### ISSUE TITLE
Kibana Timelion vs Grafana for Successful Calls and Registers

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/heplify-server#100]
Trying to duplicate the Grafana successful calls/register graph in Kibana/Timelion.  Using a query to count the '200 OK' response when cseq.method = REGISTER or INVITE, respectively.   Timelion syntax used:
.es(index=heplify-server-*, timefield=Timestamp,q='SIP.Cseq.Method:REGISTER AND SIP.StartLine.Resp:200', metric=count).scale_interval(1s).color(#1e6ca7).lines().label("Successful Registers").legend(position=nw,showTime=true), .es(index=heplify-server-*, timefield=Timestamp,q='SIP.Cseq.Method:INVITE AND SIP.StartLine.Resp:200', metric=count).scale_interval(1s).color(#f0882f).lines().label("Successful Invites")

Graphs are not lining up between the two.

Questions:  In Grafana, how are you able to ensure that the same sip message isn't counted multiple times if it's reported by different servers in the call path?  i.e. the 200 OK will traverse a few servers before hitting the endpoint, each of those servers have heplify-client running.  

FYI - the grafana graph is spot on.  Using SIPP to generate different traffic rates, and the grafana chart reflects the CPS and RPS rates perfectly.

**Comment by lmangani** [comment]
@JonConnor any reason why not using the already correctly formed statistics heplify-server can generate for this specific purpose?

**Comment by JonConnor** [comment]
@lmangani mainly because i didn't know how lol.  I know you mentioned before to use Telegraf to send these stats somehow but i didn't look into that route.   Will look into it now.

**Comment by lmangani** [comment]
I highly suggest this route - as you have noticed, the way statistics are calculated is not plain, this should allow reproducing a 1:1 statistics scenario in ES without the need to collect the originating traffic at all. If you need help let me know, happy to sidetrack in case of blockers.

**Comment by lmangani** [comment]
@JonConnor btw If you're using docker, I can provide a variant including Telegraf from the "other" bundle to cover this role

**Comment by lmangani** [comment]
It appears you could also use [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-prometheus-collector.html) to fetch the prometheus metrics, too. I've never tried this but it looks potentially adequate.

**Comment by JonConnor** [comment]
@lmangani yes i'm using docker.  Would definitely try it out if you provided the telegraf role.  haven't played with metricbeat but i'll do that and post any learnings.

**Comment by lmangani** [comment]
@JonConnor You can find a working telegraf config [here](https://github.com/sipcapture/homer-docker/blob/master/heplify-server/hom5-hep-elastic/conf/telegraf.conf) and compose example [here](https://github.com/sipcapture/homer-docker/blob/master/heplify-server/hom5-hep-elastic/docker-compose.yml#L77) to play with

**Comment by JonConnor** [comment]
cool, question on this param:
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://heplify-server:9096/metrics"]

the prometheus docker runs on port 9090 but has a username/password that's needed to authenticate.  I assume i can just add the user/pass directly in the http string..?

also, is there a diff between using prometheus port (9090) versus the grafana port (3000)?  if i go to the grafana url:port/metrics, i also get the metrics output page.

**Comment by lmangani** [comment]
@JonConnor not sure how you're spinning up your stack but ideally you should make the telegraf container part of the bundle and let it communicate internally with heplify and its metrics - this will bypass caddy and its authentication for internal communication. If you use one of our compose files you can just add the telegraf containers from the example.

**Comment by JonConnor** [comment]
yeah that's what i did, added the following the the docker-compose.yml from negbie i've been using:
  telegraf:
    image: telegraf:1.5-alpine
    restart: unless-stopped
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8125:8125/udp"
    depends_on:
      - heplify-server

then i created a conf directory and added the telegraf.conf file that you referenced.  

i wasn't sure what to modify for the metrics url.   right now elasticsearch is showing all the http metrics of prometheus, so it's sending the data, just not the sip metrics i was looking for.

**Comment by lmangani** [comment]
Keep in mind the Grafana/Chronograf dashboards only use metrics and tags (there's nothing else shipped there) so you should be able to eventually replicate them with a bit of patience in Elasticsearch too. What's missing?

**Comment by JonConnor** [comment]
i'm not seeing any of the heplify_ metrics show up, but i see others like http_metrics.  eg:

   "@timestamp": "2018-07-06T22:08:10Z",
    "measurement_name": "prometheus_http_request_duration_seconds",
    "prometheus_http_request_duration_seconds": {
      "1": 6,
      "3": 6,
      "8": 6,
      "20": 6,
      "60": 6,
      "120": 6,
      "0.1": 6,
      "0.2": 6,
      "0.4": 6,
      "count": 6,
      "sum": 0.015758611000000002
    },

**Comment by lmangani** [comment]
Unless I'm mistaken, here's the original expression to port from Grafana into Kibana/Timelion: 
```
(sum(increase(heplify_method_response{target_name=~"$tn", method="INVITE", response="200"}[5m]))) / (sum(increase(heplify_method_response{target_name=~"$tn", method="INVITE", response="INVITE"}[5m])) - (sum(increase(heplify_method_response{target_name=~"$tn", method="INVITE", response=~"3.*|401|407"}[5m])) or sum(up) * 0)) * 160 * sum(rate(heplify_method_response{target_name=~"$tn", method="INVITE", response="INVITE"}[5m]))
```
  
I am not fond of the timelion syntax but here's my untested kickstarter for corrections and fun:
```
.es(index=hep-*, timefield=@timestamp,q='tag.method:INVITE AND tag.response:200', metric=count).scale_interval(1m).color(#00ff00).lines().label("Successful Invites").legend(position=nw,showTime=true).derivative().sum().divide(
.es(index=hep-*, timefield=@timestamp,q='tag.method:INVITE AND tag.response:INVITE', metric=count).scale_interval(1m).sum().subtract(
  .es(index=hep-*, timefield=@timestamp,q='tag.method:INVITE AND tag.response:3*|401|407', metric=count).scale_interval(1m).sum()).multiply(160).multiply(
  .es(index=hep-*, timefield=@timestamp,q='tag.method:INVITE AND tag.response:INVITE', metric=count).scale_interval(1m).sum()
  )
)
```

**Comment by JonConnor** [comment]
yeah i'm not even at that point.  Still struggling with the right config file i guess.
when using this in telegraf.conf:  
http://heplify-server:9096/metrics

I don't get anything showing up in elasticsearch.  

If i change it to the prometheus url (ip-address:9090/metrics), i get data but none of the heplify_* metrics.

**Comment by JonConnor** [comment]
still struggling with the getting the configuration proper.  Error when starting the docker:

telegraf_1        | 2018-07-07T01:44:30Z E! Error in plugin [inputs.prometheus]: error making HTTP request to http://heplify-server:9096/metrics: Get http://heplify-server:9096/metrics: dial tcp: lookup heplify-server on 127.0.0.11:53: no such host

tried using 0.0.0.0 instead of heplify-server,  got connection errors with that.

**Comment by JonConnor** [comment]
found the issue was in my docker-compose config.  was missing the following for the telegraf section:
    networks:
      - monitor-net

**Comment by JonConnor** [comment]
@lmangani tweaked some timers and now getting metrics appear in elasticsearch every 10 seconds.  However seeing this warning as well ... is it something i should be concerned with?

telegraf          | 2018-07-07T13:43:50Z W! Skipping a scheduled flush because there is already a flush ongoing.
telegraf          | 2018-07-07T13:44:30Z W! Skipping a scheduled flush because there is already a flush ongoing.
telegraf          | 2018-07-07T13:44:50Z W! Skipping a scheduled flush because there is already a flush ongoing.
telegraf          | 2018-07-07T13:45:10Z W! Skipping a scheduled flush because there is already a flush ongoing.
telegraf          | 2018-07-07T13:45:40Z W! Skipping a scheduled flush because there is already a flush ongoing.

**Comment by lmangani** [comment]
@JonConnor you need to adjust the `flush_interval` to get rid of that - I guess you have enough data to cause a little of queuing in Telegraf perhaps.

**Comment by lmangani** [comment]
@JonConnor curious if you managed to reproduce the formulas you wanted. Any good set would be a great contribution for us to add as defaults.

**Comment by JonConnor** [comment]
@lmangani was away this past week.  Definitely will share if I get the timeline formulas working.

**Comment by JonConnor** [comment]
![grafana successful invites registers](https://user-images.githubusercontent.com/39862433/42957980-365f34dc-8b52-11e8-93f5-e00d8a54bed0.png)
![kibana successful invites registers](https://user-images.githubusercontent.com/39862433/42957981-366a966a-8b52-11e8-81fc-a8d386153f1d.png)

**Comment by JonConnor** [comment]
Timelion syntax:  .es(index=hepmetrics-*, timefield=@timestamp,q='measurement_name:"heplify_method_response" AND tag.method:"REGISTER" AND tag.response:"200"', metric=max:heplify_method_response.counter).derivative().abs().mvavg(1m).scale_interval(1s).yaxis(min=0).color(orange).lines(fill=2,width=1).label("RPS").legend(position=nw,showTime=true), .es(index=hepmetrics-*, timefield=@timestamp,q='measurement_name:"heplify_method_response" AND tag.method:"INVITE" AND tag.response:"200"', metric=max:heplify_method_response.counter).derivative().mvavg(1m).scale_interval(1s).yaxis(min=0).color(green).lines(fill=1,width=1).label("CPS")

also had to set the Interval dropdown to 10seconds, since the metrics were coming in every 10 seconds.

**Comment by lmangani** [comment]
@JonConnor thanks for confirming this works - I'll add it to the readme for now. Got a Kibana Dashboard JSON with this or anything else interesting to contribute for inclusion as preset by any chance?
