### ISSUE TITLE
Setting up Heplify to read from pcap files 

### ISSUE THREAD

**Issue by sergani** [sipcapture/heplify-server#101]
Hello, 

I'm trying to get Heplify to read from pcap files, so far I'm able to get the standalone server to run and connect to a local host MySQL DB. 

Can anyone point me towards the right direct? Where do I configure Heplify to read from pcap files? 

Also, how do I access the web interface once the server is setup correctly? 

Thank you. 
//M

**Comment by lmangani** [comment]
Hi

You should check out [heplify](https://github.com/sipcapture/heplify) as starting point instead as that's the element able to read PCAPs or capture from wire, just like Captagent would. 

Once you have that figured, it will be ready to send HEP encapsulated data to a HOMER setup. If you are looking into installing HOMER, check out the various options. Hope this helps!

**Comment by sergani** [comment]
Hi Lorenzo, 

Thank you for your feedback. 

I've installed Heplify as you suggested, but I can't get it to read the PCAPs, can you tell me how to configure it to do so? 

I get your second point regarding HOMER, I'll be working on a setup once I'm able to get Heplify to "HEP"lify the PCAPs and send them to HOMER.

Appreciate the support. 

Thanks

**Comment by lmangani** [comment]
Check out [heplify](https://github.com/sipcapture/heplify) and you will see right in the main readme the option `-rf   Read pcap file`

**Comment by sergani** [comment]
Thank you! 
Don't know how I many times I looked there and didn't see it.
