### ISSUE TITLE
PCAP timestamp not sent to DB

### ISSUE THREAD

**Issue by sergani** [sipcapture/heplify-server#102]
Hi, 

I've successfully got heplify to read from pcap file, and send it over to the heplify-server. 

I am testing with pcap files from 20180707 (yesterday), but I can see them entering the DB as if they were captured now, not even today at the same time of yesterday - no, just now. 

Is there a way to read from pcap and read the packets' timestamps too?

Thanks
//M

**Comment by lmangani** [comment]
Not an issue with `heplify-server` FYI the packet timestamp is inserted by the capture agents, the servers just stores them as received and applies a timestamp for those missing it.

**Comment by negbie** [comment]
@sergani use heplify like that:

./heplify -rf test.pcap -rs

**Comment by negbie** [comment]
-rs will insert with original timestamps

**Comment by lmangani** [comment]
@negbie readme updated

**Comment by negbie** [comment]
@sergani I think you talk about heplify-server and not heplify because heplify won't insert anything. Yes heplify-server will only insert realtime traffic and not by provided timestamps. What you want can easily be done with good old sql.

**Comment by sergani** [comment]
Thanks Eugen, that makes sense.

//M
