### ISSUE TITLE
Seeting up the UI on heplify-server

### ISSUE THREAD

**Issue by Julian-Mentasti** [sipcapture/heplify-server#104]
Hey negbie,

I set up a heplify-server with docker and connected my client and it all works fine. I'm now looking for the domain to look at the Homer UI although I cant find it. 

I know that nginx, php, and apache are running but the directory /var/www/html does not exist. 

Maybe its not set up. 

the server is also producing the following:

```
adminer_1         | [Thu Jul 12 22:43:58 2018] ::ffff:OMITTED:40695 [200]: /
adminer_1         | [Thu Jul 12 22:45:16 2018] ::ffff:OMITTED:7299 [200]: /
alertmanager      | level=error ts=2018-07-12T22:45:29.85267626Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="dial tcp 127.0.0.1:25: connect: connection refused"
alertmanager      | level=error ts=2018-07-12T22:45:29.852946163Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="dial tcp 127.0.0.1:25: connect: connection refused"
```

**Comment by negbie** [comment]
Yes you need to create this folder, put 
https://github.com/sipcapture/homer-ui
https://github.com/sipcapture/homer-api
inside. Then rename
/var/www/html/api/configuration_example.php to configuration.php
/var/www/html/api/preferences_example.php to preferences.php
and edit configuration.php

**Comment by negbie** [comment]
You can look into the installer script. There you should find all the steps you need to do by hand.
