### ISSUE TITLE
Ignoring some message type

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#108]
Hello,

My captagents capture inter-server flows that are not fully sip, i don't want do insert them in DB for the moment, but as they are not parsable i get 3 log lines any time that overflow my logfiles (in docker).

Is there a way to ignore those parckets for the logs ?

Bellow are the log example with the headers (CGPSIP and CGPRELAY).

{"log":"2018/07/16 09:30:11.135871 decoder.go:101: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly\n","stream":"stderr","time":"2018-07-16T09:30:11.136073595Z"}
{"log":"\"CGPSIP/udp[

{"log":"2018/07/16 09:30:11.137306 decoder.go:101: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly\n","stream":"stderr","time":"2018-07-16T09:30:11.137415149Z"}
{"log":"\"CGPRELAY/tcp

Thanks

**Comment by negbie** [comment]
You can set LogLvl to error and heplify-server will only errors

**Comment by dvillaume** [comment]
You're true, ill enable more dtailed log if i find missing packets.

Thanks
