### ISSUE TITLE
Multiple captagent

### ISSUE THREAD

**Issue by gamishaev** [sipcapture/heplify-server#109]
Hello. Is there are way to target heplify-server metrics for each captagent instance? As long as there is more than one captagent.

**Comment by negbie** [comment]
Hi,
would be the nodeid defined as tag enough for you?

**Comment by gamishaev** [comment]
I think so, how can this be realized?

**Comment by gamishaev** [comment]
Thanks!

**Comment by negbie** [comment]
Done https://github.com/sipcapture/heplify-server/commit/9914d71cfaea00c0e063c53ac2df3b32a68f0212

Do you need a new release or do you build it from source?

**Comment by negbie** [comment]
For now I did this for the heplify_method_response metric if you need it for something else tell me your usecase and we can talk about it ;)

**Comment by gamishaev** [comment]
I'll try to assemble. I will test and write the result.
