### ISSUE TITLE
Handler for missing HEP TS

### ISSUE THREAD

**Issue by lmangani** [sipcapture/heplify-server#111]
When sending an HEP packet w/o Timestamp (`time_sec + time_usec`) headers, unix timestamp 0 is used.
Since HEP3 still allows for timestamp-less deliveries in general, perhaps the current time should be used to mark a packet/document delivered without accurate stamps for broader backwards compatibility future protocols lacking this ability.

**Comment by negbie** [comment]
Done https://github.com/sipcapture/heplify-server/commit/82ef5691c095e844471338cc5b1e2a0322ab6f28

Mby it's  enough to only check time_usec because in this case the resolution is most likely not good enough anyway but for now I check if both time_sec + time_usec are 0
