### ISSUE TITLE
Multiple ES IP addresses 

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/heplify-server#115]
I (now) have a 3-node cluster for Elasticsearch.  Will Heplify-Server support outputting to the 3 IPs (round-robin or whatever load balancing solution)?   If so, is it just a matter of a comma separated list of ES IPs in the config file, or do I need to specify a FQDN rather than IP?

**Comment by lmangani** [comment]
Hi @JonConnor modern Elasticsearch client should do this on its own as the ES cluster can publish back several communication endpoints for balancing upon connection. We need to check if the one being used in this case features this behavior or not already...

**Comment by negbie** [comment]
@lmangani as far as I remeber I disabled this https://github.com/sipcapture/heplify-server/blob/master/elastic/elasticsearch.go#L29

@JonConnor could you try
-esaddr ""http://127.0.0.1:9200", "http://127.0.0.1:9201""

**Comment by JonConnor** [comment]
doesn't like more than 1 URL:
heplify-server    | 2018/07/27 20:36:17.114611 elasticsearch.go:32: ERR health check timeout: no Elasticsearch node available

I'll try just creating a FQDN in DNS that will resolve into 3 addresses.  I use the same port (9200) on all nodes so hopefully that'll work.

**Comment by lmangani** [comment]
@negbie perhaps we could just make `elastic.SetSniff()` configurable via an ENV, its very useful for large clusters and takes lots of complexity away in handling multiple targets around the client, although this is a very minor feature.

**Comment by JonConnor** [comment]
@negbie oops just realized now that you meant to have me run it from the CLI with -esaddr option.  Sorry I'm use the docker image so just modified the ESADDR= param in the docker file. 
ESADDR=""http://127.0.0.1:9200", "http://127.0.0.1:9201"" --> parsing error and docker up fails.
ESADDR="http://127.0.0.1:9200, http://127.0.0.1:9201" --> no ES node available

I don't have a heplify-server instance running natively where i can pass the run level arguments.

**Comment by negbie** [comment]
@lmangani  absolutely. Do you have a better name than essniff ?
@JonConnor since docker will pass the double quotes could you try
ESADDR=http://127.0.0.1:9200,http://127.0.0.1:9201
what is your output (mask sensitive data) of

curl 'http://localhost:9200/_nodes/http?pretty'

**Comment by JonConnor** [comment]
{
  "_nodes": {
    "total": 4,
    "successful": 4,
    "failed": 0
  },
  "cluster_name": "dax-cluster",
  "nodes": {
    "zzzzzzzzzzzzzzzzzzzzzz": {
      "name": "dax-node-1",
      "transport_address": "A.B.C.D:9300",
      "host": "A.B.C.D",
      "ip": "A.B.C.D",
      "version": "6.3.2",
      "build_flavor": "default",
      "build_type": "rpm",
      "build_hash": "053779d",
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "attributes": {
        "ml.machine_memory": "33970601984",
        "ml.max_open_jobs": "20",
        "xpack.installed": "true",
        "ml.enabled": "true"
      },
      "http": {
        "bound_address": [
          "[::]:9200"
        ],
        "publish_address": "A.B.C.D:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "r_XXXXXXXXXXX": {
      "name": "dax-node-4",
      "transport_address": "E.F.G.H:9300",
      "host": "E.F.G.H",
      "ip": "E.F.G.H",
      "version": "6.3.2",
      "build_flavor": "default",
      "build_type": "rpm",
      "build_hash": "053779d",
      "roles": [],
      "attributes": {
        "ml.machine_memory": "8185651200",
        "xpack.installed": "true",
        "ml.max_open_jobs": "20",
        "ml.enabled": "true"
      },
      "http": {
        "bound_address": [
          "[::]:9200"
        ],
        "publish_address": "E.F.G.H:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "JZZZZZZZZZZZ": {
      "name": "dax-node-3",
      "transport_address": "L.M.N.O:9300",
      "host": "L.M.N.O",
      "ip": "L.M.N.O",
      "version": "6.3.2",
      "build_flavor": "default",
      "build_type": "rpm",
      "build_hash": "053779d",
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "attributes": {
        "ml.machine_memory": "33564688384",
        "ml.max_open_jobs": "20",
        "xpack.installed": "true",
        "ml.enabled": "true"
      },
      "http": {
        "bound_address": [
          "[::]:9200"
        ],
        "publish_address": "L.M.N.O:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "5kTW1SSSSSSSSA": {
      "name": "dax-node-2",
      "transport_address": "P.Q.R.S:9300",
      "host": "P.Q.R.S",
      "ip": "P.Q.R.S",
      "version": "6.3.2",
      "build_flavor": "default",
      "build_type": "rpm",
      "build_hash": "053779d",
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "attributes": {
        "ml.machine_memory": "33566806016",
        "ml.max_open_jobs": "20",
        "xpack.installed": "true",
        "ml.enabled": "true"
      },
      "http": {
        "bound_address": [
          "[::]:9200"
        ],
        "publish_address": "P.Q.R.S:9200",
        "max_content_length_in_bytes": 104857600
      }
    }
  }
}

**Comment by JonConnor** [comment]
4 nodes  (3 data nodes, 1 coordinating node for kibana).  

Also tried the suggestion above. ERROR:
ERR health check timeout: Head xxxxxxx invalid URL port "9200,http": no Elasticsearch node available
