### ISSUE TITLE
heplify-server crash with "slice bounds out of range"

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#123]
Hello,
i'm running a docker version of heplify-server  (latest :heplify-server 0.95) and see some recuring crashes :

heplify-server    | panic: runtime error: slice bounds out of range
heplify-server    | 
heplify-server    | goroutine 53 [running]:
heplify-server    | github.com/negbie/sipparser.parseUriHost(0xc4232e6a80, 0xbda1e8)
heplify-server    |     /go/src/github.com/negbie/sipparser/uri.go:231 +0xa22
heplify-server    | github.com/negbie/sipparser.(*URI).Parse(0xc4232e6a80)
heplify-server    |     /go/src/github.com/negbie/sipparser/uri.go:72 +0x37
heplify-server    | github.com/negbie/sipparser.ParseURI(0x0, 0x0, 0x0)
heplify-server    |     /go/src/github.com/negbie/sipparser/uri.go:65 +0x60
heplify-server    | github.com/negbie/sipparser.parseFromGetURI(0xc42261f880, 0xbda178)
heplify-server    |     /go/src/github.com/negbie/sipparser/from.go:71 +0x79
heplify-server    | github.com/negbie/sipparser.(*From).parse(0xc42261f880)
heplify-server    |     /go/src/github.com/negbie/sipparser/from.go:43 +0x37
heplify-server    | github.com/negbie/sipparser.getFrom(0x0, 0x0, 0x1ab)
heplify-server    |     /go/src/github.com/negbie/sipparser/from.go:109 +0x60
heplify-server    | github.com/negbie/sipparser.(*SipMsg).parseTo(0xc4232e4c00, 0x0, 0x0)
heplify-server    |     /go/src/github.com/negbie/sipparser/parser.go:545 +0x39
heplify-server    | github.com/negbie/sipparser.(*SipMsg).addHdr(0xc4232e4c00, 0xc4248500ce, 0x3)
heplify-server    |     /go/src/github.com/negbie/sipparser/parser.go:230 +0xe9b
heplify-server    | github.com/negbie/sipparser.getHeaders(0xc4232e4c00, 0xbda168)
heplify-server    |     /go/src/github.com/negbie/sipparser/parser.go:616 +0x29d
heplify-server    | github.com/negbie/sipparser.(*SipMsg).run(0xc4232e4c00)
heplify-server    |     /go/src/github.com/negbie/sipparser/parser.go:125 +0x37
heplify-server    | github.com/negbie/sipparser.ParseMsg(0xc424850000, 0x27b, 0xc42001da00, 0x1, 0x1, 0xfc0500)
heplify-server    |     /go/src/github.com/negbie/sipparser/parser.go:644 +0x171
heplify-server    | github.com/negbie/heplify-server.(*HEP).parseSIP(0xc422b98820, 0x8f01f9c2e, 0xfc0500)
heplify-server    |     /go/src/github.com/negbie/heplify-server/decoder.go:227 +0x60
heplify-server    | github.com/negbie/heplify-server.(*HEP).parse(0xc422b98820, 0xc4243da000, 0x2e4, 0x2000, 0xc421a7ef80, 0x1)
heplify-server    |     /go/src/github.com/negbie/heplify-server/decoder.go:123 +0x574
heplify-server    | github.com/negbie/heplify-server.DecodeHEP(0xc4243da000, 0x2e4, 0x2000, 0xc424053a00, 0x0, 0x0)
heplify-server    |     /go/src/github.com/negbie/heplify-server/decoder.go:85 +0x62
heplify-server    | github.com/negbie/heplify-server/server.(*HEPInput).hepWorker(0xc421766230)
heplify-server    |     /go/src/github.com/negbie/heplify-server/server/server.go:239 +0x15e
heplify-server    | created by github.com/negbie/heplify-server/server.(*HEPInput).Run
heplify-server    |     /go/src/github.com/negbie/heplify-server/server/server.go:59 +0x4c

Could you have a look if you see any reason why ? 

Thanks :)

**Comment by lmangani** [comment]
Hi @dvillaume Tell us more about your scenario, platform and configuration in use. 
This is probably due to a malformed message being passed, but its just a spontaneous guess.

**Comment by negbie** [comment]
Hi,

it's obvious thats this comes from the sipparser. So for sure it's a malformed message which is not handled properly in this line:
https://github.com/negbie/sipparser/blob/master/uri.go#L231

I will check that.

**Comment by negbie** [comment]
@dvillaume I still have no idea how you could craft a message to be out of the slice bound at this code block. Anyway I add a additional safety check
https://github.com/negbie/sipparser/commit/cbd197b09a139cf02af99cbe0629f95e701d90b5

If you still get crashes there something fishy is going on...
I will rebuild the containers in 2-3 hours

**Comment by dvillaume** [comment]
I rebuilt and launched it last night.

I don't see crashes anymore, i'll check again tonight and will tell you. 

Thanks .

**Comment by negbie** [comment]
Your welcome and thanks for the feedback!

**Comment by dvillaume** [comment]
No crash today, you're a chief.
