### ISSUE TITLE
heplify-server-docker

### ISSUE THREAD

**Issue by siptesterprofi1** [sipcapture/heplify-server#130]
past installation no show Templates 

error failure :Could not resolve all promises by homer5

**Comment by negbie** [comment]
Could you please provide more information? Is it the prometheus bundle? Do you have some old container images?

**Comment by siptesterprofi1** [comment]
i have install https://github.com/sipcapture/heplify-server.git 
The installation is ok and work ok 
The one and only error is by homer container Could not resolve all promises

**Comment by negbie** [comment]
Please paste the full docker log here.

**Comment by siptesterprofi1** [comment]
All stats dashboards are empty for me, just blanks. .

I did check that Mysql have all data in table thats Ok 

I need a answer of my problem. I think it id a php Problem
i have it a make secound installation with the same succses.

a fundamental problem of your software? Bug?

**Comment by negbie** [comment]
@siptesterprofi1 I think you have the same so look here:
https://github.com/sipcapture/heplify-server/issues/131
