### ISSUE TITLE
Docker image does not contain homer_statistic db

### ISSUE THREAD

**Issue by lexxua** [sipcapture/heplify-server#131]
Hi I tried to use docker image with homer5, looks like all works fine. But SIPCapture Charts return that "Could not resolve all promises". Basic check with curl returns to me following:
{
    "status": 500,
    "error": "PDOException",
    "message": "SQLSTATE[42000] [1049] Unknown database 'homer_statistic'"
}
And show databases looks like:
MariaDB [homer_data]> show databases;
+---------------------+
| Database            |
+---------------------+
| homer_configuration |
| homer_data          |
| information_schema  |
| mysql               |
| performance_schema  |
+---------------------+
5 rows in set (0.001 sec)

MariaDB [homer_data]>

My question is: Heplify server supports statistic db or not?
Thanks.

**Comment by negbie** [comment]
It does not use statistic db. It's designed to expose a http metrics endpoint which can be used by Prometheus or Telegraf. If you've used the docker compose file you should have a running Grafana container which you can use to graph your stats.

**Comment by lexxua** [comment]
Hi,
Thanks for the explanation!

**Comment by negbie** [comment]
Your welcome.

**Comment by quadrinary** [comment]
Thanks for the explanation, now how do i point the container to Grafana?
