### ISSUE TITLE
Where do I get the stats

### ISSUE THREAD

**Issue by cerienj** [sipcapture/heplify-server#14]
Sorry to be a noob. I've installed the docker images, I have a homer v5 running, I am feeding sip & rtcp data to port 9060 of the instance, but I only see classic homer v5 data, I see no new data in homer databases.
I am looking for rtpc / qos stats !
J.

**Comment by lmangani** [comment]
have you used the `homer-heplify` compose or did you just swap kamailio with heplify? Mind heplify v1 works in homer v5 emulation mode unless you plug a prometheus instance to it on a custom port, ie: `PromAddr  = "0.0.0.0:8899"`

**Comment by cerienj** [comment]
Yes, I did use the docker compose in the homer-heplify directory.
What I am looking for, may be I'm wrong, is a global view on the QOS - view meaning anything from a sql table to a gui. I'd like to be able to find the calls that have had issues, evaluate the calls with packet loss, with jitter, etc... and get a good feel if the system is smooth or not. Current HOMER requires you to go  to each call and check the data

**Comment by lmangani** [comment]
Feel free to experiment using the prometheus stats and testers, but it will not do what you think it will just yet magically without any effort :) You'll have to wait for HOMER 7
