### ISSUE TITLE
Best way of setup heplify-server

### ISSUE THREAD

**Issue by sfrique** [sipcapture/heplify-server#148]
Hello,

I am trying to run this setup for testing:
heplify-server, postgres prometheus running on a kubernetes cluster.
my kamailio uses TLS, i tried to run hepifly on it, but got errors probably becasue of TLS

the error:
```
2018/12/07 20:32:55.708021 decoder.go:125: WARN parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly
"\x01\x10\x02\x16\x13Żh?-\n\tSIP/2.0 200 OK\r\nVia: SIP/2.0/TLS X.X.X.X:5061;branch=z9hG4bKc87c.c11cd6c26611a5c17315f0be37b1142d.0;i=c76e;rport=48030\r\nVia: SIP/2.0/TLS X.X.X.X:48267;received=X.X.X.X;rport=48267;branch=z9hG4bKPjvE3QEkx5D9ogZ3q-UattgRrvXzHF4ODl;alias\r\nFrom: <sip:testcaller.b(domain.com)@X.X.X.X>;tag=DJLSeQEyOMrRZkGrB.-O0vfboRjVbIID\r\nTo: <sip:0000000000@X.X.X.X>;tag=BX4r2N2Bpv6tH\r\nCall-ID: SC-B-0-jSo8yu.aM3fgzglaMKsJm12WUnFh2fi3\r\nCSeq: 9771 BYE\r\nUser-Agent: 2600hz\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE\r\nSupported: timer, path, replaces\r\nContent-Length: 0\r\n\r\n"
nodeID: 2002, protoType: 1, version: 2, protocol: 17, length: 666, flow: 10.240.0.9:5060->10.240.0.24:9060
```

So I need to configure my kamailio to send it directly to heplify-server using siptrace?
I tried but then got this error:
```
2018/12/07 20:45:21.987002 decoder.go:103: WARN malformed packet with length 632 which is neither hep nor protobuf encapsulated
2018/12/07 20:45:24.049094 decoder.go:103: WARN malformed packet with length 670 which is neither hep nor protobuf encapsulated
2018/12/07 20:45:24.060466 decoder.go:103: WARN malformed packet with length 798 which is neither hep nor protobuf encapsulated
```

What is the suggestion to this setup?

Thanks

**Comment by negbie** [comment]
Hi,
in case of TLS you need to forward the decrypted traffic by setting something like
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "duplicate_uri", "sip:heplify-serverIP:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "hep_capture_id", 2222)

Blindly guessed I would say you did not set modparam("siptrace", "hep_version", 3) and since the default value is 1 and heplify-server only supports 3 you get those warnings.

Do you want to use homer 5? If so I wouldn't recommend postgres.

**Comment by sfrique** [comment]
Hi
Thanks for the info!

So it won't work. I am at older version of kamailio, and it doesn't support hep_version 3. ='[

I want to use homer7
In fact we already have a homer5 setup working. but is quite outdated and the installation isn't automated/documented well.

So looking on how to test/update i found homer7 and was playing with it on kubernetes.
(we are moving everything to kubernetes)

It seems i just need to wait more/upgrade more parts of my stack before using it.

by the way, i was able to get some data into homer7 (postgres) by using my hepipejs on FS instance, I couldn't get the data to appear on homer7 web, but since I won't be able to use it for now, I will just drop it the way it is.

If you want I do have a really basic helm chart form homer7, i may be able to do small changes and open it. (still very very simple)  
I was planing on adding to helm/charts/incubator later on, but now I won't be doing much effort on it.

Thanks anyway!

Looking forward to homer7 become stable!

**Comment by lmangani** [comment]
@sfrique H7 is quite stable already. we have some basic helm charts if you are interested inside our rancher-catalog repository. Make sure you use the very latest builds of our containers using the `master` tag to get the latest versions up

**Comment by sfrique** [comment]
@lmangani I will take a look, my chart is done already also.

Even if i'ts stable, I probably won't be updating our kamailio anytime soon =/

I will make a note and see if we can update or kamailios.

Whats the recommended way of capturing of H7 for freeswitchs? 
this?  
`<param name="capture-server" value="udp:192.168.0.1:9060;hep=3;capture_id=100"/>` 
or hepipejs, or both etc

We use TLS if we can.

Thanks for the info on stability, that may make us push on kamailio update!

**Comment by sfrique** [comment]
Thank you, this will be really helpful! I may migrate homer5 to kubernetes with it, will take a look at those charts! 

https://github.com/QXIP/rancher-catalog

**Comment by negbie** [comment]
@sfrique another thing you can do is a tls->udp proxy. Terminate the TLS traffic and send it over UDP to kamailio. I do this for example for some server because kamailios TLS implementation isn't the stablest one. This would allow you to use heplify.

**Comment by negbie** [comment]
I guess I can close this ;)
