### ISSUE TITLE
filepath invalid character '

### ISSUE THREAD

**Issue by Gudeen** [sipcapture/heplify-server#164]
when i execute "go build cmd/heplify-server/heplify-server.go", it results in following error:
-> unzip /root/go/pkg/mod/cache/download/github.com/negbie/heplify-server/@v/v0.0.0-20181221112811-5429c3f96f6e.zip: malformed file path "docker/hep-prom-graf/grafana/provisioning/dashboards/SIP_KPI's.json": invalid char '\''

maybe the dashboard could be renamed without the "'" character for better compatibility?

**Comment by negbie** [comment]
Hi @Gudeen 
thanks for the hint, I will look into it.

**Comment by negbie** [comment]
@Gudeen should be fixed now.

**Comment by Gudeen** [comment]
Yes, it works now :-)
Thank you
