### ISSUE TITLE
Fields not populated in index

### ISSUE THREAD

**Issue by Alan01252** [sipcapture/heplify-server#172]
Hi,

Firstly thank you for this! I've managed to get almost everything up and running in K8's using your examples. 

The last problem I have is that in elasticsearch although I can see plenty of potential fields around the SIP call none of them are populated.

I'm using Freeswitch with HEP enabled, sending via heplify-server which sends to prometheus and graphana, where I can see charts of the calls being correctly populated.

I'm then using telegraph to forward the logs into elastic search, where I can see the logs which look  a little like this:

`
@timestamp:December 28th 2018, 16:33:00.000 heplify_packets_total.counter:77 measurement_name:heplify_packets_total tag.host:telegraf-6fbf7666cb-8pfkp tag.type:sip tag.url:http://heplify-server:9096/metrics _id:4mSp9WcB9KjhsTkXa4OX _type:metrics _index:hep-2018.12.28 _score: -
@timestamp:December 28th 2018, 16:33:00.000 heplify_method_response.counter:11 measurement_name:heplify_method_response tag.host:telegraf-6fbf7666cb-8pfkp tag.method:INVITE tag.node_id:6553600 tag.response:200 tag.url:http://heplify-server:9096/metrics _id:6GSp9WcB9KjhsTkXa4OX _type:metrics _index:hep-2018.12.28 _score: -
`

So I can see the invite in there but no other meta information around the call. I'm pretty sure I'm missing something obvious here so any help would be appreciated.

P.S do you have a slack channel for these type of questions?

**Comment by Alan01252** [comment]
Fixed....

I was using the wrong index hep- index rather than the heplify-server-2018-12-2 index..

**Comment by lmangani** [comment]
This is what you're looking for: https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-elastic

Please consider sharing back your K8S charts ;)

**Comment by Alan01252** [comment]
Thanks, @lmangani I hope to share once I've got everything a little bit tidied up :)
