### ISSUE TITLE
Invalid PostGRES byte Sequence

### ISSUE THREAD

**Issue by UzairM** [sipcapture/heplify-server#180]
Some of my packets are not making it into the postgres database due to addition of 0x00 character at the end of the sip packet. 
The log is as follows:
ERR pq: invalid byte sequence for encoding "UTF8": 0x00

2019/02/01 10:43:57.309923 postgres.go:262: ERR "SIP/2.0 200 OK\r\nVia: SIP/2.0/UDP 10.0.1.1:11000;branch=z9hG4bKH256a1FF4cDeS;received=10.0.1.1;rport=11000\r\nRecord-Route: <sip:10.0.1.2;lr;ftag=XDmHByK8Ue03j>\r\nCall-ID: f95b241c-260e-11e9-bbc4-793f36e89cab\r\nFrom: \"59413\"<sip:dinstar1@frec.pbx>;tag=XDmHByK8Ue03j\r\nTo: <sip:58029@frec.pbx>;tag=ez4vjg9p\r\nCSeq: 134173004 INVITE\r\nContact: <sip:58029@10.0.2.40:5060;user=phone>;expires=1800\r\nSupported: 100rel\r\nAllow: INVITE,ACK,OPTIONS,BYE,CANCEL,REGISTER,INFO,PRACK,SUBSCRIBE,NOTIFY,UPDATE,REFER,MESSAGE\r\nUser-Agent: HUAWEI eSpace IAD1224/V300R002C01SPCm00\r\nContent-Length: 214\r\nContent-Type: application/sdp\r\n\r\nv=0\r\no=58029 3025098750 3025098750 IN IP4 10.0.2.40\r\ns=-\r\nc=IN IP4 10.0.2.40\r\nt=0 0\r\nm=audio 50112 RTP/AVP 0 101\r\na=sendrecv\r\na=rtpmap:0 PCMU/8000\r\na=ptime:20\r\na=rtpmap:101 telephone-event/8000/1\r\na=fmtp:101 0-15\r\n 0-15\r\n_**\x00\x00\x00\x00\x00\x00\x00\x00\x00**_"

2019/02/01 10:43:57.309947 postgres.go:265: ERR pq: Could not complete operation in a failed transaction

**Comment by negbie** [comment]
Fix in latest commit.

**Comment by UzairM** [comment]
thankyou
