### ISSUE TITLE
 Question about your tweet : 132K pps and about 80% CPU Usage

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#186]
Hi,

I saw your tweet a few days ago, and i was wondering if data were sent to database ?

If so i would be really interested by seeing your db settings because i'm pretty far of your pefs even if i'm very glad of what i have.

Regards 

David

**Comment by negbie** [comment]
Hi,
first some infos. The benchmark was done with hammerhep https://github.com/negbie/hammerHEP
which sends about 800 byte large SIP OPTIONS
Server had 8 disks in raid 10
cat /sys/block/sdb/queue/scheduler
[noop] deadline cfq
We tested with postgres so homer7 shema was used which is faster than homer5 shema.

So when you don't use hammerhep, have at least 8 disks in raid 10 and use homer7 shema you cannot compare.

**Comment by negbie** [comment]
And of course the postgres config was tuned too.

**Comment by negbie** [comment]
The postgres config:

# Connectivity
max_connections = 100
superuser_reserved_connections = 3

# Memory Settings
shared_buffers = '8192 MB'
work_mem = '32 MB'
maintenance_work_mem = '520 MB'
huge_pages = try   # NB! requires also activation of huge pages via kernel params, see here for more:
                   # https://www.postgresql.org/docs/current/static/kernel-resources.html#LINUX-HUGE-PAGES
effective_cache_size = '22 GB'
effective_io_concurrency = 200   # concurrent IO only really activated if OS supports posix_fadvise function

# Monitoring
shared_preload_libraries = 'pg_stat_statements'    # per statement resource usage stats
track_io_timing=on        # measure exact block IO times
track_functions=pl        # track execution times of pl-language procedures if any

# Replication
wal_level = minimal		# consider using at least 'replica'
max_wal_senders = 0
synchronous_commit = off
wal_keep_segments = 1290

# Checkpointing:
checkpoint_timeout  = '15 min'
checkpoint_completion_target = 0.9
max_wal_size = '10240 MB'
min_wal_size = '5120 MB'


# WAL writing
wal_compression = on
wal_buffers = -1    # auto-tuned by Postgres till maximum of segment size (16MB by default)

# Background writer
bgwriter_delay = 200ms
bgwriter_lru_maxpages = 100
bgwriter_lru_multiplier = 2.0
bgwriter_flush_after = 0

# Parallel queries:
max_worker_processes = 16
max_parallel_workers_per_gather = 8
max_parallel_maintenance_workers = 8
max_parallel_workers = 16
parallel_leader_participation = on

# Advanced features

enable_partitionwise_join = on
enable_partitionwise_aggregate = on
jit = on
jit_above_cost = 100000
jit_optimize_above_cost = 500000
jit_inline_above_cost = 500000

**Comment by negbie** [comment]
heplify-server config:
HEPAddr         = "0.0.0.0:9060"
HEPTCPAddr      = ""
HEPTLSAddr      = "0.0.0.0:9060"
ESAddr          = ""
ESDiscovery     = true
MQDriver        = ""
MQAddr          = ""
MQTopic         = ""
PromAddr        = ""
PromTargetIP    = ""
PromTargetName  = ""
DBShema         = "homer7"
DBDriver        = "postgres"
DBAddr          = "localhost:5432"
DBUser          = "postgres"
DBPass          = "newroot"
DBDataTable     = "homer_data"
DBConfTable     = "homer_config"
DBTableSpace    = ""
DBBulk          = 2000
DBTimer         = 20
DBBuffer        = 400000
DBWorker        = 8
DBRotate        = true
DBPartLog       = "30m"
DBPartSip       = "30m"
DBPartQos       = "30m"
DBDropDays      = 14
DBDropOnStart   = false
Dedup           = false
DiscardMethod   = []
AlegIDs         = []
LogDbg          = ""
LogLvl          = "info"
LogStd          = false
Config          = "./heplify-server.toml"
Version         = false

**Comment by negbie** [comment]
When you use mysql you need to tune mainly

innodb_buffer_pool_size
innodb_log_file_size
innodb_log_buffer_size
innodb_log_files_in_group
innodb_file_per_table
innodb_flush_method
innodb_flush_log_at_trx_commit
innodb_use_native_aio
innodb_numa_interleave
innodb_io_capacity
innodb_write_io_threads
innodb_read_io_threads
innodb_lru_scan_depth

**Comment by dvillaume** [comment]
Hi Eugen,

Thanks for the tips.
I'm still using V5 With mysql, I'll have a look on some parameters you
mentioned as i didn't figured yet some of them.
Do you think the heplify-server settings you provided fits mysql as well ?
DBBulk = 2000
DBTimer = 20
DBBuffer = 400000
DBWorker = 8
DBRotate = true
DBPartLog = "30m"
DBPartSip = "30m"
DBPartQos = "30m"

Thanks again.
David


Le jeu. 14 févr. 2019 à 17:55, Eugen Biegler <notifications@github.com> a
écrit :

**Comment by negbie** [comment]
Hi,

yes you can ;) Just keep in mind that v5 won't be as fast as v7 and the main bottleneck is mostly disk IO and your database settings. It takes a long time to go through the mysql/mariadb documentation and understand all those settings.

**Comment by dvillaume** [comment]
Thanks a lot for you answer and your time.

Have a nice Week-end

David

**Comment by dvillaume** [comment]
Thanks a lot for you answer and your time.

Have a nice Week-end

David
