### ISSUE TITLE
Feature Request: DB Tables drop configurable

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify-server#187]
I was wondering if you can do it so that the different tables have different days to be stored.
Currently it is only controlled by DBDropDays.

My disk is used up mostly by registeration messages. probably willing to keep register messages up to a week and call traces up to a month.

Thank You

**Comment by negbie** [comment]
Hi,
it's easy to implement but right now I have no idea how the config should look like. Mby:
DBDropTableDays = ["sip:7","reg:3","rest:1"]
Right now I did not find something I really like. Maybe you have some better ideas?

**Comment by games130** [comment]
looks good to me. previously i was thinking additional fields
DBDropTableDaysSIP = 7
DBDropTableDaysREG = 3
DBDropTableDaysREST = 1

**Comment by lmangani** [comment]
Days seems a little bit high-resolution as opposed to seconds or hours?

**Comment by games130** [comment]
I don't think we need it to be hour or seconds as it will defeat the purpose of storing all these SIP messages. Complains usually dont come in that fast - so it is good to keep a few days at minimum.

**Comment by negbie** [comment]
@games130 please take a look at this commit https://github.com/sipcapture/heplify-server/commit/05b7ef45cda0b296aa328c86b1d86fd94e7ee889

Sorry for the delay but I was and will be busy the next months. The new config parameters are:
DBDropDaysCall
DBDropDaysRegister
DBDropDaysRest

and have 0 as default which means they will use DBDropDays

**Comment by negbie** [comment]
@games130 one notice. I renamed DBDropDaysRest to DBDropDaysDefault. So this options are new:
DBDropDaysCall
DBDropDaysRegister
DBDropDaysDefault

**Comment by negbie** [comment]
DBDropDaysCall will drop following methods:
"INVITE", "UPDATE", "BYE", "ACK", "PRACK", "REFER", "CANCEL", "INFO"

DBDropDaysRegister
"REGISTER"

DBDropDaysRegister
All other SIP Methods not listed above

**Comment by games130** [comment]
Just to update, i finish testing it and it is working fine. 
Thank You 👍
