### ISSUE TITLE
Import paths and go.mod refer to negbie/heplify-server

### ISSUE THREAD

**Issue by pdf** [sipcapture/heplify-server#188]
Can't build this project properly in its current state - if this is the official location for the project, please replace references to the (old?) repository.

**Comment by negbie** [comment]
Hi Peter,
sorry for the delayed respone. If you want to build it yourself without having sources from negbie and sipcapture repo I would suggest you to build from https://github.com/negbie/heplify-server. My workflow is to push there first and merge later into this repo. Mby someday I just push only to this repo and will change the import path but not for now.

**Comment by pdf** [comment]
At the time I created this issue, _this_ repo was ahead of negbie/heplify-server, so it's not about not wanting to have that repo checked out, it's about the following:

- there's no source of truth for the project's code, it's entirely unclear which repo people are meant to refer to
- if changes are committed to sub-packages here (eg - thanks to PRs, as appears to have happened in the past) there is no way to actually build those changes, because the import paths point to the other repo
- this repo cannot be built with go modules enabled
- breaking changes make this repo unbuildable any time the two out of sync, so CI/CD cannot use this repo, however this repo is the only one with tagged releases

I can't see any justification for the workflow you've described - either this repo should not exist, or the project should be fixed to build from here, and this should be the primary repo.  If you want to stage development changes, just use git branches - that's what they're for.

I think it would be very unfortunate to underestimate the importance of this issue - the project in its current state is confusing, doesn't inspire confidence, and significantly hampers potential contributors.

**Comment by negbie** [comment]
Thank you for taking your time writing this. All your points are valid so the only logical step is https://github.com/sipcapture/heplify-server/commit/1f9f5de76ce3e4c314365101455ebc37e42153c0

Please try building from here again and sorry inconvenience.

**Comment by pdf** [comment]
Thanks @negbie I can confirm with this change, I'm able to build from this repo.  Appreciate the consideration.
