### ISSUE TITLE
Missing \x00 makes corrupted pcap exports

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#193]
Hi Eugen, 
since commit for 'Cut \x00 ' i got malformed packet if i try to extract pcap for specific callflows that normally contains \x00 somewhere in ISUP.

I attached a compare of wireshark view.

![image 542](https://user-images.githubusercontent.com/20556929/53818539-827eaf80-3f68-11e9-9fb3-34dc604956c4.png)

Do you think you could deal with this case and not delete \x00 in the body ?

Thanks for you time ;)

David

**Comment by negbie** [comment]
Hi David,
oh I did this mainly because of homer7 and postgres. You use homer5 right? Because for mysql I don't need to cut \x00

**Comment by negbie** [comment]
So I could do it only for postgres

**Comment by dvillaume** [comment]
You're right

**Comment by dvillaume** [comment]
I'm using docker version, if you do any commit :)

**Comment by negbie** [comment]
Ok with latest commit I cut \x00 only when you use postgres. But nevertheless I need to think about this more deeply because this would mean postgres users could have your issue too.
