### ISSUE TITLE
PostgreSQL database "root", "homer_data" and "homer_config" creation issue.

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/heplify-server#221]
Hello,

I am setting the heplify-server, homer-app and postgreSQL via kubectl.
These service run well on the kubernetes clusters.
But when check the postgreSQL, there is no "root", "homer_data" and "homer_config" database.
Only postgres, postgresdb, template0 and template1 databases are created.

heplify-server docker log shows "rotator.go:66: ERR pq: database "root" does not exist".
Could you please give some suggestion to this setup?
Thanks a lot!

**Comment by negbie** [comment]
Hi @TaurusXY. Was on vacation so here is the delayed answer. It seems you have an error in your config. A root database won't be created so I guess you mixed some config fields.

**Comment by TaurusXY** [comment]
Thanks negbie, I make some changes on the access and bypass this issue now.

**Comment by negbie** [comment]
Thanks for the info. So I guess I can close it.
