### ISSUE TITLE
please check PostgreSQL version at startup

### ISSUE THREAD

**Issue by dpocock** [sipcapture/heplify-server#222]
It would be very easy and very useful to check the PostgreSQL version at startup, logging the version and refuse to run if it is < 10.x

Many Linux distributions include older versions (e.g. 9.6.x in Debian stretch) and some people may inadvertently use the wrong version.  It is also possible for people to have multiple versions installed concurrently (the Debian/Ubuntu packages are designed this way) and the user may inadvertently connect to an older version if they don't explicitly configure the port number for the new version.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/f429e84bc93fae38aab988b875da8bdf20ad63fe
