### ISSUE TITLE
stop if database initialization / DDL fails

### ISSUE THREAD

**Issue by dpocock** [sipcapture/heplify-server#223]
I notice that if DDL commands fail, e.g. because of an older PostgreSQL version, the heplify-server process keeps running.  It may be a good idea for the process to log an error and completely abort whenever DDL commands fail.

**Comment by lmangani** [comment]
@dpocock mind `HEPlify-server` can and does use multiple backends. A single db failure might not prevent other inserts from proceeding or completing as intended. Perhaps we could think of more explicit error logs if @negbie find this necessary

**Comment by negbie** [comment]
@lmangani is on point! heplify-server is designed to work with multiple backends with strong focus on metrics. These days metrics have to most value because you send alerts based on them so they shouldn't be affected only when something happens with the database.
