### ISSUE TITLE
"SIP method - q850 reason" pair statistics

### ISSUE THREAD

**Issue by kpribic** [sipcapture/heplify-server#231]
Current implementation of heplify-server generates aggregate statistics for q850 reasons per promtarget. However there are cases where it's important which SIP message does the Reason header come in (specifically provisional messages). This is a potential performance issue due to cardinality so parameter probably should be made configurable.

**Example where this would be useful**: There are telecoms that play early media announcements upon call failure using 183 messages, and those 183 messages contain correct Reason header relating to the content of the announcement. Information contained in final response to Invite contains different Reason header and that one is often not useful (could be that it relates to the deliver of early media announcement or it's just generic). 
Different scenario is when A side hangs up first (via CANCEL) and then we don't get any sensible Reason header in final response at all. 

Some real world combinations:
Double Reason header, and the 480 one is useless:
```
183 provisional --> Reason: Q.850;cause=18;text="No user responding",SIP;cause=408
480 final response --> Reason: Q.850;cause=31;text="Normal, unspecified",SIP;cause=480
```
Double Reason header, and the 480 one is useless:
```
183 provisional --> Reason: Q.850;cause=34;text="No circuit/channel available",SIP;cause=503
480 final response --> Reason: Q.850;cause=31;text="Normal, unspecified",SIP;cause=480
```
Double Reason header, and the 480 one is useless:
```
183 provisional --> Reason: Q.850;cause=17;text="User busy",SIP;cause=486
480 final response --> Reason: Q.850;cause=31;text="Normal, unspecified",SIP;cause=480
```
This one would be reported correctly, but it would still be interesting to know that it came in provisional message (meaning an resource consuming announcement was played as opposed to terminating call immediately):
```
SIP 183 --> Reason: Q.850;cause=34;text="No circuit/channel available",SIP;cause=503
SIP 487 --> without reason header (A side canceled)
```

**Comment by negbie** [comment]
I could try to reduce cardinality by only using src ip's as target. For example with this setup:
http://www.dialogic.com/webhelp/bordernet2020/1.1.0/webhelp/CF_SIP_ReasonHead_cause17_486.pngPromTargetIP    = "1.1.1.1, 2.2.2.2"
PromTargetName  = "SIP, IMG"

You will only get a metric for target_name="IMG", method="486", cause="17". Cardinality could still become high because you can have a reason header in
BYE
CANCEL
4xx, 5xx, and 6xx messages.

But we can try this and make it optional when cardinality becomes an issue.

**Comment by negbie** [comment]
Ok I made some changes and hope they will fit your need. I need to make some tests before I decide to make a flag for this.

**Comment by negbie** [comment]
@kpribic Could you test it already. In our enviroment the series cardinality is "Total time series: 3185" which is quite high but hey hardware is cheap :D So if it works ok for you I will keep it this way and close this issue.

**Comment by kpribic** [comment]
It's not that easy to get production traffic with new heplify-server for me :-).
I plan to test the new version tomorrow and then we'll what it looks like.

**Comment by kpribic** [comment]
Sorry, I'm having some network issues here trying to get production traffic messages to the new VM, promise to confirm tomorrow...

**Comment by negbie** [comment]
Hehe ok. Take your time. You could also just put heplify client into the prod machine and just forward a bit of traffic to every host you like.

**Comment by kpribic** [comment]
Tried it with production traffic, works great. You can close the issue :-)
My specific HOMER instance doesn't even have that big cardinality, about 2500 at the moment.

Currently I'm using captagent because it's configurable but in the end we didn't configure anything smart there. How do you forward to multiple heplify-server instances using heplify client? Multiple "-hs" parameters?

**Comment by negbie** [comment]
Glad it works for you! I wrote a simple proxy some time ago but it's unfinished. In heplify client you cant use multiple hs flags. But when I want to test some new things out I simple run another heplify process to a heplify-server in the lab.

**Comment by negbie** [comment]
@kpribic Since it's working fine for you I will close this issue now. Feel free to open a new one when you think something should be improved, a feature, documentation you name it ;)
