### ISSUE TITLE
VQ-RTCP-XR Metrics

### ISSUE THREAD

**Issue by PDGIII** [sipcapture/heplify-server#245]
Not sure if this is the proper place to ask, but how would one go about importing [metrics](https://github.com/sipcapture/heplify-server/tree/master/metric) into Prometheus within the hep-prom-graf stack? When go to http://<myip>:9090/metrics, I don't see any metrics for vqrtcpxr:

[metrics.txt](https://github.com/sipcapture/heplify-server/files/3225139/metrics.txt)

I'm currently using the following flow: 

`Phone --> heplify-xrcollector --> heplify-server --> Prometheus --> Grafana`

And hepify-server is receiving data from heplify-xrcollector:

> heplify-server    | Event: vq-rtcpxr
>heplify-server    | User-Agent: PolycomVVX-VVX_250-UA/5.9.1.0615
>heplify-server    | Accept-Language: en
>heplify-server    | Max-Forwards: 70
>heplify-server    | Expires: 900
>heplify-server    | Content-Type: application/vq-rtcpxr
>heplify-server    | Content-Length: 700

I believe once I'm able to import those metrics, I should be able to query the vqrtcpxr data. 

Thanks!

**Comment by negbie** [comment]
@PDGIII Prometheus itself exposes metrics under http://:9090/metrics and scrapes them. heplify-server exposes its metric under :9069/metrics

Could you please check what metrics you have under :9069/metrics

**Comment by PDGIII** [comment]
Sorry for the late response. 

I can't hit :9069/metrics and don't see any mention of it when I turn the docker container up. Here is the output when heplify-server starts: 

`heplify-server    | Could not find toml config file, use flag defaults. <nil>
heplify-server    | 2019/05/30 19:55:55.226420 server.go:93: INFO start heplify-server 1.09 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"''", ESDiscovery:true, ESUser:"", ESPass:"", MQDriver:"", MQAddr:"", MQTopic:"", LokiURL:"", LokiBulk:200, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 100}, PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer5", DBDriver:"mysql", DBAddr:"''", DBUser:"root", DBPass:"", DBDataTable:"homer_data", DBConfTable:"homer_configuration", DBTableSpace:"", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:14, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), FilterHost:[]string(nil), AlegIDs:[]string(nil), LogDbg:"", LogLvl:"debug", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", GCBallast:0}
heplify-server    | 2019/05/30 19:55:55.227000 prometheus.go:33: INFO expose metrics without or unbalanced targets`

Should I try setting up the heplify-server binary manually instead of messing with the hep-prom-graf stack?

**Comment by negbie** [comment]
Ups typo ;) It's :9096/metrics 
In the config its the value of PromAddr. The stack is fine and will save you some time + will give you some dashboards in grafana out of the box.

**Comment by PDGIII** [comment]
Figured it was a typo :).

I also tried hitting :9096/metrics but get no response. I'm wondering if isn't listening like it's supposed to (not sure if nmap is the proper test).

Port 9060 vs 9096:

--------------------------------------------
# nmap -p9060 127.0.0.1

PORT     STATE SERVICE
9060/tcp open  CardWeb-IO
--------------------------------------------
# nmap -sU -p9060 127.0.0.1

PORT     STATE         SERVICE
9060/udp open|filtered unknown
--------------------------------------------
# nmap -p9096 127.0.0.1

PORT     STATE  SERVICE
9096/tcp closed unknown
--------------------------------------------
# nmap -sU -p9096 127.0.0.1

PORT     STATE  SERVICE
9096/udp closed unknown
--------------------------------------------

**Comment by negbie** [comment]
Ah thats because that port is not exposed in the docker-compose.yml file. You can login into prometheus ui under :9090 and look up all the metrics you have.

**Comment by negbie** [comment]
Sorry but It's quite some time ago since I last time used the docker stack so I need to lookup some things myself ;)

**Comment by PDGIII** [comment]
No worries, I really appreciate your responsiveness and assistance. 

So I posted the [metrics.txt](https://github.com/sipcapture/heplify-server/files/3241408/metrics.txt) from :9090/metrics in my initial post and don't see anything for vqrtcpxr. I'm wondering how I could add the VQ-RTCP-XR metrics you came up with to capture what I'm looking for.

**Comment by negbie** [comment]
Prometheus has a simple webinterface. Could you please login under localhost:9090 (or your ip) with user/pw admin/admin? localhost:9090/metrics is not that interesting for that moment.

**Comment by PDGIII** [comment]
Sure. When I log into the web interface, these are the only heplify metrics I see: 

![image](https://user-images.githubusercontent.com/33589351/58710643-c841ed00-838a-11e9-8b4b-95d8ce6367d2.png)

**Comment by negbie** [comment]
Ah perfect. Hmm this seems like heplify-server isn't exposing any vq-rtcpxr metrics. You should see metrics like heplify_vqrtcpxr_nlr. Could you set inside the heplify-server config the LogLvl to debug and make some testcalls?

**Comment by PDGIII** [comment]
Will do.

**Comment by PDGIII** [comment]
This is going to sound dumb, but I was able to get everything working by changing the listening port on heplify-xrcollector to 5060 instead of 9064. Collected data: 

![image](https://user-images.githubusercontent.com/33589351/58767060-4c939c00-8554-11e9-8119-78df59217de6.png)

My next task will be creating creating more panels and seeing how I can query the collected data by endpoint.

Thanks for your help and all of your hard work!

**Comment by negbie** [comment]
Nice! Just open a new issue when you need help or more metrics.

**Comment by negbie** [comment]
@PDGIII Maybe some phones have troubles with that port? But I don't know it exactly. I released a new version which will listen on port 5060 as default. Thank you for this information.
