### ISSUE TITLE
What's the mechanism of heplify-server clear database ?

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/heplify-server#246]
Hello,

We are using PostgreSQL as the database of HOMER7. 
From the config.go, we can see the default DBDropDay is 14 days.
Is there any possibility to drop the tables due to some disk usage or other condition besides of the time limitation?

Thanks,
TaurusXY

**Comment by negbie** [comment]
Hi,
only time based rotation is supported and right now I have no plans to support something else. You can define different rotation days for
Call, Register and Default SIP tables with
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0

If you set one of these to > 0 it will overwrite DBDropDays value for that particular table.
