### ISSUE TITLE
hepsub mapping schema error

### ISSUE THREAD

**Issue by Demon-DK** [sipcapture/heplify-server#251]
I'm using default deploy of following stack docker images:
- image: sipcapture/heplify:master
- image: sipcapture/heplify-server:master
- image: sipcapture/homer-app:master
- image: postgres:10-alpine 

In the postgreSQL log I'm constantly observe the following error which is caused by heplify-server calls:
```
[198] ERROR:  relation "hepsub_mapping_schema" does not exist at character 23
[198] STATEMENT:  select "mapping" from "hepsub_mapping_schema" where "hepid" = $1 and "profile" = $2
```

What is this mapping schema ?
How to resolve this error ?

**Comment by negbie** [comment]
Hi @Demon-DK,
this has nothing to do with heplify-server. Please open this issue under homer-app or hepsub repo. Thanks!

**Comment by Demon-DK** [comment]
> 
> 
> Hi @Demon-DK,
> this has nothing to do with heplify-server. Please open this issue under homer-app or hepsub repo. Thanks!

Hi, thanks, its done.
