### ISSUE TITLE
Questions about HOMER7 capacity testing

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/heplify-server#252]
Hi，

Have you ever did some capacity testing on HOMER7? What's the maximum of call load can Heplify-server support?

We are aimed to get HOMER7's capacity by sending SIP message to HOMER7 with 60cps and 120cps.
However, it's strange that after several time, Heplify-server can not insert the message data into the PostgreSQL. 
We suspect there's something wrong with DB channel after writing/reading data for a period of time . 
Have you ever met this kind of issue? could you please give some help on how to debug and  continue?
Thanks so much!

**Comment by negbie** [comment]
Yes I did some tests on h7 with hammerhep https://twitter.com/negbie/status/1093203426803179521
I've made no tests with production traffic for homer7 because I still use homer 5 but I don't think that heplify-server sets the limits. It's always the configuration of the database and os.

**Comment by negbie** [comment]
Make sure you have a decent postgres configuration. As a good starting point I can recommend you this online configurator:
http://pgconfigurator.cybertec.at/

For everything else I need to know more about your hardware. CPU, RAM, Max IO, Os settings like scheduler, sysctl.conf, fstab, numactl and many more.

**Comment by TaurusXY** [comment]
Thanks negbie for your quick response! 
I use kubectl to set up the PostgreSQL . Below is the configuration for it.
`kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: postgresql
    version: v1.22
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  name: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:10-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
            hostPort: 5432
            protocol: TCP
        envFrom:
          - configMapRef:
              name: homerenv-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: root
      volumes:
        - name: root
          persistentVolumeClaim:
            claimName: postgres-pv-claim
status: {}
---
`

**Comment by negbie** [comment]
Its hard to do this right on kubernetes (high IO db applications). Sorry but since this would require a lot of time on my side to assist you I would recommend you to google a bit or just move only your database to a separate machine.

**Comment by negbie** [comment]
@TaurusXY I close this here because it's not really heplify-server related and more how to configure kubernetes properly for a db which needs to handle lots of io.
