### ISSUE TITLE
About DBBuffer and Input channel buffer

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/heplify-server#253]
Hi,

When we are doing capacity testing, there are some packets lost.
I found the value of DBBuffer  is set as 400000 in the heplify-server.toml,
and the inputCh buffer is set as 40000 when create the input channel.
Per our current understanding, it is caused by the different throughput of these two buffers.

Could you please give some explanation about the reason why it is set up this way?

**Comment by negbie** [comment]
inputCh is to buffer packets from network which has low delay so you don't need such a high buffer like DBBuffer. Most likely the lost packets are got lost inside the network.

**Comment by negbie** [comment]
Keep in mind buffers won't help you with wrong configured kubernetes cluster or when your hardware cannot provide enough IO.
