### ISSUE TITLE
How to increase the amount of TCP connection between DB and Heplify-server?

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/heplify-server#254]
Hi,

We notice that, currently there are 8 TCP connections between Heplify-server and DB,
Could you please help indicate how to increase the number of the TCP connection?

![image](https://user-images.githubusercontent.com/49503708/59996051-ca4a5380-968b-11e9-8168-2ff730a87a73.png)

**Comment by negbie** [comment]
Every DBWorker will open it's own connection. So set DBWorker higher. Keep in mind that I will limit this to the amount of CPU's you have.

**Comment by TaurusXY** [comment]
That is to say, if the number of DBWorker > CPU core, the number of TCP connection is equal to the number of DBWorker; otherwise, the number of TCP connection is equal to the number of CPU cores. right?

**Comment by negbie** [comment]
if worker > runtime.NumCPU() {
		worker = runtime.NumCPU()
	}

**Comment by negbie** [comment]
Every worker 1 tcp connection. Max is your CPU count.

**Comment by TaurusXY** [comment]
Ok, it's clear, Thanks so much, negbie!
