### ISSUE TITLE
Better way to map PROMTARGETIP to PROMTARGETNAME/Service discovery?

### ISSUE THREAD

**Issue by PNRxA** [sipcapture/heplify-server#255]
Currently I run heplify-server in a docker container.

My config has the following flags set up with 40+ VoIP servers for example:

```
- "HEPLIFYSERVER_PROMTARGETIP=1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,..."
- "HEPLIFYSERVER_PROMTARGETNAME=name1,name2,name3,name4,..."
```

We launch new VoIP servers often so every night using a cron job I run a script which updates those flags in my docker-compose file with the latest IPs and Names pulled from AWS CLI and then runs `docker-compose up -d` to update heplify-server with the new values.

There is no problem here as it all works fine but is this the best way to accomplish this?
Is there a better way of mapping IP addresses to names dynamically or is this typically done manually?

**Comment by negbie** [comment]
Hi, yes a better way would be to create a new flag like PromTargetMap and use a map like notation 
{ a = "foo" , b = "bar" } 
or 
a:foo,b:bar

**Comment by negbie** [comment]
About the dynamically mapping I guess I would do something like this: Use dns names instead of IP's and create a go routine in heplify-server whichs does the ip resolution every x hours and puts them into the targets.

**Comment by lmangani** [comment]
@negbie if this is the approach, consider letting the DNS server(s) configurable so one can avoid resolving unwanted items and/or setup a dedicated DNS server for this purpose, vs. the OS DNS which might end up resolving more spammers than others.

**Comment by negbie** [comment]
Good point, I will keep it in mind. I was just thinking out loud about a possible solution to this. There are more elegant ways especially when you use aws or gcp but they are more complex. I will see when I find more time to look for other possible solutions to this.

**Comment by lmangani** [comment]
I guess a simple table in the db, or an optional sqlite file would also do, if we're trying to stay simple - we can brainstorm on slack if you'd like ;)

**Comment by changzx** [comment]
> Currently I run heplify-server in a docker container.
> 
> My config has the following flags set up with 40+ VoIP servers for example:
> 
> ```
> - "HEPLIFYSERVER_PROMTARGETIP=1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,..."
> - "HEPLIFYSERVER_PROMTARGETNAME=name1,name2,name3,name4,..."
> ```
> 
> We launch new VoIP servers often so every night using a cron job I run a script which updates those flags in my docker-compose file with the latest IPs and Names pulled from AWS CLI and then runs `docker-compose up -d` to update heplify-server with the new values.
> 
> There is no problem here as it all works fine but is this the best way to accomplish this?
> Is there a better way of mapping IP addresses to names dynamically or is this typically done manually?

 40+ VoIP servers?

**Comment by PNRxA** [comment]
> 40+ VoIP servers?

Yes, over 40 VoIP servers hosted on AWS EC2

**Comment by changzx** [comment]
> > 40+ VoIP servers?
> 
> Yes, over 40 VoIP servers hosted on AWS EC2

Concurrent?
Can you send me your email?

**Comment by lmangani** [comment]
@changzx @PNRxA right now advanced and realtime tagging options are only available in `hepic` but a new version of `homer` is in the works where we could perhaps address this more elegantly.

**Comment by PNRxA** [comment]
@lmangani that sounds great, looking forward to it. Are you referring to Homer 7.x or a newer version?

**Comment by changzx** [comment]
> @changzx @PNRxA right now advanced and realtime tagging options are only available in `hepic` but a new version of `homer` is in the works where we could perhaps address this more elegantly.

that sounds great!

**Comment by Zhenyuga** [comment]
I want to konw does this sovled this issue? if yes, where is the latest config map, or db

**Comment by izaacmenezes** [comment]
Good morning, do you have an update on the topic?

**Comment by lmangani** [comment]
@izaacmenezes there were no community contributions or sponsorship regarding this feature

**Comment by lmangani** [comment]
closing in favour of new methods/proposals

**Comment by 2naive** [comment]
@lmangani could you please tell - is it possible to just use all IPs as target_names?

The default build leaves you with empty target_name var in Grafana unless you manually set HEPLIFYSERVER_PROMTARGETIP and HEPLIFYSERVER_PROMTARGETNAME which (as for me) makes little sense: it's better to see at least IPs even if no "names" provided.

Thank you!
