### ISSUE TITLE
Loki config out of date

### ISSUE THREAD

**Issue by PNRxA** [sipcapture/heplify-server#261]
Current config produced 502 and label errors

https://github.com/sipcapture/heplify-server/blob/master/docker/hep-prom-loki-graf/loki/loki-local-config.yaml

New config example 

https://github.com/grafana/loki/blob/master/cmd/loki/loki-local-config.yaml

Working briefly on my setup I was able to get rid of the 502 error by using the new config but am still getting the label errors and unable to retrieve data from Loki in Grafana

The 502 was caused by this specifically https://github.com/grafana/loki/issues/607

**Comment by negbie** [comment]
Thanks for pointing this out. Yes this config is old. I would suggest you to look under https://github.com/sipcapture/homer7-docker for docker related stuff. The docker folder under this repo was more for testing in the early days. Will update the config here soon.

**Comment by PNRxA** [comment]
Ah yes, my bad. Should have posted in the other repository
