### ISSUE TITLE
Question about heplify-server loglevel configuration.

### ISSUE THREAD

**Issue by judyQD** [sipcapture/heplify-server#263]
Actually, this is a question about heplify-server's loglevel configuration. We use file: heplify-server.toml to do the configuration. For the part: 
LogDbg          = "hep,sql"
LogLvl          = "warning"
What's the real usage of these two line?
For my understanding, LogLvl is used to control the log level. If it was set to "warning", there should be no INFO log, only WARN & ERROR log would be print out.  Am I right?
But in my heplify-server's log, it has INFO log with configuration LogLvl          = "warning"
Could I get the answers? Thanks.

**Comment by negbie** [comment]
Hi,
LogDbg is only relevant when you set loglvl to debug. Since debug can generate a lot of messages you can for example just log debug messages related to hep by using LogDbg = "hep" 

Hmm ok seems to be a bug when you say you see INFO and have set LogLvl to warning.

**Comment by negbie** [comment]
Just tested with this config options:
 LogDbg = ""
 LogLvl = "warning"
 LogStd = false
 LogSys = false

and it works like it should. So I can't reproduce your issue. Try to leave LogDbg empty and use
 LogLvl = "debug"
when you need debug log level.
