### ISSUE TITLE
How to import monitoring indicators related to heplify-server sip into Prometheus

### ISSUE THREAD

**Issue by haozi4263** [sipcapture/heplify-server#264]
How to import monitoring indicators related to heplify-server sip into Prometheus?
Currently Prometheus has only heplify_kpi_xx monitoring data

**Comment by negbie** [comment]
No heplify_packets_size or heplify_packets_total?

**Comment by haozi4263** [comment]
Heplify starts with monitoring data.
https://github.com/sipcapture/heplify-server home page grafana no related data

**Comment by haozi4263** [comment]
Do you have a commercial version and an open source version

**Comment by lmangani** [comment]
@haozi4263 please email sales at qxip dot net
