### ISSUE TITLE
PromTargetIP and PromTargetName usecase

### ISSUE THREAD

**Issue by changzx** [sipcapture/heplify-server#267]
Dear:
   What are the functions of the following options? There are no comments in the code.
```
PromAddr              = ":9096"
PromTargetIP          = ""
PromTargetName        = ""
```
  Thank you!

**Comment by negbie** [comment]
heplify-server will expose it's metrics under PromAddr. You need to configure Prometheus to scrape metrics from that address.
PromTargetIP and PromTargetName depend on each other and are usefull when you need metrics for specific devices. For example:

PromTargetIP = "172.16.0.11, 172.16.0.22, 172.16.0.33 "
PromTargetName = "SBC, Kamailio, Asterisk"

Keep in mind that the position is important.
172.16.0.11 belongs to SBC
172.16.0.22 belongs to Kamailio
172.16.0.33 belongs to Asterisk

heplify-server will check src and dst IP of every packet against PromTargetIP list. If there is a match it will create a metric with the matching PromTargetName.

**Comment by changzx** [comment]
> heplify-server will expose it's metrics under PromAddr. You need to configure Prometheus to scrape metrics from that address.
> PromTargetIP and PromTargetName depend on each other and are usefull when you need metrics for specific devices. For example:
> 
> PromTargetIP = "172.16.0.11, 172.16.0.22, 172.16.0.33 "
> PromTargetName = "SBC, Kamailio, Asterisk"
> 
> Keep in mind that the position is important.
> 172.16.0.11 belongs to SBC
> 172.16.0.22 belongs to Kamailio
> 172.16.0.33 belongs to Asterisk
> 
> heplify-server will check src and dst IP of every packet against PromTargetIP list. If there is a match it will create a metric with the matching PromTargetName.

Can it be understood as distinguishing between different businesses?

**Comment by negbie** [comment]
It depends on how creative you are. But nothing stops you from using PromTargetName like customer1_sbc, customer9000_kamailio1337 and do the grouping in grafana.

**Comment by negbie** [comment]
Go and read about Grafana template variable, be clever and do the rest
https://grafana.com/docs/reference/templating
