### ISSUE TITLE
QoS RTCP/RTCP-XR Metrics

### ISSUE THREAD

**Issue by alexllobet** [sipcapture/heplify-server#279]
Hi everyone!

First and foremost, I apologize for any inconveniences posting this issue here, this is the first time I do it and I do not know exactly how to proceed.

I have recently installed Heplify Server + Prometheus + VictoriaMetrics + Grafana and I'm having problems with displaying QoS data, concretely RTCP and XRTP. This issue seems to be very related to issue #245, but in my case changing the port of RTCPXR (HEPlify-XRcollector) didn't work.

In Prometheus (localhost:9090) I see the following:
![Metrics](https://user-images.githubusercontent.com/26059063/68204104-92530580-ffc7-11e9-8490-67baf77967e2.png)

As you can see, only these metrics are available. But neither of these are RTCP-related. Indeed, in the following queries:

![RTP](https://user-images.githubusercontent.com/26059063/68204145-a5fe6c00-ffc7-11e9-81c1-e48b292c75aa.png)

and

![XRTP](https://user-images.githubusercontent.com/26059063/68204181-bc0c2c80-ffc7-11e9-9d6d-0f01efd4cc79.png)

the data cannot be displayed as the metrics seem not to be in Prometheus.
I also tried to look for **heplify_vqrtcpxr_moslq** instead of **heplify_xrtp_mos** but nothing happens...

Does anybody know why I am not able to see these RTC/XRTP Metrics? And on the other hand, RTCP metrics should be displayed even if I hand not the XRCollector right?

Thank you for any support and assistance!

**Comment by lmangani** [comment]
Hi @alexllobet 
The Victoriametrics support is experimental, so you need to deal with a few differences and Grafana presets won't work possibly. This said, the metrics depend on what's being fed to the system.

Are you positive RTCP-XR collections are generating inserts? Could you provide a few examples of the messages and reports you are sending in?

**Comment by alexllobet** [comment]
Hello @lmangani 
Thank you so much for you fast answer. Truth is I have had several problems with Victoriametrics... Would you recomend me to change de DB? If so, should I use InfluxDB?

I used tcpdump to capture the traffic destinated to 9060 and only received packets from the capture agent... not the RTCP-XR collector...  (I followed the guide https://github.com/negbie/heplify-xrcollector) I assume that the information is not being inserted....

Then I changed config of Heplify Capture Agent so as to send info to port 5060, "where" heplify-xrc is listening. Then heplify-xrc sends the info to 9060, "where" Heplify-Server is listening. With this schema I get no traffic at 9060.


![noTraffic](https://user-images.githubusercontent.com/26059063/68208813-507b8c80-ffd2-11e9-82f6-6a6a862da878.PNG)


I think I may have a concept confusion...

**Comment by lmangani** [comment]
You're doing it wrong :) All HEP agents must communicate with the HEP server.

* HEPlify (agent) should send traffic to HOMER on port 9060/udp
* HEPlify-Collector should send traffic to HOMER on port 9060/udp

I would proceed and sniff the `input` stage of HEPflify-Collector and see if you get any messages there to begin with.

**Comment by alexllobet** [comment]
Thank you for noticing my mistake!  

Sorry for my ignorance, I have assumed that the heplify xrcollector must be installed on the client (the sip proxy which recevies the call) and then send the information to the monitoring server (where the heplify-server is installed). That's right, isn't it?

Nevertheless, the port 5060 is being used by Kamailio:

![port_used](https://user-images.githubusercontent.com/26059063/68211514-0a292c00-ffd8-11e9-89ac-4a647ee77066.PNG)

So I changed to port 9064 but no traffic was found:
![noTrraffic_in_new_port](https://user-images.githubusercontent.com/26059063/68212194-54f77380-ffd9-11e9-9c2b-b9bae2bbbaf3.PNG)

Any thoughts of how can the collector send the data to the HEP-Server?

**Comment by lmangani** [comment]
No problem! Try to follow me here.

HEPlify-Collector is a collector - this means its not sniffing (like HEPlify does) but rather listening for data sent to it intentionally. In order for this to work you need to assign an exclusive service port for it and then configure your SIP Phones to send RTCP-XR Vq reports to it - if they support so. 

If you're just after RTCP, HEPlify does that already when configured right, there's not need for companions unless you actually have Vq reports flying around.

I hope this helps! Closing as this is a non-issue but feel free to continue commenting if help is needed

**Comment by alexllobet** [comment]
OK thank you for closing the thread and the explanation, I understood it well. 
That it is just what I wanted initially: to see QoS metrics in Grafana. But as shown in the 3 pictures at the begging, the metrics in Prometheus just do not exist and therefore there is no plot in Grafana.

 Might be because of the Database used?
