### ISSUE TITLE
Tables partitioned incorrectly

### ISSUE THREAD

**Issue by nevian427** [sipcapture/heplify-server#28]
Hi,

Table rotations done by heplify-server sets incorrect time(local timezone?), e.g.
p20180404_pnr0 1522789200 (Tue, 03 Apr 2018 21:00:00 GMT)
must be 1522886400 (Thu, 05 Apr 2018 00:00:00 GMT)

And on day 2018-04-04 it can't write as 
 driver error (1526): Table has no partition for value 1522886218

**Comment by negbie** [comment]
Hi,
will look into it.

**Comment by negbie** [comment]
Changed to UTC for rotation
https://github.com/sipcapture/heplify-server/commit/dc607a0f6dd63367621f19a13c8452265381da9b

Could you please test it with -loglvl debug

**Comment by nevian427** [comment]
Hi,
Nothing changed
p20180412_pnr0 1523480400

**Comment by negbie** [comment]
Please give -loglvl debug output from at least one whole table partition

**Comment by nevian427** [comment]
2018-04-10T12:51:43+03:00 DBG  [rotator] db query:
CREATE TABLE IF NOT EXISTS `logs_capture_all_20180410` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`micro_ts` bigint(18) NOT NULL DEFAULT '0',
`correlation_id` varchar(256) NOT NULL DEFAULT '',
`source_ip` varchar(60) NOT NULL DEFAULT '',
`source_port` int(10) NOT NULL DEFAULT 0,
`destination_ip` varchar(60) NOT NULL DEFAULT '',
`destination_port` int(10) NOT NULL DEFAULT 0,
`proto` int(5) NOT NULL DEFAULT 0,
`family` int(1) DEFAULT NULL,
`type` int(5) NOT NULL DEFAULT 0,
`node` varchar(125) NOT NULL DEFAULT '',
`msg` varchar(1500) NOT NULL DEFAULT '',
PRIMARY KEY (`id`,`date`),
KEY `date` (`date`),
KEY `correlationid` (`correlation_id`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`) ) (
PARTITION p20180410_pnr0 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-04-10 00:00:00') )
);

2018-04-10T12:51:43+03:00 DBG  [rotator] db query:
ALTER TABLE logs_capture_all_20180410 ADD PARTITION (PARTITION p20180410_pnr0 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-04-10 00:00:00') ));

**Comment by negbie** [comment]
Well from this output I see nothing strange. The table name suffix is from today 20180410
The first partition is for this day at midnight 
PARTITION p20180410_pnr0 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-04-10 00:00:00') )

So far all good. So I need more lines!

**Comment by nevian427** [comment]
IMO there should be next day, isn't it?  And why result again timezone affected?
Which do lines you need?

**Comment by negbie** [comment]
If you look more closely you will find the next day too.
Again you provide no debug logs where I see something strange in the timezone.

**Comment by nevian427** [comment]
I mean for day 10 apr we should have
PARTITION p20180410_pnr0 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-04-**11** 00:00:00') )


Old good homer_mysql_rotate.pl created like this

create data table: CREATE TABLE IF NOT EXISTS `webrtc_capture_all_20180410` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  `micro_ts` bigint(18) NOT NULL DEFAULT '0',
  `method` varchar(100) NOT NULL DEFAULT '',
  `caller` varchar(250) NOT NULL DEFAULT '',
  `callee` varchar(250) NOT NULL DEFAULT '',
  `session_id` varchar(256) NOT NULL DEFAULT '',
  `correlation_id` varchar(256) NOT NULL DEFAULT '',
  `source_ip` varchar(60) NOT NULL DEFAULT '',
  `source_port` int(10) NOT NULL DEFAULT 0,
  `destination_ip` varchar(60) NOT NULL DEFAULT '',
  `destination_port` int(10) NOT NULL DEFAULT 0,
  `proto` int(5) NOT NULL DEFAULT 0,
  `family` int(1) DEFAULT NULL,
  `type` int(5) NOT NULL DEFAULT 0,
  `node` varchar(125) NOT NULL DEFAULT '',
  `msg` varchar(3000) NOT NULL DEFAULT '',    
  PRIMARY KEY (`id`,`date`),
  KEY `date` (`date`),
  KEY `sessionid` (`session_id`),
  KEY `correlationid` (`correlation_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='20180410'
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
(PARTITION p2018041000 VALUES LESS THAN (1523404800),
PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */ ;

**Comment by negbie** [comment]
When you start heplify-server with enabled rotation it will call once
createTables()
https://github.com/sipcapture/heplify-server/blob/master/database/rotator.go#L216

So for example when you start heplify-server today(20180410) createTables() will create
20180410
20180411

When createTables() has finished a cronjob will be created which will execute every night at 03:15
r.CreateDataTables(1)
r.CreateDataTables(2)

So on 20180411 at 03:15 a table 20180412 and 20180413 will be created.

**Comment by nevian427** [comment]
I see..
Partition should end on NEXT midnight so for 10 apr we have to break at 00:00 11 apr

**Comment by negbie** [comment]
When you look more closely you will see I create PARTITION pmax too so this will handle it.

**Comment by games130** [comment]
The rotator seems to create the partition value late by 1 hour. 
p20180420_pnr0 should be recording time less than 0100h
p20180420_pnr1 should be recording time less than 0200h

but from the created partition, it is doing 
p20180420_pnr0 should be recording time less than 0000h 
p20180420_pnr1 should be recording time less than 0100h



Also, Just wondering this partition is created for homer5 or homer7? From what i understand homer5 store everything based on UTC time.. but the rotation is stored based on my server time which is GMT+8.

So the sql command send by HOMER5 would have problem finding some of the calls during specific time. like 19-04-2018 0AM-2AM GMT+8 as it would be trying to find in the file sip_capture_call_20180418 because of the UTC date. 

This is the partition created by the rotator:

> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
> /*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
> (PARTITION p20180420_pnr0 VALUES LESS THAN (1524153600) ENGINE = InnoDB,
>  PARTITION p20180420_pnr1 VALUES LESS THAN (1524157200) ENGINE = InnoDB,
>  PARTITION p20180420_pnr2 VALUES LESS THAN (1524160800) ENGINE = InnoDB,
>  PARTITION p20180420_pnr3 VALUES LESS THAN (1524164400) ENGINE = InnoDB,
>  PARTITION p20180420_pnr4 VALUES LESS THAN (1524168000) ENGINE = InnoDB,
>  PARTITION p20180420_pnr5 VALUES LESS THAN (1524171600) ENGINE = InnoDB,
>  PARTITION p20180420_pnr6 VALUES LESS THAN (1524175200) ENGINE = InnoDB,
>  PARTITION p20180420_pnr7 VALUES LESS THAN (1524178800) ENGINE = InnoDB,
>  PARTITION p20180420_pnr8 VALUES LESS THAN (1524182400) ENGINE = InnoDB,
>  PARTITION p20180420_pnr9 VALUES LESS THAN (1524186000) ENGINE = InnoDB,
>  PARTITION p20180420_pnr10 VALUES LESS THAN (1524189600) ENGINE = InnoDB,
>  PARTITION p20180420_pnr11 VALUES LESS THAN (1524193200) ENGINE = InnoDB,
>  PARTITION p20180420_pnr12 VALUES LESS THAN (1524196800) ENGINE = InnoDB,
>  PARTITION p20180420_pnr13 VALUES LESS THAN (1524200400) ENGINE = InnoDB,
>  PARTITION p20180420_pnr14 VALUES LESS THAN (1524204000) ENGINE = InnoDB,
>  PARTITION p20180420_pnr15 VALUES LESS THAN (1524207600) ENGINE = InnoDB,
>  PARTITION p20180420_pnr16 VALUES LESS THAN (1524211200) ENGINE = InnoDB,
>  PARTITION p20180420_pnr17 VALUES LESS THAN (1524214800) ENGINE = InnoDB,
>  PARTITION p20180420_pnr18 VALUES LESS THAN (1524218400) ENGINE = InnoDB,
>  PARTITION p20180420_pnr19 VALUES LESS THAN (1524222000) ENGINE = InnoDB,
>  PARTITION p20180420_pnr20 VALUES LESS THAN (1524225600) ENGINE = InnoDB,
>  PARTITION p20180420_pnr21 VALUES LESS THAN (1524229200) ENGINE = InnoDB,
>  PARTITION p20180420_pnr22 VALUES LESS THAN (1524232800) ENGINE = InnoDB,
>  PARTITION p20180420_pnr23 VALUES LESS THAN (1524236400) ENGINE = InnoDB,
>

**Comment by games130** [comment]
This is rotation done by homer5 rotation script

> ) ENGINE=InnoDB AUTO_INCREMENT=13060828 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8 COMMENT='20180417'
> /*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
> (PARTITION p2018041700 VALUES LESS THAN (1523926800) ENGINE = InnoDB,
>  PARTITION p2018041701 VALUES LESS THAN (1523930400) ENGINE = InnoDB,
>  PARTITION p2018041702 VALUES LESS THAN (1523934000) ENGINE = InnoDB,
>  PARTITION p2018041703 VALUES LESS THAN (1523937600) ENGINE = InnoDB,
>  PARTITION p2018041704 VALUES LESS THAN (1523941200) ENGINE = InnoDB,
>  PARTITION p2018041705 VALUES LESS THAN (1523944800) ENGINE = InnoDB,
>  PARTITION p2018041706 VALUES LESS THAN (1523948400) ENGINE = InnoDB,
>  PARTITION p2018041707 VALUES LESS THAN (1523952000) ENGINE = InnoDB,
>  PARTITION p2018041708 VALUES LESS THAN (1523955600) ENGINE = InnoDB,
>  PARTITION p2018041709 VALUES LESS THAN (1523959200) ENGINE = InnoDB,
>  PARTITION p2018041710 VALUES LESS THAN (1523962800) ENGINE = InnoDB,
>  PARTITION p2018041711 VALUES LESS THAN (1523966400) ENGINE = InnoDB,
>  PARTITION p2018041712 VALUES LESS THAN (1523970000) ENGINE = InnoDB,
>  PARTITION p2018041713 VALUES LESS THAN (1523973600) ENGINE = InnoDB,
>  PARTITION p2018041714 VALUES LESS THAN (1523977200) ENGINE = InnoDB,
>  PARTITION p2018041715 VALUES LESS THAN (1523980800) ENGINE = InnoDB,
>  PARTITION p2018041716 VALUES LESS THAN (1523984400) ENGINE = InnoDB,
>  PARTITION p2018041717 VALUES LESS THAN (1523988000) ENGINE = InnoDB,
>  PARTITION p2018041718 VALUES LESS THAN (1523991600) ENGINE = InnoDB,
>  PARTITION p2018041719 VALUES LESS THAN (1523995200) ENGINE = InnoDB,
>  PARTITION p2018041720 VALUES LESS THAN (1523998800) ENGINE = InnoDB,
>  PARTITION p2018041721 VALUES LESS THAN (1524002400) ENGINE = InnoDB,

**Comment by games130** [comment]
I tried to improve on the rotation script, please do help check #37

**Comment by negbie** [comment]
@nevian427 @games130 could you please test with latest master?

**Comment by games130** [comment]
@negbie If compared with the original homer, it is still not working well. I tested with the latest source.

Problems:
1. My heplify-server.toml was set to 1h partition, but it created the new data with 2h partition
2. Value is also not correct, 
 - 20180426_pnr0 should be VALUES LESS THAN (1524708000)
 - 20180426_pnr1 should be VALUES LESS THAN (1524715200)

I will update you again tomorrow to see how the rotation goes.

This is the result(same with the other tables):
> /*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
> (PARTITION 20180426_pnr0 VALUES LESS THAN (1524700800) ENGINE = InnoDB,
>  PARTITION 20180426_pnr1 VALUES LESS THAN (1524708000) ENGINE = InnoDB,
>  PARTITION 20180426_pnr2 VALUES LESS THAN (1524715200) ENGINE = InnoDB,
>  PARTITION 20180426_pnr3 VALUES LESS THAN (1524722400) ENGINE = InnoDB,
>  PARTITION 20180426_pnr4 VALUES LESS THAN (1524729600) ENGINE = InnoDB,
>  PARTITION 20180426_pnr5 VALUES LESS THAN (1524736800) ENGINE = InnoDB,
>  PARTITION 20180426_pnr6 VALUES LESS THAN (1524744000) ENGINE = InnoDB,
>  PARTITION 20180426_pnr7 VALUES LESS THAN (1524751200) ENGINE = InnoDB,
>  PARTITION 20180426_pnr8 VALUES LESS THAN (1524758400) ENGINE = InnoDB,
>  PARTITION 20180426_pnr9 VALUES LESS THAN (1524765600) ENGINE = InnoDB,
>  PARTITION 20180426_pnr10 VALUES LESS THAN (1524772800) ENGINE = InnoDB,
>  PARTITION 20180426_pnr11 VALUES LESS THAN (1524780000) ENGINE = InnoDB,
>  PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */ |
>

**Comment by games130** [comment]
oops my bad on the first problem. I did not notice the toml file format have changed, was using the old file format.
I tested with the new .toml file format and the 1h partition is working (for new create) but the timing is still wrong.

**Comment by negbie** [comment]
No problem. We need to discuss the timing. I still don't think its a problem with the first partition because the whole table is day based

**Comment by negbie** [comment]
I will spin up a container set the time to midnight and test it

**Comment by games130** [comment]
lets say the partition is 1h. My understanding is that:
pnr0 should store 00:00 - 01:00
pnr1 should store 01:00 - 02:00

Is that what you are trying to achieve as well?

**Comment by negbie** [comment]
What I do in mysql is

pnr0 less than 00:00
pnr1 less than 01:00

pnr0 is more or less a placeholder because less 00:00 would mean yesterday but since the table is based on daily timestamp it should go into the pmax partition from yesterday

**Comment by negbie** [comment]
For postgres I do exactly that what you describe but not for mysql

**Comment by negbie** [comment]
If you think I am wrong tell me ;)

**Comment by games130** [comment]
Yes, i do hope mysql can be same with what you have done for postgres.
well i am basing this on the original homer5 (with kamailio) script which generate the time that way.

**Comment by games130** [comment]
one more question, the time 1524700800 and 1524708000 is suppose to be my local time (in my timezone) or should be the UTC time

(PARTITION 20180426_pnr0 VALUES LESS THAN (1524700800) ENGINE = InnoDB,
PARTITION 20180426_pnr1 VALUES LESS THAN (1524708000) ENGINE = InnoDB,

**Comment by negbie** [comment]
This should be 00:00 utc time and +x localtime. Check it here:

https://www.unixtimestamp.com/index.php

**Comment by negbie** [comment]
I made some tests with following simple dataset on a 2h partitioned table:

INSERT INTO sip_capture_rest_20180426(date,micro_ts,method) VALUES ('2018-04-26 21:59:59.999999', 1524772799999999, '200');
INSERT INTO sip_capture_rest_20180426(date,micro_ts,method) VALUES ('2018-04-26 22:59:59.999999', 1524776399999999, '200');
INSERT INTO sip_capture_rest_20180426(date,micro_ts,method) VALUES ('2018-04-26 23:59:59.999999', 1524779999999999, '200');
INSERT INTO sip_capture_rest_20180427(date,micro_ts,method) VALUES ('2018-04-27 00:00:01.111111', 1524780001111111, '200');
INSERT INTO sip_capture_rest_20180427(date,micro_ts,method) VALUES ('2018-04-27 01:00:01.111111', 1524783601111111, '200');
INSERT INTO sip_capture_rest_20180427(date,micro_ts,method) VALUES ('2018-04-27 02:00:01.111111', 1524787201111111, '200');

Then I checked the partitions

SELECT table_rows as 'count(*)' FROM information_schema.partitions WHERE table_schema = schema() and table_name ='sip_capture_rest_20180426' and partition_name = '20180426_pnr11';
-------------------------------
count(*)
--
1

SELECT table_rows as 'count(*)' FROM information_schema.partitions WHERE table_schema = schema() and table_name ='sip_capture_rest_20180426' and partition_name = 'pmax';
-------------------------------
count(*)
--
2

SELECT table_rows as 'count(*)' FROM information_schema.partitions WHERE table_schema = schema() and table_name ='sip_capture_rest_20180427' and partition_name = '20180427_pnr0';
-------------------------------
count(*)
--
0

SELECT table_rows as 'count(*)' FROM information_schema.partitions WHERE table_schema = schema() and table_name ='sip_capture_rest_20180427' and partition_name = '20180427_pnr1';
-------------------------------
count(*)
--
2

SELECT table_rows as 'count(*)' FROM information_schema.partitions WHERE table_schema = schema() and table_name ='sip_capture_rest_20180427' and partition_name = '20180427_pnr2';
-------------------------------
count(*)
--
1

So as I said partition pnr0 won't be used and can be ignored. So there is nothing to do for me here.

**Comment by games130** [comment]
@negbie Need to double confirm again on the partition time hahahahaha.

for a server in UTC (GMT+0), the table created will be for that day (example today 20180427). the first pnr0 will be UTC 00:00-01:00

for a server in **GMT+8**, the first pnr0 will be **GMT+8** 00:00-01:00
 -- or should it be pnr0 UTC 00:00-01:00

**Comment by negbie** [comment]
It should be fine now. The important part is to use the right format (Format("2006-01-02 15:04:05-07:00"))

With that mysql will handle this for use. Otherwise it would assume its UTC.

Right now this is the pnr0 partition:

ALTER TABLE sip_capture_call_20180428 ADD PARTITION (PARTITION 20180428_pnr0 VALUES LESS THAN ( UNIX_TIMESTAMP('2018-04-28 00:00:00+02:00') ));

In unixtime 1524787200
Which is 27.04.2018 - 02:00:00 and the correct value for 2h base partition.

**Comment by games130** [comment]
Okay what I notice using homer5 GUI is this.

sip_capture_rest_20180427(date,micro_ts,method) VALUES ('2018-04-27 00:30:01.111111', 1524780001111111, '200');

After you insert this data, use the homer GUI search for "today". You will be able to find the data.

But if you search for time 2018-04-27 00:00 to 2018-04-27 01:00. You will not be able to find it.

**Comment by negbie** [comment]
Let me spin up the mysql container to test this.

**Comment by negbie** [comment]
Do you use a dedicated GUI and the latest heplify-server version or from the docker container?

**Comment by games130** [comment]
Homer webui and MySQL is docker (from your folders)

Heplify-server is the latest

**Comment by games130** [comment]
@negbie Are you getting the same result as i describe?

**Comment by negbie** [comment]
@games130 sorry couldn't test it yet because of some other stuff I am working on. Will give you feedback asap.

**Comment by negbie** [comment]
@games130 the only things I noticed are that the packr file needs to be updated and the wrong unixtimestamp in your example insert statement

INSERT INTO sip_capture_rest_20180427(date,micro_ts,method) VALUES ('2018-04-27 00:30:01.111111', 1524780001111111, '200');

please use 1524781801111111

Whith that I was able to find the 200 inside the timerange
2018-04-27 00:00 to 2018-04-27 01:00

**Comment by negbie** [comment]
Its best to test with real data. You can use heplify with the pcap from the example folder. Just run from the heplify folder:

./heplify -rf example/rtp_rtcp_sip.pcap

**Comment by games130** [comment]
oops mistake when modifying.. you found the data in mysql or found it from the homer WebUI search?

**Comment by negbie** [comment]
I build a new graf-homer-hep-prom cointainer and tested it with ./heplify -rf example/rtp_rtcp_sip.pcap

I checked the call table in db

1 | 2018-04-27 12:58:57 | 1524833937690554 | INVITE
-- | -- | -- | --

Keep in mind its UTC. In the GUI I used GMT+2 because its my localtime and was able to find that INVITE with the range

From 2018-04-27 14:55:00 to 2018-04-27 15:00:00, TZ GMT+2 EET

**Comment by games130** [comment]
please do correct me if i am wrong, my understanding is that (This is what i remember, i dont have access to my server now as i have gone back for the weekend):
1. The current heplify-server will create the tables and partition based on server timzone --> converted to UTC. So in my case GMT+8
```
table sip_capture_call_20180427 
pnr0 will be UNIX_TIMESTAMP('2018-04-27 01:00:00+08:00')
pnr1 will be UNIX_TIMESTAMP('2018-04-27 02:00:00+08:00')
pnr2 will be UNIX_TIMESTAMP('2018-04-27 03:00:00+08:00')
```

2. Homer WebUI will do the sql query after converting the time selected to UTC time. If i search for 
2017-04-27 00:00-02:00 GMT+8, After convert to UTC:
```
2017-04-27 00:00 GMT +8 = 2017-04-26 16:00 UTC
2017-04-27 02:00 GMT +8 = 2017-04-26 18:00 UTC
```
So because of the new UTC time, it will query to table sip_capture_call_20180426 date between 2017-04-26 16:00 and 2017-04-26 18:00

So actually the query has been send to the wrong table.

**Comment by games130** [comment]
It is strange in your database the time stored is UTC, how did that happen?
Based on the homer5.go the timestamp does not have any timezone information, so your mysql will stored based on mysql server timezone.

https://github.com/sipcapture/heplify-server/blob/01174edd961477e4397b534bd7492349c842b44a/database/sqlhomer5.go#L175

**Comment by negbie** [comment]
No when you provide no timezone information mysql will use UTC

**Comment by games130** [comment]
is that because the timezone in mysql docker is using UTC? 
coz i changed mine to GMT+8 :(

**Comment by negbie** [comment]
What I can suggest you is to change it back to 

ts = pkt.Timestamp.UTC().Format("2006-01-02 15:04:05.999999")

This should not break anything

**Comment by negbie** [comment]
Will need to check how postgres is handling this.

**Comment by games130** [comment]
could you help me check a few things on your server, so that first thing monday when i get back i can compare to what i have.

1. Your exact time when executing the below with timezone
2. After you have loaded latest live data, (i want to know what are the date and time you see here)
select date from sip_capture_call_20180427 order by date DESC limit 10;
3. show create table sip_capture_call_20180427 

Why i am asking this is because, i recall that when i did number 2, the result i get from date is the current time. I dont see the UTC time. 

thank you

**Comment by negbie** [comment]
MariaDB [homer_data]> select now();
+---------------------+
| now()               |
+---------------------+
| 2018-04-27 17:31:41 |
+---------------------+
1 row in set (0.00 sec)

insert will produce
id: 16493868
date: 2018-04-27 17:31:35
micro_ts: 1524843035285325

Sorry its not per default utc it depends on your db configuration. As you can see select now() is the same like the ntptime
ntptime 
Fri, Apr 27 2018 17:31:55.498, (.498500),

And the last partitions are:

 PARTITION `20180427_pnr140` VALUES LESS THAN (1524951000) ENGINE = InnoDB,
 PARTITION `20180427_pnr141` VALUES LESS THAN (1524951600) ENGINE = InnoDB,
 PARTITION `20180427_pnr142` VALUES LESS THAN (1524952200) ENGINE = InnoDB,
 PARTITION `20180427_pnr143` VALUES LESS THAN (1524952800) ENGINE = InnoDB,
 PARTITION `pmax` VALUES LESS THAN MAXVALUE ENGINE = InnoDB)

**Comment by negbie** [comment]
In the GUI you will see following under details:

id | 16493868
date | 2018-04-27 15:30:35
milli_ts | 1524843035285
micro_ts | 1524843035285325

**Comment by games130** [comment]
These are the result i am getting from the similiar command:

mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2018-04-30 09:35:07 |
+---------------------+

mysql> select date, micro_ts from sip_capture_call_20180430 order by date DESC limit 10;
+---------------------+------------------+
| date                | micro_ts         |
+---------------------+------------------+
| 2018-04-30 09:35:19 | 1525052118961388 |
| 2018-04-30 09:35:19 | 1525052118646384 |
| 2018-04-30 09:35:19 | 1525052118616030 |
| 2018-04-30 09:35:19 | 1525052118601044 |
| 2018-04-30 09:35:19 | 1525052118531641 |
| 2018-04-30 09:35:19 | 1525052118936143 |
| 2018-04-30 09:35:19 | 1525052118914296 |
| 2018-04-30 09:35:19 | 1525052118883468 |
| 2018-04-30 09:35:19 | 1525052118855164 |
| 2018-04-30 09:35:19 | 1525052118842800 |
+---------------------+------------------+


mysql> show create table sip_capture_call_20180430;
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
(PARTITION 20180430_pnr0 VALUES LESS THAN (1525021200) ENGINE = InnoDB,
 PARTITION 20180430_pnr1 VALUES LESS THAN (1525024800) ENGINE = InnoDB,
 PARTITION 20180430_pnr2 VALUES LESS THAN (1525028400) ENGINE = InnoDB,
 PARTITION 20180430_pnr3 VALUES LESS THAN (1525032000) ENGINE = InnoDB,
 PARTITION 20180430_pnr4 VALUES LESS THAN (1525035600) ENGINE = InnoDB,
 PARTITION 20180430_pnr5 VALUES LESS THAN (1525039200) ENGINE = InnoDB,
 PARTITION 20180430_pnr6 VALUES LESS THAN (1525042800) ENGINE = InnoDB,
 PARTITION 20180430_pnr7 VALUES LESS THAN (1525046400) ENGINE = InnoDB,
 PARTITION 20180430_pnr8 VALUES LESS THAN (1525050000) ENGINE = InnoDB,
 PARTITION 20180430_pnr9 VALUES LESS THAN (1525053600) ENGINE = InnoDB,
 PARTITION 20180430_pnr10 VALUES LESS THAN (1525057200) ENGINE = InnoDB,
 PARTITION 20180430_pnr11 VALUES LESS THAN (1525060800) ENGINE = InnoDB,
 PARTITION 20180430_pnr12 VALUES LESS THAN (1525064400) ENGINE = InnoDB,
..
 PARTITION 20180430_pnr22 VALUES LESS THAN (1525100400) ENGINE = InnoDB,
 PARTITION 20180430_pnr23 VALUES LESS THAN (1525104000) ENGINE = InnoDB,


mysql> SELECT PARTITION_NAME, table_rows FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_NAME='sip_capture_call_20180430' AND TABLE_SCHEMA='homer_data' ORDER BY PARTITION_DESCRIPTION ASC;
+----------------+------------+
| PARTITION_NAME | table_rows |
+----------------+------------+
| 20180430_pnr0  |      57110 |
| 20180430_pnr1  |      23211 |
| 20180430_pnr2  |      15632 |
| 20180430_pnr3  |      10760 |
| 20180430_pnr4  |      11603 |
| 20180430_pnr5  |      18103 |
| 20180430_pnr6  |      65045 |
| 20180430_pnr7  |     143889 |
| 20180430_pnr8  |     308296 |
| 20180430_pnr9  |     326126 |
| 20180430_pnr10 |          0 |
| 20180430_pnr11 |          0 |

**Comment by games130** [comment]
When i select on WebUI based on this time range:
![timerange](https://user-images.githubusercontent.com/32865575/39413528-1c479dce-4c5e-11e8-8180-c1f40ab8b05e.JPG)

This is the result i am getting:-
![searchresult1](https://user-images.githubusercontent.com/32865575/39413536-33369aa8-4c5e-11e8-89fc-209a683cbac6.JPG)

I check the mysql command log, the query executed was:

> 2018-04-30T01:58:21.776899Z     10756 Query     SET time_zone = "+00:00"
> 2018-04-30T01:58:21.777430Z     10756 Query     SELECT id, date, (micro_ts DIV 1000) as milli_ts, micro_ts,method,reply_reason,ruri,ruri_user,ruri_domain,from_user,from_domain,from_tag,
> to_user,to_domain,to_tag,pid_user,contact_user,auth_user,callid,callid_aleg,via_1,via_1_branch,cseq,diversion,reason,content_type,auth,
> user_agent,source_ip,source_port,destination_ip,destination_port,contact_ip,contact_port,originator_ip,originator_port,correlation_id,proto,family,rtp_stat,type,node,'call' as trans,'single' as dbnode FROM **sip_capture_call_20180430**  WHERE (date BETWEEN FROM_UNIXTIME(1525017600) AND FROM_UNIXTIME(1525103999)) AND ( method = 'INVITE') LIMIT 1000
> 



If i query 00:00 to 01:00
![timerange2](https://user-images.githubusercontent.com/32865575/39413540-63d7f42c-4c5e-11e8-98c0-41d867a3ad80.JPG)

I will get nothing:
![searchresult2](https://user-images.githubusercontent.com/32865575/39413544-6b66e612-4c5e-11e8-974a-5568ef0a292e.JPG)

Mysql query show that it is checking the wrong table:

> 2018-04-30T01:57:31.047590Z     10745 Query     SET time_zone = "+00:00"
> 2018-04-30T01:57:31.048154Z     10745 Query     SELECT id, date, (micro_ts DIV 1000) as milli_ts, micro_ts,method,reply_reason,ruri,ruri_user,ruri_domain,from_user,from_domain,from_tag,
> to_user,to_domain,to_tag,pid_user,contact_user,auth_user,callid,callid_aleg,via_1,via_1_branch,cseq,diversion,reason,content_type,auth,
> user_agent,source_ip,source_port,destination_ip,destination_port,contact_ip,contact_port,originator_ip,originator_port,correlation_id,proto,family,rtp_stat,type,node,'call' as trans,'single' as dbnode FROM **sip_capture_call_20180429**  WHERE (date BETWEEN FROM_UNIXTIME(1525017600) AND FROM_UNIXTIME(1525021200)) AND ( method = 'INVITE') LIMIT 1000

**Comment by games130** [comment]
I check on the rotation script done by the original. 
The tables are partition based on UTC timezone. I believe heplify-server rotation should produce similar partition

/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
(PARTITION p2018050100 VALUES LESS THAN (1525136400) ENGINE = InnoDB,
 PARTITION p2018050101 VALUES LESS THAN (1525140000) ENGINE = InnoDB,
 PARTITION p2018050102 VALUES LESS THAN (1525143600) ENGINE = InnoDB,
 PARTITION p2018050103 VALUES LESS THAN (1525147200) ENGINE = InnoDB,
 PARTITION p2018050104 VALUES LESS THAN (1525150800) ENGINE = InnoDB,
 PARTITION p2018050105 VALUES LESS THAN (1525154400) ENGINE = InnoDB,
 PARTITION p2018050106 VALUES LESS THAN (1525158000) ENGINE = InnoDB,
 PARTITION p2018050107 VALUES LESS THAN (1525161600) ENGINE = InnoDB,
 PARTITION p2018050108 VALUES LESS THAN (1525165200) ENGINE = InnoDB,
 PARTITION p2018050109 VALUES LESS THAN (1525168800) ENGINE = InnoDB,
 PARTITION p2018050110 VALUES LESS THAN (1525172400) ENGINE = InnoDB,
 PARTITION p2018050111 VALUES LESS THAN (1525176000) ENGINE = InnoDB,
 PARTITION p2018050112 VALUES LESS THAN (1525179600) ENGINE = InnoDB,
 PARTITION p2018050113 VALUES LESS THAN (1525183200) ENGINE = InnoDB,
 PARTITION p2018050114 VALUES LESS THAN (1525186800) ENGINE = InnoDB,
 PARTITION p2018050115 VALUES LESS THAN (1525190400) ENGINE = InnoDB,
 PARTITION p2018050116 VALUES LESS THAN (1525194000) ENGINE = InnoDB,
 PARTITION p2018050117 VALUES LESS THAN (1525197600) ENGINE = InnoDB,
 PARTITION p2018050118 VALUES LESS THAN (1525201200) ENGINE = InnoDB,
 PARTITION p2018050119 VALUES LESS THAN (1525204800) ENGINE = InnoDB,
 PARTITION p2018050120 VALUES LESS THAN (1525208400) ENGINE = InnoDB,
 PARTITION p2018050121 VALUES LESS THAN (1525212000) ENGINE = InnoDB,
 PARTITION p2018050122 VALUES LESS THAN (1525215600) ENGINE = InnoDB,
 PARTITION p2018050123 VALUES LESS THAN (1525219200) ENGINE = InnoDB,

**Comment by negbie** [comment]
Ok lets do this. If I will find some time today I will do the changes.

**Comment by negbie** [comment]
@games130 could you please test the latest commit. This should partition the tables based on utc time.

**Comment by games130** [comment]
@negbie i am now running the latest commit, table creation so far is ok. will update again tomorrow to see the result when it is executed by the cronjob.

**Comment by games130** [comment]
@negbie mysql table rotation looks good. thank you 👍

**Comment by negbie** [comment]
@games130 Thank you for the update. @games130 @nevian427 I will close it now. Feel free to reopen if you find something else.
