### ISSUE TITLE
Prometheus is not exposing all Heplify metrics

### ISSUE THREAD

**Issue by alexllobet** [sipcapture/heplify-server#280]
Hi all, 

I have been having some issues regarding the display of QoS values in grafana. Concretely I want it to show Jitter and Packet loss metrics. Grafana is currently plotting "No Data".
 (I'm using Heplify-server to ingest the capture agent data, Prometheus as time data series, Postrgres, VictoriaMetrics for storage Prometheus series and Grafana for visualising them.)

So I looked into Prometheus metrics and I saw the following:
![Metrics](https://user-images.githubusercontent.com/26059063/68787275-7c85b600-0641-11ea-9c89-def067700249.png)

As you can see, some metrics are missing (for instance heplify_rtcp_jitter or heplify_rtcp_fraction_lost). 

So I thought it might be a problem of not receiving data properly, then I tcpdumped port 9060:
![traffic](https://user-images.githubusercontent.com/26059063/68787506-f61da400-0641-11ea-9905-cfe6ecfee511.PNG)

The selected packet contains the following info:

> sender_information":{"ntp_timestamp_sec":3782653667,"ntp_timestamp_usec":673437987,"rtp_timestamp":4164483065,"packets":474,"octets":75840},"ssrc":602099638,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":26962,"fraction_lost":0,"packets_lost":0,"highest_seq_no":29832,"ia_jitter":37,"lsr":0,"dlsr":0}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":602099638}2NmFlZGE3YmZjMzg4MmEwOTBiYTk5NjA4NmRhNmM3ZDM.

Seems right to me! Heplify is receiving the RTP information so I infer there is a problem between Prometheus and Heplify-Server... Does somebody know what could be happening? 
On the other hand, do you recommend me using VictoriaMetrics? Maybe is this DB what is causing the problem...

I am very grateful for all the help!

**Comment by negbie** [comment]
@alexllobet do you still have this? If yes I would need a pcap.

**Comment by negbie** [comment]
@alexllobet let us close this here due to inactivity. If you still need help just write it here or open a new issue with a pcap please.
