### ISSUE TITLE
Docs of Heplify server

### ISSUE THREAD

**Issue by leongnaw8** [sipcapture/heplify-server#281]
Hello,

Do you have any Documents about mechanism of Heplify server? Trying to debug one issue but need to know more about implementation of Heplify server......
Thanks!

BR,
Leon

**Comment by negbie** [comment]
What should these Docs cover exactly?

**Comment by leongnaw8** [comment]
Hi,

Is it possible to have a very draft high level design doc ?
Just like a quic readme :)
Thanks!

br,
Leon

**Comment by lmangani** [comment]
The examples so far provide a decent coverage alongside the code. Any better doc contributions welcome!
