### ISSUE TITLE
Tx and Rx of Heplify-server

### ISSUE THREAD

**Issue by leongnaw8** [sipcapture/heplify-server#282]
Hello,

Would you please help give a few support to this issue?
We sent data to HEPLIFY Server with a stable flow (~1.1MBps). However, when HEPLIFY Server deliver the data to postgre DB, the output/speed bounced, some packets lost and some delayed.
See below snapshot from Grafana about HELPIFY's Rx and Tx.
Under this case, is it related with something in HEPLIFY Sever configuration? Or how to prove it is a issue in postgre DB side? 

![Tx and Rx](https://user-images.githubusercontent.com/44797573/69022283-cda4f980-09f5-11ea-95f8-076665caab14.png)

Thanks a lot!

br,
Leon

**Comment by negbie** [comment]
heplify-server does not insert packet for packet. It distrubutes them around multiple worker, each worker will batch packets and send them if the batch size reaches a limit or after a certain time.

**Comment by negbie** [comment]
So it's very unlikely to have a steady output line.

**Comment by negbie** [comment]
I would recommend you the check your IO on the database server. You can use iostat or iotop

**Comment by leongnaw8** [comment]
Thank you very much for the quick response and suggestions!

Regarding the mechanism of each work sending data to DB, does it need to wait for response from DB, after it send out a batch? 

We assume the 8 workers concurrently...

The size of the batch, and the number of the workers, seems we need to tune to find a balance, to avoid HEPLIFY Server to be the bottle-neck...

**Comment by negbie** [comment]
No it does not. heplify-server is non blocking so when you db isn't able to catch up it will buffer the packets and send them later. If the buffer is full packets will be dropped and you should see that in the heplify-server log. Almost everytime the bottleneck is the database.

So make sure you have a server with enough CPU, IO and RAM.

**Comment by sherry-shi1211** [comment]
@negbie Thanks so much for your detailed response. 

We run heplify-server as a container, if the buffer is full, is the log printed directly in the container log? (kubectl logs heplify-server-pod). 

Now in our container logs, "WARN overflowing db channel, please adjust DBWorker or DBBuffer setting" is printed. This logs means we need to adjust related configuration instead of using the default value?

**Comment by sherry-shi1211** [comment]
Another question is regarding to configuration "DBWorker". The connection count between heplify and database is "DBWorker*4", is that right?

From the source code, i also can see "m.db.SetMaxIdleConns(config.Setting.DBWorker)". So what does "idle connection" mean? If DBWorker=10, does it mean that there are (4*10-10=30) connection used for communication between heplify and database?

Thanks in advance for your kind explanation.

**Comment by negbie** [comment]
In your case it's most likely that the database server or pod can't provide enough IO. 1.1MBps traffic is nothing and should be easily handled with the default settings. So make sure to configure memory request and cpu request in kubernetes for your db pod.

About pg connections take a look here:
https://www.alexedwards.net/blog/configuring-sqldb

DBWorker=10 means 40 pg conns and 10 max idle conns.

**Comment by negbie** [comment]
And most important make sure the db node has enough IO. It's all about IO. If you don't have enough IO no application in the world can help you :)

**Comment by negbie** [comment]
You can run heplify-server on a raspberry pi and insert thousands of packets per second if you database server has enough IO.

**Comment by sherry-shi1211** [comment]
Thanks so much for your quick response and suggestions.

Now in our lab, DBWorker is 10. Per my understanding, the Max connection between heplify and database is 40, is it right?

I run command "ss -tan" to check the connection count. The result is always 10 no matter how many packets there. Does the connection count adjust dynamically?

**Comment by leongnaw8** [comment]
@negbie 
One more question regarding the Rx/Tx of Heplify server.
Dbworker and #CPU, and TCP connections are 10.
Scenario 1: the Rx of Heplify server is ~1.1MBps, and the Tx (data sent from Heplify to DB) is ~1.5MBps. Both Heplify server and the DB work well. No data drop. (Refer to below pic, from 15:10 to 15:22).

Scenario 2: Increase the Rx of Heplify server to be ~2.2MBps.  We expect the Tx (data from Heplify to DB) will be ~3MBps. However, the actual Tx was even lower than 1.5MBps. What caused this? No changes to tcp connections at all...we had thought, the worst case is that, the Tx will be ~1.5MBps...however, the actual is smaller...(See below pic, time from 15:24 to 15:34)

We checked CPU & MEM in both sides...no any problem...
So, we suspect that, there might be a few problems in Heplify server side? Buffer was too small? or other reasons?
![Tx and Rx](https://user-images.githubusercontent.com/44797573/69132692-83a03e80-0aef-11ea-93cb-f7de06abcd55.png)

Thanks,
Leon

**Comment by leongnaw8** [comment]
Besides, Heplify server is client of the tcp connection with DB. Under what condition, it will shut-down the connection? 

Thanks!

**Comment by negbie** [comment]
@leongnaw8 you can configure more dbworker than your available CPU cores but I will set in the code dbworker to the your available CPU cores anyway. So when you have 10 CPU cores SetMaxOpenConns will be 40. Keep in mind that SetMaxOpenConns is a pool. So maybe you don't need 40 connections to handle your load. In your case the traffic is such low it's most likely you don't need all 40 connections.

To your other question. It's easy to answer and obvious that your db setup can handle 1.1MBps but not more. You have two options. Maybe you can tune your DB a bit more by giving it more RAM and CPU otherwise you need hardware whichs provides more IO.

**Comment by negbie** [comment]
It seems that you totally forget about IO. Keep in mind that it's not that easy to handle in kubernetes. But please stop ignoring it by only looking at your RAM and CPU cores ;)
