### ISSUE TITLE
VXLAN header

### ISSUE THREAD

**Issue by sharafi1981** [sipcapture/heplify-server#284]
Hi Eugen,

As per your request on Google group, I am opening an issue related to handling packets that are encapsulated with a VXLAN header. (https://groups.google.com/forum/?nomobile=true#!topic/homer-discuss/qXvcIJQpb5w)

I will prepare a pcap and send it you later. 

Thanks.

**Comment by negbie** [comment]
Hi @sharafi1981 
nice. Could you please open this under heplify? heplify-server is the wrong repo in this case.

**Comment by sharafi1981** [comment]
sure. I will close this and re-open it under heplify.
