### ISSUE TITLE
Not creating all mysql partitions

### ISSUE THREAD

**Issue by rayj-pgi** [sipcapture/heplify-server#295]
We are seeing this error across our servers and we believe it may be related to the new year.

```
mysql.go:337: ERR Error 1526: Table has no partition for value 1577991008
```

It appears that when the table is created it is only creating a single 2 hour partition instead of all 12.

```
mysql> show create table sip_capture_call_20200102;

...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(date))
(PARTITION 20200103_0000 VALUES LESS THAN (1578016800) ENGINE = InnoDB) */
```

I can drop the table, restart heplify-server and it always creates the table with only one partition.

A temporary fix is setting these configuration options:

```
# disabling partitioning
DBPartLog   = "1d"
DBPartIsup  = "1d"
DBPartSip   = "1d"
DBPartQos   = "1d"
```

**Comment by negbie** [comment]
Let me try to reproduce this in docker. We use mysql/mariadb (with rocksdb engine) in prod too and I did not see any errors.

**Comment by negbie** [comment]
Used a plain mysql docker container:

MariaDB [homer_data]> show create table sip_capture_call_20200101;
...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
 PARTITION BY RANGE (unix_timestamp(`date`))
(PARTITION `20200101_0000` VALUES LESS THAN (1577844000) ENGINE = InnoDB,
 PARTITION `20200101_0200` VALUES LESS THAN (1577851200) ENGINE = InnoDB,
 PARTITION `20200101_0400` VALUES LESS THAN (1577858400) ENGINE = InnoDB,
 PARTITION `20200101_0600` VALUES LESS THAN (1577865600) ENGINE = InnoDB,
 PARTITION `20200101_0800` VALUES LESS THAN (1577872800) ENGINE = InnoDB,
 PARTITION `20200101_1000` VALUES LESS THAN (1577880000) ENGINE = InnoDB,
 PARTITION `20200101_1200` VALUES LESS THAN (1577887200) ENGINE = InnoDB,
 PARTITION `20200101_1400` VALUES LESS THAN (1577894400) ENGINE = InnoDB,
 PARTITION `20200101_1600` VALUES LESS THAN (1577901600) ENGINE = InnoDB,
 PARTITION `20200101_1800` VALUES LESS THAN (1577908800) ENGINE = InnoDB,
 PARTITION `20200101_2000` VALUES LESS THAN (1577916000) ENGINE = InnoDB,
 PARTITION `20200101_2200` VALUES LESS THAN (1577923200) ENGINE = InnoDB) |

**Comment by rayj-pgi** [comment]
Hey thanks for looking. We figured out that we need to delete all of the tables for the particular day to get it to rebuild the table. They are partitioning correctly.

```
drop table sip_capture_rest_20200103;
drop table sip_capture_registration_20200103;
drop table sip_capture_call_20200103;
drop table rtcp_capture_all_20200103;
drop table report_capture_all_20200103;
drop table logs_capture_all_20200103;
```
