### ISSUE TITLE
SIP-I message displaying Issue (only SIP-I)

### ISSUE THREAD

**Issue by benhamoua** [sipcapture/heplify-server#298]
Hello,

i m using Homer 7.7 to capture SIP-I message, but when we display the invite message it seems there is corrupted data displayed (attached screenshot), but when we use Homer5 the SIPI message are displayed correctly

<img width="669" alt="Homer5" src="https://user-images.githubusercontent.com/57920841/72209484-d9b9ae80-34ae-11ea-964d-68a283807935.png">
<img width="513" alt="Homer7" src="https://user-images.githubusercontent.com/57920841/72209485-d9b9ae80-34ae-11ea-837c-c1a9ecde877f.png">

**Comment by lmangani** [comment]
Thanks for your report. Please provide a SIP-I PCAP sample we can replicate this with.

**Comment by benhamoua** [comment]
> Thanks for your report. Please provide a SIP-I PCAP sample we can replicate this with.


[SIPI_trace.zip](https://github.com/sipcapture/heplify-server/files/4049910/SIPI_trace.zip)

**Comment by adubovikov** [comment]
@benhamoua but you know that this is binary. Would you like to diplay it as decoded ISUP or as a HEX ?

**Comment by adubovikov** [comment]
ok, wir are doing first normal HEX display, after we can implement decoding

**Comment by negbie** [comment]
Please no complicated stuff. Keep it clean and just use something like this:

`func isupToHex(s string) string {
	p1 := strings.Index(s, "/isup")
	if p1 == -1 {
		if p1 = strings.Index(s, "/ISUP"); p1 == -1 {
			return s
		}
	}

	if p2 := strings.Index(s[p1:], "\r\n\r\n"); p2 > -1 {
		p2 = p1 + p2 + 4
		if p3 := strings.Index(s[p2:], "\r\n"); p3 > -1 {
			p3 = p2 + p3
			return injectHex(s, p2, p3)
		} else {
			return injectHex(s, p2, len(s)-1)
		}
	}
	return s
}

func injectHex(s string, start, end int) string {
	return s[:start] + fmt.Sprintf("% X", s[start:end]) + s[end+1:]
}`

**Comment by adubovikov** [comment]
@negbie can I use your function ?

**Comment by benhamoua** [comment]
> @benhamoua but you know that this is binary. Would you like to diplay it as decoded ISUP or as a HEX ?

thank's, the best way is to have it a decoded ISUP body like below, but with HEX is also great :)

![image](https://user-images.githubusercontent.com/57920841/72509120-2d2d5300-3847-11ea-997a-31d8f2225927.png)

**Comment by negbie** [comment]
@adubovikov sure go ahead but it must be checked if the utf8 replacement in heplify-server won't cut some chars. Just a blind guess.

**Comment by adubovikov** [comment]
@benhamoua can you please update to the latest homer-app package and test again ? You can also activate the tshark decoder to see the full decoded message. It will be great if you can confirm that it works for you and you can do some screenshoots :-)

**Comment by benhamoua** [comment]
@adubovikov 

thank you, i have upload lastest Homer but, i get same result

![image](https://user-images.githubusercontent.com/57920841/73167279-de5da400-40f7-11ea-8d5a-0db5e08eee86.png)

**Comment by adubovikov** [comment]
Just uploaded your PCAP and it shows good! Are you sure you have the latest homer-app ?

![Screenshot from 2020-01-27 12-05-18](https://user-images.githubusercontent.com/4513061/73169985-a35e6f00-40fd-11ea-8953-9efd816c19c4.png)
![Screenshot from 2020-01-27 12-06-19](https://user-images.githubusercontent.com/4513061/73169994-a5c0c900-40fd-11ea-84c3-643f49b8d76e.png)
![Screenshot from 2020-01-27 12-06-37](https://user-images.githubusercontent.com/4513061/73170005-a9ece680-40fd-11ea-8c1b-b34a72189e05.png)

**Comment by benhamoua** [comment]
yes i have installed the last one homer 7.7.012, (downloded from Github docker image)

**Comment by lmangani** [comment]
I just pushed a fresh build, could you `docker-compose pull` and try again?

**Comment by benhamoua** [comment]
i have triyed with pull and even new fresh install.

![image](https://user-images.githubusercontent.com/57920841/73175262-0bb34d80-410a-11ea-8d58-e116313c1af3.png)

![image](https://user-images.githubusercontent.com/57920841/73175308-271e5880-410a-11ea-8c8f-7d89e60575f8.png)

**Comment by adubovikov** [comment]
let wait for a release tonight and recheck it

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.16

**Comment by adubovikov** [comment]
please install and let us know

**Comment by benhamoua** [comment]
@adubovikov it's seems works, thank you.

![image](https://user-images.githubusercontent.com/57920841/73436843-87e8a380-434b-11ea-83fe-94cd3f0e30d3.png)

**Comment by adubovikov** [comment]
ok, please activate external decoder and you will see also ISUP messages in the "decoded" tab

**Comment by benhamoua** [comment]
thank, you 🥇 

how i can activate  the decoder.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L77

and be sure that you have installed tshark on your system
