### ISSUE TITLE
SIP Metric Performance

### ISSUE THREAD

**Issue by benhamoua** [sipcapture/heplify-server#299]
Hi,

I m using hom7-prom-all 7.7 and faced a problem with KPI, i have add direction tag to the metric in order to differentiate target traffic direction Incoming or Outgoing:

the purpose is to have KPI for Incoming traffic and outgoing separated, i have already add PromtargetIp & Promtargetname but the metric calculate all trafic IN & OUT at the same time.

in my case i have diffrenete trunk and each one is used for both direction, so need to have KPI-IN & KPI-OUT for the same PromtargetIP, i have used the below formula: but i got incorrect Data ASR = 900%

![image](https://user-images.githubusercontent.com/57920841/72257180-45b12980-360b-11ea-97de-77553afff050.png)

**Comment by negbie** [comment]
Let's assume this is incoming
Host1       Host2
src ------> dst | this is a request like method=INVITE, response=INVITE
dst <------ src | this is a response like method=INVITE, response=200

than outgoing is like:
Host1       Host2
dst <------ src | this is a request like method=INVITE, response=INVITE
src ------> dst | this is a response like method=INVITE, response=200

**Comment by negbie** [comment]
Short, your calculation is wrong.

**Comment by benhamoua** [comment]
thanks for you help

**Comment by benhamoua** [comment]
dear @negbie 

i have tried below metric but it seems also incorrect, can you please help with example:

(sum(rate(heplify_method_response{target_name=~"$tn",direction="src",method="INVITE",response="200"}[5m]))) * 100 / (sum(rate(heplify_method_response{target_name=~"$tn",direction="dst",method="INVITE",response="INVITE"}[5m])))

**Comment by negbie** [comment]
Here is a screenshot of a graph I made last year exactly for this:

![asr](https://user-images.githubusercontent.com/20154956/72280149-f03f4180-3637-11ea-8f25-9fe3d1554805.jpeg)

**Comment by benhamoua** [comment]
Thank's for help
