### ISSUE TITLE
RURI User, From User and To User is not recorded if format it TEL URI

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify-server#30]
I compile the latest helplify-server "go install heplify-server.go" from the path location heplify-server\cmd\heplify-server

Then i run the server with ./heplify-server -loglvl debug
I can see the data going into the mysql server. I notice that calls with Tel URI are not stored in mysql properly. 
 - RURI User, From User and To User are not stored (the fields are empty).
 - The call itself is stored as i can find the entry in mysql (with all the information in msg column)

If the calls is with SIP URI, the RURI User, From User and To User are stored correctly.

**Comment by games130** [comment]
These are the tel format from the debug:

2018-04-10T11:00:12+08:00 DBG  [hep] &HEP{Version:2,Protocol:17,SrcIP:172.16.124.22,DstIP:172.16.124.15,SrcPort:5060,DstPort:5060,Tsec:1523329212,Tmsec:67276,ProtoType:1,NodeID:2001,NodePW:myhep,Payload:INVITE tel:+6569179715 SIP/2.0

From: <tel:+6583199881>;tag=k2zuofun-CC-1004
To: <tel:+6569179715>

It is strange if you manage to parse the TEL URI "tel:5554448000@myfoo.com" successfully because as per my understanding, this is a wrong TEL URI format.
If a TEL format have the domain name it would be in this format "tel:7042;phone-context=example.com"

Or another format for tel can be "tel:863-1234;phone-context=+1-914-555"
I two example i have gotten off the https://tools.ietf.org/html/rfc3966

**Comment by negbie** [comment]
Hi games130,
first of all thank you for your effort. I really appreciate it! I am sorry that I cannot response as fast as I used to (preparation for a vacation)

With your changes some other URI tests did not pass. 
go test
--- FAIL: TestUri (0.00s)
        uri_test.go:33: [TestUri] Error parsing URI "tel:5554448000@myfoo.com".  Should have received "5554448000" as the user.  Received: 5554448000@myfoo.com
        uri_test.go:36: [TestUri] Error parsing URI "tel:5554448000@myfoo.com".  Host should be "myfoo.com" but received:
FAIL
exit status 1
FAIL    github.com/negbie/sipparser     0.001s

But I see the problem in the code and I will fix it.

**Comment by games130** [comment]
Yup, i notice this problem as well. but this TEL URI should not exist in the first place because it is the wrong format. should it return a different error? or just parse it as best as possible?

**Comment by negbie** [comment]
My wife will probably punch me but I found some time to tweak your changes so they will pass the tests ;)
https://github.com/negbie/sipparser/commit/e3ca502d4c4b3c7cecabda9d5234b2c9abac2b6b

While I agree with you that this tel format with \@hostpart is invalid I made the changes in a way nothing else will be affected without the need to write a parser for rfc3966 tel format

**Comment by games130** [comment]
I have check with the latest update you have done, it is working fine now. Thank you for taking the time to make the changes. Have a happy holiday.

Now that this is resolve, do i just click close for the issue?

**Comment by negbie** [comment]
Yes simply close it. You can still reopen it later.

**Comment by Navid-wgtwo** [comment]
What is a ruri user ? 
thanks

**Comment by lmangani** [comment]
@Navid-wgtwo 

``` 
Request URI
INVITE sip:bob@biloxi.example.com SIP/2.0

The Request URI is the contact information of the next hop in the call route. 
In the above example, the username of the next hop is bob, who is hosted by biloxi.example.com.
```


here are a couple useful links:

- https://transnexus.com/whitepapers/sip-invite-header-fields/
- https://datatracker.ietf.org/doc/html/rfc3261
