### ISSUE TITLE
1.14 creates a ton of postgres db connections

### ISSUE THREAD

**Issue by abv** [sipcapture/heplify-server#306]
I'm not exactly sure what's going on, but I've rolled back to 1.13 for the time being. I noticed 1.14 creating a ton of postgres db connections until I started seeing "remaining connection slots are reserved for non-replication superuser connections" in my logs.

**Comment by lmangani** [comment]
@abv could you attach some examples and/or those logs for investigation and validation

**Comment by lmangani** [comment]
perhaps @negbie can comment on this vs. the changes

**Comment by adubovikov** [comment]
abv, please be sure that for in the config you have:
DBConfTable           = "homer_config_tmp" 

othwerwise it will replace correct configuration of 7.7

**Comment by abv** [comment]
Looks related to db.Ping() in rotator.go?

Some logs:

```
2020/01/22 16:30:47.128406 rotator.go:94: ERR pq: remaining connection slots are reserved for non-replication superuser connections
2020/01/22 16:30:49.124690 rotator.go:94: ERR pq: remaining connection slots are reserved for non-replication superuser connections
2020/01/22 16:30:51.171980 rotator.go:94: ERR pq: remaining connection slots are reserved for non-replication superuser connections
```

**Comment by negbie** [comment]
Yeah I see the bug. Ticker ticks but db conn never gets closed when it's postgres. Will fix later.

**Comment by negbie** [comment]
Fixed. I reuploaded the new binary under same version 1.14. Good job for monitoring the db conn count! Not all ppl I know are doing this but they should!

**Comment by negbie** [comment]
Will close this now. Just reopen if you find something else.

**Comment by lmangani** [comment]
I replaced the 1.14 package releases on the repository just to be safe w/ the latest build.
