### ISSUE TITLE
postgresql errors

### ISSUE THREAD

**Issue by ccmsi** [sipcapture/heplify-server#309]
Greetings.
We observed the following messages in postgresql logs which may be fixable with input data validation:

1)
STATEMENT:  COPY hep_proto_1_registration(sid,create_date,protocol_header,data_header,raw) FROM STDIN
ERROR:  invalid input syntax for type json
DETAIL:  Character with value 0x09 must be escaped.

2)
STATEMENT:  COPY hep_proto_1_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN
ERROR:  invalid input syntax for type json
DETAIL:  Token "asterisk" is invalid.
CONTEXT:  JSON data, line 1: ...:5060","method":"OPTIONS","user_agent":""asterisk...

Best regards and thanks for heplify, no doubt a great tool.

**Comment by negbie** [comment]
About 1. 0x09 is TAB and valid utf8 but needs to be escaped for postgres. So code around this line needs to be adjusted:
https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L170

About 2. This should be coverd in newer releases. Which release do you use? The issue here are the quotation marks around user_agent which will be escaped in newer releases.

**Comment by ccmsi** [comment]
I'm running heplify-server 1.15

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.20

**Comment by ccmsi** [comment]
Just for clarification, homer-app release is unrelated.

**Comment by adubovikov** [comment]
no, but we recomend anyway update to the latest ;-)

**Comment by ccmsi** [comment]
we do :)

**Comment by negbie** [comment]
@ccmsi pls check latest master branch.

**Comment by ccmsi** [comment]
we have put it into service and will watch it.

**Comment by negbie** [comment]
Nice!

**Comment by ccmsi** [comment]
the intermediate statistical conclusion is that the problem is fixed

**Comment by ccmsi** [comment]
However looking at the diff suggests that the solutions is TAB specific and iE double quotes might still come out with errors

**Comment by negbie** [comment]
Talk is cheap. Show me the code. Torvalds, Linus (2000-08-25).
https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L187

Enjoy and have a nice day.

**Comment by ccmsi** [comment]
https://github.com/sipcapture/heplify-server/commit/fb31a7498525d6cc9fa0dfc7a900bc420062391b#diff-f76bf448a8f93a847f9cc1c78eb7e80d

**Comment by negbie** [comment]
Double quote were already handled before. So all good. Go out and enjoy the sun ;)

**Comment by ccmsi** [comment]
original post case 2 seems to contradict ... ?

**Comment by negbie** [comment]
Maybe you had an older binary at that time or this log line is from an older log. What I can tell you is that double quotes were already handled before you opened the issue.

**Comment by ccmsi** [comment]
what i can say is that the binary is that of https://github.com/sipcapture/heplify-server/releases/tag/1.15 and the log is of the day of the report with said binary
lets give it some time to see

**Comment by negbie** [comment]
Hmm this is strange. Ok if you will see something related to doublequotes again, please just reopen this issue and I will take a deeper look. Have a nice day!

**Comment by ccmsi** [comment]
so far i got two cases, where it asks to escape characters 0x01 and 0x0b. i don't know how these made it into the data. nonetheless one might choose to just filter out all non printable codes.

**Comment by negbie** [comment]
Could you please paste the log lines for these findings?

**Comment by ccmsi** [comment]
had to remove some data for privacy...

2020-02-15 16:00:58.419 UTC [16343] heplify@homer_data ERROR:  invalid input syntax for type json
2020-02-15 16:00:58.419 UTC [16343] heplify@homer_data DETAIL:  Character with value 0x01 must be escaped.
2020-02-15 16:00:58.419 UTC [16343] heplify@homer_data CONTEXT:  JSON data, line 1: ...callid":"0_230...@192....","method":"d...
        COPY hep_proto_1_default, line 11, column data_header: "{"ruri_user":"...
2020-02-15 16:00:58.419 UTC [16343] heplify@homer_data STATEMENT:  COPY hep_proto_1_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN
2020-02-15 16:01:05.468 UTC [16343] heplify@homer_data ERROR:  invalid input syntax for type json
2020-02-15 16:01:05.468 UTC [16343] heplify@homer_data DETAIL:  Character with value 0x0b must be escaped.
2020-02-15 16:01:05.468 UTC [16343] heplify@homer_data CONTEXT:  JSON data, line 1: ...530343130-xvvmo02...","method":"5...
        COPY hep_proto_1_registration, line 84, column data_header: "{"ruri_user":"","ruri_domain":"...
2020-02-15 16:01:05.468 UTC [16343] heplify@homer_data STATEMENT:  COPY hep_proto_1_registration(sid,create_date,protocol_header,data_header,raw) FROM STDIN

**Comment by negbie** [comment]
@ccmsi ok thanks. So it's all about the json strings. Ok let me come up with a solution for escaping the json header.

**Comment by negbie** [comment]
@ccmsi please check latest master. I hope this will catch them all.

**Comment by ccmsi** [comment]
has been deployed, watching logs

**Comment by ccmsi** [comment]
no more cases so far. suggest to close.

**Comment by negbie** [comment]
Sounds good. Feel free to close it. Thank you for the report!
