### ISSUE TITLE
AlegID = other (non X-CID)

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify-server#31]
I am doing call correlation using the header "P-Charging-Vector" - inside this have a field ICID which is constant throughout the call.
Therefore in the heplify-server.toml, i configured:
AlegID          = "P-Charging-Vector"

Based on the captured sip messages in mysql, the callid_aleg column is always empty

example of the header P-Charging-Vector:
P-Charging-Vector: icid-value="d335f5981ed702c414843f092aca5660.3732318005.2962603871.301"

from kamailio, what is did was set the kamailio.cfg with 
modparam("sipcapture", "callid_aleg_header", "P-Charging-Vector")

In the callid_aleg column i would get the value of icid-value="d335f5981ed702c414843f092aca5660.3732318005.2962603871.301"

**Comment by games130** [comment]
So i was doing quick search in the sipparser, Is it correct to say this wont be working because the sipparser does not parse the header P-Charging-Vector?

**Comment by lmangani** [comment]
Thanks for the report @games130 we'll look into this and provide feedback.

**Comment by negbie** [comment]
Well first of all you are right and at the moment I don't look at the P-Charging-Vector header. But still when I would parse it the AlegID handling needs more love.

I removed it with this commit:
https://github.com/sipcapture/heplify-server/commit/6d6a8151fc39c5f1952c6dbf3c186827ed9c0d96
-		for _, v := range h.SIP.Headers {
-			if v.Header == config.Setting.AlegID {
-				h.AlegID = v.Val
-			}
-		}


At this time I wrote inside the sipparser every header+value inside an header array so I could easily iterate through it
https://github.com/negbie/sipparser/blob/master/parser.go#L261

This was working fine but I was looking for a more idomatic way to do this and so I temporaly removed it.

Do you mby have a suggestion how this could be done in a more idomatic way?

**Comment by lmangani** [comment]
@negbie go back to holidays before you get punched! hahah ;)

sounds like in the future this perhaps could be handled from a config list, the same way we do for Prometheus IP groups in order of priority?

**Comment by negbie** [comment]
Hehe its hard to go in offline holiday mode but I will try ;) This sounds like a possible solution.

**Comment by lmangani** [comment]
Seems `toml` supports proper arrays as well:
```
correlation_headers = [
  "X-CID",
  "x-cid",
  "XCall-ID",
  "P-Charging-Vector"
]
```

**Comment by games130** [comment]
Tested the quick fix, working well now. I am able to get the value correctly (like how i was getting when using kamailio).

@lmangani for the toml, is that something for future development? meaning that it will get the header based on the toml file?

**Comment by negbie** [comment]
@games130 please have a look at this issue https://github.com/sipcapture/heplify-server/issues/84
AlegID has changed to AlegIDs and I removed the hardcoded P-Charging-Vector header.

**Comment by games130** [comment]
@negbie okay will get the latest and let you know the test result. hopefully by this week.

**Comment by games130** [comment]
tested with the new changes, "P-Charging-Vector" for the AlegIDs is working well.
