### ISSUE TITLE
loki.go deprecated get/post paths

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/heplify-server#312]
Per Loki's docs, `/api/prom/label` and `/api/prom/push` are deprecated.  They changed it to `/loki/api/v1/`

https://github.com/grafana/loki/blob/master/docs/api.md#get-apipromlabel
https://github.com/grafana/loki/blob/master/docs/api.md#post-apiprompush

Should getPath and postPath be updated?

**Comment by negbie** [comment]
Thanks for the reminder @ghmj2417 ! I will change it soon.

**Comment by ghmj2417** [comment]
If you want, I can submit a PR.  I already signed the CLA.

**Comment by negbie** [comment]
Sure let's go for it and raise the contributors count! Keep in mind that it's not done by only changing 	postPath     = "/api/prom/push"
getPath      = "/api/prom/label"

because I made sure that it will work even when people just use http://loki:3100 instead of http://loki:3100/api/prom/push

**Comment by negbie** [comment]
So keep in mind that there are lots of deployments which have set "HEPLIFYSERVER_LOKIURL=http://loki:3100/api/prom/push"

**Comment by ghmj2417** [comment]
If you are wanting to support the deprecated URI and new URI I see why the PR would require more work.  However, if we are just changing the URI to the new, I don't see anywhere that the code has to be modified.  You already put that work in.

**Comment by negbie** [comment]
Yes I want to support the deprecated URI. It's quite easy to just check if its /api/prom/push and rewrite it to /loki/api/v1/

**Comment by negbie** [comment]
All the heplify stuff should be as easy as possible to use and be good to the user :) So I would like to avoid break existing deployments which just update the binary.

**Comment by ghmj2417** [comment]
I'll wait for you to patch it.  My go expertise is limited and I don't want to screw anything up.

**Comment by negbie** [comment]
You can still do it and I will guide you. The constant getPath could indeed just be changed to /loki/api/v1/label since the user can't set it and it is only used for connectivity test.

For postPath you can place after this condition
	if !strings.Contains(u.Path, postPath) {
		u.Path = postPath
		q := u.Query()
		u.RawQuery = q.Encode()
		l.URL = u.String()
	}

Something like this:
l.URL = strings.Replace(l.URL, postPath, "/loki/api/v1/push", -1)

**Comment by negbie** [comment]
@ghmj2417 please check latest master.

**Comment by ghmj2417** [comment]
Sorry about not following up on this. I wasn't feeling well the past couple of days so my focus shifted from working on this.

Thank you for your help. I appreciate it.

**Comment by negbie** [comment]
Your welcome and get well soon!
