### ISSUE TITLE
[Bug] heplify-server start successfully but heplify-server.log file not create ?

### ISSUE THREAD

**Issue by hangocanh2303** [sipcapture/heplify-server#313]
I'm using CentOS Linux release 7.7.1908 (Core)
I'm install heplify-server via this link: https://github.com/sipcapture/homer/wiki/homer-seven-setup#the-heplify-capture-agent
Result: heplify-server start successfully but heplify-server.log file not create
![image](https://user-images.githubusercontent.com/19758537/74519049-950ab280-4f47-11ea-954e-7bdbf09949e5.png)

Here is heplify-server.toml file: 
HEPAddr               = "0.0.0.0:9060"
HEPTCPAddr            = ""
HEPTLSAddr            = "0.0.0.0:9060"
ESAddr                = ""
ESDiscovery           = false
LokiURL               = ""
LokiBulk              = 200
LokiTimer             = 4
LokiBuffer            = 100000
LokiHEPFilter         = []
ForceHEPPayload       = []
PromAddr        = "0.0.0.0:9096"
PromTargetIP          = ""
PromTargetName        = ""
DBShema               = "homer7"
DBDriver              = "postgres"
DBAddr                = "localhost:5432"
DBUser          = "homer_user"
DBPass          = "FT5QRbUOflpHMrWqXGUwu39r9cQ"
DBDataTable           = "homer_data"
DBConfTable           = "homer_config"
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 32
DBRotate              = true
DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 14
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
DBDropOnStart         = false
Dedup                 = false
DiscardMethod         = ["OPTIONS","NOTIFY"]
AlegIDs               = []
CustomHeader          = []
SIPHeader             = []
LogDbg                = "hep,sql"
LogLvl                = "info"
LogStd                = false
LogSys                = false
Config                = "./heplify-server.toml"
ConfigHTTPAddr        = ""

**Comment by negbie** [comment]
Mby some permission issue?

**Comment by hangocanh2303** [comment]
> Mby some permission issue?

No, I changed permission of heplify-server folder to 777 and log file still not create

**Comment by negbie** [comment]
Does LogSys = true work?

**Comment by hangocanh2303** [comment]
> Does LogSys = true work?

No, When I set LogSys = true, no log in /var/log/heplify-server.log

**Comment by negbie** [comment]
LogSys = true should write into syslog, normally under /var/log/syslog

**Comment by hangocanh2303** [comment]
> LogSys = true should write into syslog, normally under /var/log/syslog
@negbie No syslog folder in /var/log

**Comment by negbie** [comment]
Red Hat family distributions (including CentOS and Fedora) use /var/log/messages and /var/log/secure

Maybe there?

**Comment by negbie** [comment]
I use for almost everything Debian and there it's /var/log/syslog

**Comment by negbie** [comment]
Since this seems to be an CentOS specific issue maybe someone else could help you out here? Let tag this issue properly.

**Comment by hangocanh2303** [comment]
> I use for almost everything Debian and there it's /var/log/syslog

@negbie /var/log/messages printed some log of heplify, I will check it later. 
But, I don't know why if syslog = false, heplify-server.log not create. It seem like centOS bug.

**Comment by hangocanh2303** [comment]
here is some log in /var/log/message
Feb 14 20:14:54  /opt/heplify-server/heplify-server[27016]: server.go:83: start heplify-server 1.15 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:false, ESUser:"", ESPass:"", LokiURL:"", LokiBulk:200, LokiTimer:4, LokiBuffer:100000, LokiHEPFilter:[]int{}, ForceHEPPayload:[]int{}, PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"localhost:5432", DBUser:"homer_user", DBPass:"FT5QRbUOflpHMrWqXGUwu39r9cQ", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:200, DBTimer:4, DBBuffer:400000, DBWorker:32, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"1h", DBPartQos:"6h", DBDropDays:14, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string{"OPTIONS", "NOTIFY"}, AlegIDs:[]string{}, CustomHeader:[]string{}, SIPHeader:[]string{}, LogDbg:"hep,sql", LogLvl:"debug", LogStd:false, LogSys:true, Config:"/opt/heplify-server/heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
Feb 14 20:14:54 mocha-hl-130 /opt/heplify-server/heplify-server[27016]: prometheus.go:38: expose metrics without or unbalanced targets
Feb 14 20:14:54 mocha-hl-130 /opt/heplify-server/heplify-server[27016]: rotator.go:331: start creating tables (2020-02-14 20:14:54.864650105 +0700 +07 m=+0.018368067)
Feb 14 20:14:55 mocha-hl-130 /opt/heplify-server/heplify-server[27016]: rotator.go:344: end creating tables (2020-02-14 20:14:55.544802807 +0700 +07 m=+0.698520771)
Feb 14 20:14:55 mocha-hl-130 /opt/heplify-server/heplify-server[27016]: postgres.go:62: postgres connection established

**Comment by negbie** [comment]
Looks good. Maybe you or someone else will find out why the normal log file can't be written on CentOS. For it's currently to low prio so help is wanted.

**Comment by systemcrash** [comment]
My first thoughts are SELinux. 

```ls -Z /var/log/...```

Try to ```touch``` the target logfile and ```systemctl restart``` heplify. See if that helps. If so, 99% certain it's SELinux perms.

**Comment by negbie** [comment]
Thank you. I hope this helps some other user!

**Comment by ffloimair** [comment]
It's a general bug. There is another issue https://github.com/sipcapture/heplify-server/issues/360 that clearly points to the root cause of problems: A hardcoded path in the working directory.
If you install from qxip repository the binary will be in /usr/local/bin (which is ok), but you certainly don't want to log there.
Why not choose a logical default in /var/log and a configuration option to divert it elsewhere?

As it is it basically unusable/inoperable (at least outside of dedicated containers).

Sure there is logs in syslog but if you want to have it separated this is currently not easily possible.

**Comment by lmangani** [comment]
> As it is now, logging to a file is basically unusable/inoperable (at least outside of dedicated containers).

This is a 4 years old issue you're commenting on so I'm not sure what the value is. If there's a PR or a proposal, we're happy to hear it and implement it.

**Comment by lmangani** [comment]
Hey @ffloimair i'm absolutely not offended but I think opening a fresh issue with your comments, proposals, etc would be more useful than commenting on a very old closed one. Feel free to do so and we'll be happy to look at this again for a solution.
