### ISSUE TITLE
Rtcp-XR QOS Best Overall Practice Advice..

### ISSUE THREAD

**Issue by ryan99alero** [sipcapture/heplify-server#315]
So I just got the newest Homer7.7 via repository installed and running.  I have FreePBX running latest build and latest Asterisk if that matters.  I have mainly all Sangoma recent model phones with a couple Yealink phones.  I have plans of implementing Jitsi VideoBridge with integration into asterisk for the transport and I believe it also supports RtcpXR.

With my current setup I am getting some stats back into db from heplify-server.  I do have all the res_hep modules loaded on asterisk and did the CDR Correlation edits in extensions.conf and cdr_custom.conf. 

My question is what is the future supported way from SipCapture to capture and analyze RTCP stats.  End goal for me would be a simplified view with standard info that would then be somewhat able to dig into the data to see additional info if needed.  I've personally just started on digging into RTCP-XR and what it has to offer so any info or direction is appreciated.

I installed the HEPlify-XRcollector but its from a different repository so I wasn't sure if it was qxip's own product or not.  After some issues I noticed I didn't even have to create a service for it.  That as long as its compiled app is in the same folder as heplify-server it will start the collector for you.

I saw in some other versions of the homer app it had tables in the DB named around the RTCP naming while I don't see any names like that in the current build. I deployed the hepgen.js to see if it'd create an additional tables and I noticed it wrote the data to the hep_proto_35_default directory.  While just the normal heplify that collects some of the data doesn't use the structure for its QOS data.

I mainly have Sangoma phones and there logs are getting errors stating it can't establish a connection to the xrcollector although once its running the port does show open from outside the solution. So before I waste a bunch of time trying to figure out why the phones won't connect and push there data.  I'd like to understand what your guy's current process is for RTCP-XR data in your own portfolio lineup.

**Comment by negbie** [comment]
Hey, sorry but I somehow forgot to respond you in the other repo. You've written so many ununderstandable things I wasn't motivated enough to spend some time on it ;)

Good that you sorted it out that you just need to download the binary and run it. I think proto 35 is not fully implemented in h7.7 yet. So just wait a bit.
