### ISSUE TITLE
additional hep-metrics for CST (call setup time - Time between SIP 200 and Initial INVITE)

### ISSUE THREAD

**Issue by ivlovric** [sipcapture/heplify-server#326]
Hi!

Is there a possibility to have metric of call setup time that is measure between final response 200 OK and initial INVITE request?

Thanks a lot,
I

**Comment by lmangani** [comment]
Hi @ivlovric Homer does not track individual transactions, unless you want to create monster recurring queries which I do not suggest. This feature is only available in [hepic](http://hepic.tel) at this time.

**Comment by negbie** [comment]
@ivlovric that's already included in heplify-server but call setup time is measured for the first 180 or 183 response. So if you want 200 remove 180 and 183 in this line
https://github.com/sipcapture/heplify-server/blob/master/metric/prometheus.go#L112

**Comment by negbie** [comment]
Metric names are heplify_kpi_srd and heplify_kpi_rrd
