### ISSUE TITLE
overflowing db channel

### ISSUE THREAD

**Issue by 00Asgaroth00** [sipcapture/heplify-server#33]
Hi,

What does the following warning mean?

```
2018-04-14T16:44:33+01:00 WARN overflowing db channel by 128 packets
```

I get hundreds of these in the server logs (amongst others). Is there a parameter I need to tweak to increase the channel, or do i need to tweak some other values?

**Comment by negbie** [comment]
Keep in mind its totally ok to get some of this messages when you start heplify-server with enabled rotation. At start same tables will be created which can cause this warning. But when you get this warning and heplify-server is already running for some time you should check how many io your hardware can handle.

**Comment by 00Asgaroth00** [comment]
Hi,

Thanks for the information, I'm currently using mysql. The installation, is a stock install using the homer_installer.sh script. I thought I'd give heplify* a go (BTW, LOVE IT!). I stopped kamailio and fired up heplify-server in its place. When I redirect most of our traffic to it I get those warnings streaming in the logfile consitently, that is after its been up for about 10 minutes then the warnings appear continously.

It wouldnt surprise me if it was mysql, I'm running within a VM, so I guess I'll be limited there. My current mysql config is as follows:

```
# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html

[mysqld]
sql-mode="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLE"
#
# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M
#
# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
# log_bin
#
# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
validate_password_policy=LOW

max_connections = 8000
tmp_table_size  = 32M
thread_cache_size = 50
query_cache_type = 0
query_cache_size = 0
max_heap_table_size = 4G
open_files_limit = 65535
table_definition_cache = 1024
table_open_cache = 2048

#INNODB
innodb_flush_method = O_DIRECT
innodb_log_files_in_group = 2
innodb_log_file_size = 500M
innodb_flush_log_at_trx_commit = 2
innodb_file_per_table = 1
innodb_buffer_pool_size = 4G
innodb_stats_on_metadata = 0
innodb_file_format = barracuda
```

The above settings are taken from the sipcapture wiki, the VM itself has 16GB of memory and 6 vCPU's. I don't see any warnings/errors in the mysql log file.

For reference my heplify-server.toml is as follows:

```
Network         = "udp"
Protobuf        = false
Mode            = "homer5"
HEPAddr         = "0.0.0.0:9060"
HEPWorkers      = 200
MQName          = ""
MQAddr          = ""
MQTopic         = ""
PromAddr        = ""
PromTargetIP    = ""
PromTargetName  = ""
RTPAgent        = false
DBDriver        = "mysql"
DBAddr          = "localhost:3306"
DBUser          = "user"
DBPass          = "password"
DBDataTable     = "homer_data"
DBConfTable     = "homer_configuration"
DBPath          = "/var/lib/mysql"
DBBulk          = 400
DBTimer         = 2
DBRotate        = true
DBRotateLog     = "6h"
DBRotateSip     = "2h"
DBRotateQos     = "12h"
DBDropDays      = 0
Dedup           = true
SentryDSN       = ""
AlegID          = "x-cid"
LogDbg          = ""
LogLvl          = "info"
LogStd          = false
Config          = "./heplify-server.toml"
Version         = false
```

I dont have a prometheus server running to pull the rates you request above.

**Comment by lmangani** [comment]
@00Asgaroth00 how's the server load looking as this happens?

**Comment by negbie** [comment]
OK with 30mb per second there is something you can do. Are you using the built in rotator or the perl script? With this amount of traffic you should use smaller table partitions. You can start with 30m and go down to 10m

**Comment by 00Asgaroth00** [comment]
Thanks for the suggestions guys, I'll check that out in a few minutes.

The VM is dedicated purely for homer, up until such time we get a bare metal box for it.

@lmangani The datastore the vm disk resides on is a equilogic san storage device with 20GB cache allocated to it. It currently has 22 10K RPM SAS disks in RAID6 configuration, IOPS combined at the storage side should be well able to handle the current load of the VM.

@negbie I originally was using the perl rotate script, but I'm willing to use heplify-server's built in rotater. This is a new build to replace an older one we have, so I'm able to chop n change things at the moment (still testing).

On a side note, but related, I have 2 questions:
[1] is it possible to specify multiple "-pr" port range parameters for heplify, I have some B2B's that have traffic on multiple ports, just wondering if I can fire up a single heplify instance sniffing all ports.
[2] If I have signalling (SIP) on one interface (eth0) and media (RTP) on another interface (eth1) for a B2B, is heplify able to monitor the RTCP for the media on the media interface even though the parameters for heplify tell it to monitor the signalling port?

**Comment by 00Asgaroth00** [comment]
@lmangani just for reference:

```
# hdparm -Tt /dev/sdb

/dev/sdb:
 Timing cached reads:   10072 MB in  1.99 seconds = 5056.54 MB/sec
 Timing buffered disk reads: 960 MB in  3.00 seconds = 319.98 MB/sec
```

**Comment by negbie** [comment]
The built in rotator at this stage is very basic and mostly for new unexperienced users. The perl rotation script is totally fine. But with your load you should really use small table partitions. Set your rotation.ini to 15min partitions for sip. 

To 1:
You can use -pr 5060-5090 or portrange 6000-6010

To 2: 
As long as you listen in any interface heplify will look for rtcp traffic on all ports. You dont need to care about it

**Comment by negbie** [comment]
To clarify 1 a bit more the first value after -pr should be a single port or portrange but than you can use any valid bpf syntax. For example

-pr 5060-5080 or port 2223 and UDP

**Comment by 00Asgaroth00** [comment]
Thanks @negbie I'll look at those rotation settings, can I turn off heplify-server's rotator if I'm going to be using the perl rotator script?

Ahh, so "-pr" is a bpf filter, good to know. What I was wondering and trying out was something like this:

```
heplify -pr 10100-10199 -pr 10400-10499 -pr 5060-5062 -hs ip:port -e
```
Was just wondering if the above would work.

**Comment by negbie** [comment]
To turn heplify-server's rotator oft set DBRotate to false.

heplify -pr 10100-10199 -pr 10400-10499 -pr 5060-5062

Will not work. Try

-pr 10100-10199 or portrange 10400-10499 or portrange 5060-5062

**Comment by 00Asgaroth00** [comment]
Thanks @negbie, let me try out some of these mysql settings and see how a get on, i'll report back later, thanks @lmangani & @negbie for suggestions so far.

**Comment by lmangani** [comment]
No problem! We might after all need your help back making those leveraged in the next-gen installer ;) BTW there is already a prototype version of the script up while waiting for the full H7 release to be ready.

**Comment by negbie** [comment]
Ok. Right now I would guess most important part is to use smaller partition steps and a bigger innodb_buffer_pool_size

**Comment by 00Asgaroth00** [comment]
Just to make sure I'm modifying the correct part of rotation.ini, this is what I've done:

```
[DATA_TABLE_STEP]
    # 0 - Day, 1 - Hour, 2 - 30 Minutes, 3 - 15 Minutes
    sip_capture_call = 3
    sip_capture_registration = 3
    sip_capture_rest = 3
    rtcp_capture_all = 0
    logs_capture = 0
    webrtc_capture_all = 0
    isup_capture_all = 0
```
That looks like 15 minutes right, so I'll drop existing tables and re-run rotation script to re-create them.

@lmangani Which branch is the prototype script in? I just watche FOSDEM 2018 HOMER 7 presentation last light, looks pretty cool, cant wait for it to come out. I can assist with the scripts when time permits, maybe the company I work for will sponser some time to do the script, I'll check with them :)

**Comment by 00Asgaroth00** [comment]
Just an update, strange things happening now.

When I set partition ranges to 15 minutes, then heplify-server puts all the signaling classed as "rest" into the sip_capture_call_<DATE> table, and not into the sip_capture_rest_<DATE> table. If I shut down heplify-server and start kamailio then data is inserted into the correct tables. If I leave the rotation.ini step to 1 day, then heplify-server  puts the data into the correct tables.

Does this sound like it could be a heplify-server issue or something I'm doing wrong here?

**Comment by negbie** [comment]
Neither nor ;) Those tables will be used

switch query {

		case "call":

			query = "INSERT INTO sip_capture_call_" + time.Now().Format("20060102") + values

		case "register":

			query = "INSERT INTO sip_capture_registration_" + time.Now().Format("20060102") + values

		case "rtcp":

			query = "INSERT INTO rtcp_capture_all_" + time.Now().Format("20060102") + values

		case "report":

			query = "INSERT INTO report_capture_all_" + time.Now().Format("20060102") + values

		case "dns":

			query = "INSERT INTO dns_capture_all_" + time.Now().Format("20060102") + values

		case "log":

			query = "INSERT INTO logs_capture_all_" + time.Now().Format("20060102") + values

		}

As you can see I for SIP I split only into calls and register. So its strange that it should have worked with 1day partitions. Do you need this? I mean to split SIP into more tables? If so I can easily add it after my vacation.

**Comment by 00Asgaroth00** [comment]
@negbie dafuq?! you're on holiday and still replying here?! Go have a break!! 

I think I was expecting similar behaviour to the way kamailio inserts into the tables, its just that when you have presence and options pings in the calls table it can be huge to search through. I guess I could use kamailio in the interim, but I do love heplify's dedupe feature, cleans up alot of call flows for us.

**Comment by 00Asgaroth00** [comment]
I'm currently testing heplify with 3 loadbalancers and 2 media servers, its currently running in pcap mode (default) I may enable it for testing with heplify-server. Is there a major difference between pcap/protobuf?

**Comment by negbie** [comment]
No big difference in terms of performance. I added it to the server so people who dont know hep can simply take the proto file and generate it for the language of choice. For example you want to write a basic capture client in Rust and dont want to write the hep implementation you can simply use the proto file

**Comment by 00Asgaroth00** [comment]
just an update:

with the changes to mysql, so far things are looking alot better. I've not moved the same load across as I had before (when i first opened the issue), but I will continue moving some systems across and keep you updated.

**Comment by negbie** [comment]
Ok, thanks. In environments with some traffic its really important to keep an eye on rows per partition.
Do you want to give Prometheus a try? Every feedback here would be appreciated.

**Comment by 00Asgaroth00** [comment]
Sorry for the late reply.

Is there an upper limit on the rows per partition in mysql? Right now I cannot move the systems I had initially onto this box as I had initially when opening this ticket, reason being, disk space. My test box has 400GB allocated to mysql and that got filled up in 1 and a half days :( So I'm going to try and keep the current load on this test box, up until we can get heplify to [diregarding sip methods](https://github.com/sipcapture/heplify/issues/45), then I can exclude huge amounts of methods while testing.

With regards prometheus, we dont currently have an installtion of it running anywhere (we currently use grafana & graphite), but I could potentially look into setting an instance up and givving it a whirl.

In the toml for heplify server I see some MQ related options, what are those for? We run RabbitMQ here so that could be interesting if there is any relation to those MQ* settings, and, what is being sent over MQ.

**Comment by lmangani** [comment]
I would suggest holding back until the HOMER7 bundle is completed to go for the full picture and the optimizations, just to avoid investing into dead ends as this is literally a hybrid situation which might not persist. Just my 2 cents as we're still finalizing things and migrating formats/databases/etc.

**Comment by lmangani** [comment]
PS: there's an alpha group forming we can happily invite you (or anyone else willing to get REAL dirty) into

**Comment by 00Asgaroth00** [comment]
@lmangani What do you mean by "REAL dirty" :) I could surely help out with some testing, and some shell scripting.

I really like this hybrid combination/configuration though. Heplify/heplify-server is a one-off binary I copy to my systems and fire it up, and so-far, "just works". Configuration of these go tools are simple. The big thing I like about heplify-server is that it can de-dup packets, thats a big win for us both in call flow viewing and database storage space. Granted, it is still early days with these tools, but, the ease of configuration and collection is way way way easier than, for example a kamailio and captagent configuration.

Anyhoo, I'd be willing to help test with homer-7 if you need testers. Hopefully the web-ui/api have been cleaned up alot since homer-5, I see heaps of php errors/warnings in my logs with a default configuration, and, the image url paths in the javascript are hardcoded too, which makes it difficult for people like me that have nginx with a sub-uri for homer as a reverse proxy in front of homer, this images fail in that configuration.

I'm guessing all the focus is currently on homer-7, so I didnt bother logging an issue on the homer-ui/homer-api github tracker.

**Comment by lmangani** [comment]
@00Asgaroth00 correct and correct. H7 does no longer use php/apache to serve itself and is based on a self-contained NodeJS API to keep inline with the spirit of simplicity and ease of assembly, and the UI has literally nothing to do with the 5.x one in terms of elements although it continues its usage traditions.

**Comment by 00Asgaroth00** [comment]
Thanks for the info @lmangani, when will we be able to begin testing H7?

**Comment by lmangani** [comment]
@00Asgaroth00 we'll release the core parts at the OpenSIPS Summit & Kamailio World conferences, everyone's rushing to make the new baseline work with it. We'll notify the mailing list once we cross that bridge

**Comment by negbie** [comment]
"In the toml for heplify server I see some MQ related options, what are those for? We run RabbitMQ here so that could be interesting if there is any relation to those MQ* settings, and, what is being sent over MQ"

With those you can send hep packets to nsq or nats. Makes only sense for bigger setups.

**Comment by 00Asgaroth00** [comment]
@negbie Thanks for the info on MQ stuff. I'm guessing we would need to write our own consumers to process the hep messages over amqp, or, would there be another heplify-server consuming those messages?

@lmangani thanks for the info on release of H-7. Let me know if you still need/want alpha testers, I've got the "green light" from mgmt to assist you guys if you need me.

@negbie Do you want me to open up a seperate issue report for splitting the messages into their associated tables in heplify-server? This is where REGISTER goes to the register tables, and everything else goes into the "call" tables. I'm not sure if you want to support H-5 with heplify-server, anyhow, let me know if you want me to create a seperate, specific, issue for that one.

**Comment by negbie** [comment]
@00Asgaroth00: yes you need to write consumer. But this would be trivial.
You would need to put something like this:

https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/go/receive.go

Into the server
https://github.com/sipcapture/heplify-server/blob/master/server/hep.go

Or register a new server here
https://github.com/sipcapture/heplify-server/blob/master/cmd/heplify-server/heplify-server.go

I would suggest to close this ticket because it slowly gets out of control in terms of topic diversity ;)
Yes, please open for every topic a new issue.

**Comment by negbie** [comment]
About splitting the messages into their associated tables. This got implemented with the latest commit.

**Comment by 00Asgaroth00** [comment]
thanks, i'll try to compile with the new commit and give it a test.

**Comment by 00Asgaroth00** [comment]
ok closing this issue as the original issue was resolved by tweaking mysql.
thanks for all the help everyone.
