### ISSUE TITLE
Mysterious CPU usage hog

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/heplify-server#331]
Noticed via node_exporter that heplify server (v1.19) is hogging all CPU, but doing nothing. Restart, and about 10 minutes later, it eats all CPU again. How to debug this?

```
top
26065 root      20   0  392228 181392   6636 S 318.3  3.1  61:40.32 heplify-server
  999 node_ex+  20   0  588292  24876   5900 S   1.3  0.4 106:00.41 node_exporter
 4502 root      20   0 1586604 106168  28980 S   1.0  1.8   8:44.84 dockerd
```

logs
```
2020/03/05 15:06:41.954448 server.go:160: INFO heplify-server has been stopped
2020/03/05 15:06:43.836348 server.go:83: INFO start heplify-server 1.19 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"http://xxx.xxx.xx:3100/api/prom/push", LokiBulk:400, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"172.16.16.10:5432", DBUser:"root", DBPass:"homerSeven", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:5, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_domain", "to_user", "callid", "method", "user_agent"}, LogDbg:"", LogLvl:"info", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
2020/03/05 15:06:43.836588 prometheus.go:38: INFO expose metrics without or unbalanced targets
2020/03/05 15:06:43.842412 server.go:121: ERR Get http://xxx.xxx.xx:3100/loki/api/v1/label: read tcp 172.16.16.8:41504->10.xx.xx.xx:3100: read: connection reset by peer
Could not find toml config file, use flag defaults. <nil>
2020/03/05 15:06:45.850055 rotator.go:394: WARN pq: database "homer_data" already exists

2020/03/05 15:06:45.850467 rotator.go:394: WARN pq: role "homer_user" already exists

2020/03/05 15:06:45.850822 rotator.go:394: WARN pq: role "postgres" does not exist
2020/03/05 15:06:45.854025 rotator.go:332: INFO start creating tables (2020-03-05 15:06:45.853990146 +0000 UTC m=+2.031733699)
2020/03/05 15:06:46.513676 rotator.go:345: INFO end creating tables (2020-03-05 15:06:46.513655896 +0000 UTC m=+2.691399445)
2020/03/05 15:06:46.519075 postgres.go:61: INFO postgres connection established
2020/03/05 15:11:43.836931 server.go:243: INFO stats since last 5 minutes. PPS: 0, HEP: 98, Filtered: 0, Error: 0
2020/03/05 15:14:27.843530 tls.go:53: INFO new TLS connection 10.xx.xx.xx:18526 -> 172.16.16.8:9060
2020/03/05 15:16:12.825322 tls.go:53: INFO new TLS connection 10.xx.xx.xx:18540 -> 172.16.16.8:9060
```
time diff on logs and cpu below agree

![Screenshot 2020-03-05 at 16 36 10](https://user-images.githubusercontent.com/647633/75997421-96ece380-5eff-11ea-8de9-24a516f3f95b.png)

**Comment by systemcrash** [comment]
edit: set loglvl to debug, waiting for more info...

**Comment by negbie** [comment]
Hmm never so this in production but try one of this:
https://delta.blue/blog/fix-high-cpu-usage/
check heplify-server pid with strace and -f flag to see what's going on.

Your log looks pretty normal.

**Comment by runelucica** [comment]
I am able to confirm that I noticed the same behavior with a recent deployment.
I noticed this in different 2 instances:
1. Configured by mistake UDP and TLS on heplify-server while the agents were connecting with TCP
docker-compose heplify-server service extract:

> environment: 
  "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
  "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
  "HEPLIFYSERVER_HEPTCPADDR="'

I have 6 agents and in the heplify-server logs I noticed the server trying to negotiate TLS and closing the connections repeatedly. 
After several minutes top shows heplify-server eating up the CPU.

2. Enabled hep and sql debugging with logging level set to warning
docker-compose heplify-server service extract:
environment:
      - "HEPLIFYSERVER_LOGDBG=hep,sql"
      - "HEPLIFYSERVER_LOGLVL=warning"
      - "HEPLIFYSERVER_LOGSTD=true"

After a couple of minutes this is what top shows:

  PID USER      PR  NI    VIRT    RES    SHR S  **%CPU** %MEM     TIME+ COMMAND
23184 root      20   0  189540 113004   5928 S **458.5**  0.7  10:11.90 heplify-server
10243 root      20   0  109092  12060   3212 S   1.0  0.1  36:48.03 containerd-shim
 1867 root      20   0 1156508  52400  14864 S   0.7  0.3  46:06.21 containerd
 1887 root      20   0 1286628  98112  29868 S   0.7  0.6  28:25.63 dockerd

**Comment by negbie** [comment]
Hi @runelucica thanks for the report. I made a commit to log those errors better. Now I check for an error if I can't set read deadline.

**Comment by systemcrash** [comment]
Don't know if this helps - but the process was stuck doing lots (more) of context switches:

![Screenshot 2020-03-06 at 15 25 36](https://user-images.githubusercontent.com/647633/76093375-26a69680-5fc1-11ea-9f12-6b5317be30c6.png)

**Comment by negbie** [comment]
@systemcrash every additional info could help, so thanks for that! Does this happen with v1.23?

**Comment by systemcrash** [comment]
@negbie - could you please pro-actively tag those versions on docker when released, as well as pushing :master and retroactively tagging those versions once they're older?

**Comment by negbie** [comment]
This is done by an build script but first I need to realese a new version because for this action no automatic handling is in place. Because this costs me some minutes I'm not doing it that regulary.

**Comment by systemcrash** [comment]
I pulled in the latest v1.22 - so far so good. Did changes only go into v1.23?

**Comment by negbie** [comment]
@systemcrash as you wrote your comment latest version was 1.23 not 1.22. Anyway currently its 1.24 ;)

**Comment by systemcrash** [comment]
Well, because the only most recent tag is :master, it's difficult to know what version got pulled in until I run it. Anyway, running the latest code, no hogs yet. But we're running mainly UDP at the moment, and we're not utilising TLS as before as per above report by @runelucica 

We will get back to TLS testing in another few days I think.

**Comment by negbie** [comment]
@systemcrash Yeah this needs and will be improved in the future. Ok great every testing is highly appreciated.

**Comment by runelucica** [comment]
With regards to the CPU issues related to TLS, it is sorted out now by making sure there is no overlap in port bindings between TCP and TLS (UDP should not be a problem, but better change the setting there as well just in case).

You could either use a **different port for each connection type**:
 - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
 - "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9061"
 - "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9062"

OR, as per @negbie , **disable (for example TCP and UDP) some settings**:
 - "HEPLIFYSERVER_HEPADDR=-"
 - "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
 - "HEPLIFYSERVER_HEPTCPADDR=-"

I hope this helps.

**Comment by systemcrash** [comment]
I would probably use TLS more frequently but helpify-server currently generates a new root CA on every restart of a new iteration (not a bad thing, but an extra step to get root CA from there to sending host).

Is there some way to have new heplify-server re-use existing root CA?

**Comment by negbie** [comment]
Any news here with version 1.26 about this topic? @systemcrash your question does not belong in this issue.

**Comment by systemcrash** [comment]
Pulled in v1.26 - running. Did not encounter any hogs with short TLS testing yesterday on v1.25

My config is still:
```
"HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
"HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
```

**Comment by negbie** [comment]
Ok I will still let this open just in case you face them again please provide some logs. Thank you!

**Comment by negbie** [comment]
No more reports so I assume it's fixed.

**Comment by systemcrash** [comment]
Yeah, no more weird spikes - thanks :)
