### ISSUE TITLE
Database reconnect settings

### ISSUE THREAD

**Issue by aqsyonas** [sipcapture/heplify-server#338]
I see hepify-server does not try to connect to postgresql if database takes some time to start upon server restart (Starts after heplify-server). 

or in cases where database server has been down for sometime. Is there any parameter to control reconnect tries or mitigate this behavior. 

Tested against version: ` 1.19`

**Comment by negbie** [comment]
Currently not but there is a connect_timeout of 2 seconds. Maybe it would help to raise that?

**Comment by negbie** [comment]
But I see the value so should be implemented.

**Comment by negbie** [comment]
@aqsyonas could you show me your test logs?
In my tests:
./hammerhep -transport tls -rate 100
sudo docker-compose stop db
wait for some time
sudo docker-compose start db

I can see in the logs:

2020/03/09 15:04:52.124617 postgres.go:294: DBG [sql] COPY hep_proto_100_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN

2020/03/09 15:04:53.123767 postgres.go:259: ERR read tcp 127.0.0.1:43244->127.0.0.1:5432: read: connection reset by peer
2020/03/09 15:04:53.124617 postgres.go:259: ERR EOF
2020/03/09 15:04:53.125785 postgres.go:259: ERR EOF
2020/03/09 15:04:57.112292 postgres.go:259: ERR dial tcp 127.0.0.1:5432: connect: connection refused
2020/03/09 15:04:57.112473 postgres.go:259: ERR dial tcp 127.0.0.1:5432: connect: connection refused

....

2020/03/09 15:13:59.762285 postgres.go:259: ERR pq: the database system is starting up
2020/03/09 15:14:03.799324 postgres.go:294: DBG [sql] COPY hep_proto_1_call(sid,create_date,protocol_header,data_header,raw) FROM STDIN

**Comment by aqsyonas** [comment]
@negbie thanks for the answers. I need to check new release on some non production system and i will do so get back to you. As a work around i had modified heplify-server.service file to start it after database.

**Comment by negbie** [comment]
I think we need to look on two cases separately.

1. Initial Database connect.
2. Connection handling when database is down for some time.

I tested case 2 and it works as it should. For case 1 I could implement a finite retry. I don't like the idea of unfinite retires.

**Comment by aqsyonas** [comment]
@negbie just tested again both cases and i think connect_timeout param in heplify is working great for first case. So, i don't see the need for additional param in these cases. I will close this. 
Thanks again. !
