### ISSUE TITLE
How does heplify handle undefined metric entries?

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/heplify-server#342]
In file `metric/definition.go` and `metric/dissect.go`, I do not see a default case or how types that are not predefined are handled.

e.g. if this JSON/RTCP report is sent:

{"report_count":1,"type":200,"ssrc":1546884831,"sender_information":{"ntp_timestamp_sec":3792865130,"ntp_timestamp_usec":292929654,"rtp_timestamp":3436489932,"packets":73,"octets":11680},"report_blocks":[{"source_ssrc":3785321346,"fraction_lost":33,"packets_lost":11,"highest_seq_no":6267,"ia_jitter":0,"lsr":0,"dlsr":0}]}

It's not clear what will happen with the following:
`lsr`, `highest_seq_no`, `source_ssrc`

Are they discarded elsewhere?

**Comment by negbie** [comment]
@systemcrash those metrics just won't be exposed. For some this is intentional because they would cause high cardinality.
