### ISSUE TITLE
Escape correlation ID characters

### ISSUE THREAD

**Issue by husam212** [sipcapture/heplify-server#346]
Having `"` in the correlation ID produces invalid JSON in the database, example log:
```
postgres    | 2020-03-17 11:15:27.832 UTC [66] ERROR:  invalid input syntax for type json
postgres    | 2020-03-17 11:15:27.832 UTC [66] DETAIL:  Token "bmGhEfDoNeJ0m" is invalid.
postgres    | 2020-03-17 11:15:27.832 UTC [66] CONTEXT:  JSON data, line 1: ...","correlation_id":"M_eP0431313170w"bmGhEfDoNeJ0m...
postgres    | 	COPY hep_proto_1_call, line 80, column protocol_header: "{"protocolFamily":2,"protocol":17,"srcIp":"80.90.160.221","dstIp":"159.65.125.17","srcPort":5060,"ds..."
postgres    | 2020-03-17 11:15:27.832 UTC [66] STATEMENT:  COPY hep_proto_1_call(sid,create_date,protocol_header,data_header,raw) FROM STDIN
heplify     | 2020/03/17 11:15:27.833508 postgres.go:284: ERR pq: invalid input syntax for type json
heplify     | 2020/03/17 11:15:27.834590 postgres.go:292: ERR pq: Could not complete operation in a failed transaction
```

More details in https://github.com/sipcapture/homer7-docker/issues/66

**Comment by negbie** [comment]
Hi @husam212 
thats because I don't escape in correlation_header. Currently I do this only with this func for data_header https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L188

**Comment by husam212** [comment]
@negbie is this considered a bug or is it working intended? Is there a way to have the correlation working with IDs having `"` character?

**Comment by negbie** [comment]
@husam212 it's a bug. I just forgot it ;)

**Comment by negbie** [comment]
@husam212 should be fixed in Version 1.27. Please check it out and close this issue if it's fixed for you. Thank you for the report!
https://github.com/sipcapture/heplify-server/releases

**Comment by husam212** [comment]
@negbie thanks, will the docker image [sipcapture/heplify-server:latest](https://hub.docker.com/layers/sipcapture/heplify-server/latest/images/sha256-21312669c000147856cc86d913a4d2e2d4ef50051048fa70274086208ddac61d?context=explore) include the fix?

**Comment by lmangani** [comment]
@husam212 go ahead and try please
```
sipcapture/heplify-server:latest
DIGEST:sha256:21312669c000147856cc86d913a4d2e2d4ef50051048fa70274086208ddac61d
OS/ARCH
linux/amd64
SIZE
8.59 MB
LAST PUSHED
an hour ago by hepic
```

**Comment by husam212** [comment]
It doesn't seem to work, I'm using [this](https://zerobin.net/?51b6e0d9e7961448#RJOCv9jxqU+6LFGVAixpnnrteXIkV0yYg9Nq7AuaeVg=) docker compose, and [here](https://zerobin.net/?0fa2ec150f0f6e01#sJxsYlX/uZiB32ljnCF54ugyxx1YWeYpT26QFVBsg3A=) is the full log.

**Comment by negbie** [comment]
heplify-server prints during starts it's version number. You are using version 1.12 from Oct 2019!
heplify     | 2020/03/23 12:35:34.430375 server.go:90: INFO start heplify-server 1.12 .....

**Comment by negbie** [comment]
seems @lmangani mixed someting up for the docker builder or latest image isn't really latest.

**Comment by negbie** [comment]
Mby you can try one of the other tags here: 
https://hub.docker.com/r/sipcapture/heplify-server/tags

**Comment by negbie** [comment]
As you can see there is a hepic called builder agent and qxip agent. Mby the hepic builds something wrong or old?

**Comment by lmangani** [comment]
The container is built very simply as follows:
```
docker build -t sipcapture/heplify-server -f docker/Dockerfile . && docker push sipcapture/heplify-server
```

**Comment by negbie** [comment]
Something fishy is going on here. Fresh pull for master tag gives me:
heplify-server    | 2020/03/23 12:53:39.089455 server.go:83: INFO start heplify-server 1.15

**Comment by lmangani** [comment]
@negbie I'm not pushing to `master` that's the `codefresh` builder pretty sure

**Comment by husam212** [comment]
Just tried using 1.27 tag, works great, it shows in the log: 
```
INFO start heplify-server 1.27
```

**Comment by negbie** [comment]
Fresh pull for latest tag gives:
heplify-server    | 2020/03/23 12:54:54.051836 server.go:90: INFO start heplify-server 1.12

So pretty sure it's messed up.

**Comment by negbie** [comment]
latest and master tag are messed up currently.

**Comment by negbie** [comment]
Yip just 1.27 tag is working fine:
heplify-server    | 2020/03/23 12:56:45.369019 server.go:83: INFO start heplify-server 1.27

**Comment by lmangani** [comment]
I'm pushing again to both for a test - could you validate again please?

**Comment by negbie** [comment]
Sure. Dockerhub tells me master and latest were pushed 6 min ago. Lets try them out.

**Comment by negbie** [comment]
"master"
heplify-server    | 2020/03/23 13:05:21.416101 server.go:90: INFO start heplify-server 1.12

"latest" 
heplify-server    | 2020/03/23 13:07:27.097246 server.go:90: INFO start heplify-server 1.12

**Comment by lmangani** [comment]
smells like caching to me.... nuking with `--no-cache` and pushing again

**Comment by negbie** [comment]
yeah probably. If it's on dockerhub I will try it one more time.

**Comment by lmangani** [comment]
done should be as fresh as it gets now

**Comment by negbie** [comment]
Now it's ok:
"latest":
heplify-server    | 2020/03/23 13:26:59.157122 server.go:83: INFO start heplify-server 1.27

"master":
heplify-server    | 2020/03/23 13:27:41.359891 server.go:83: INFO start heplify-server 1.27

**Comment by lmangani** [comment]
Ok, build script modified accordingly. Should be good to go from now on. All packages were unaffected, just docker was caching the builds somehow. Thanks!

**Comment by negbie** [comment]
Ok nice. Hope not to many Docker user were affected by this. People should use the binary anyway ;)

**Comment by negbie** [comment]
Maybe this explains some weird issues in the past were I was asking myself what the heck?
