### ISSUE TITLE
Setup for elasticsearch

### ISSUE THREAD

**Issue by bmgante** [sipcapture/heplify-server#349]
I have heplify-server running and sending data to homer 7.
Prometheus metrics are also reachable.
However, i was wondering how to properly setup heplify to send data to elasticsearch (i have a standalone elastic search listening on port 127.0.0.1:9200 and kibana running on the same machine for test purposes). What is the right setup? Are indexes automatically created by heplify?

ESAddr                = ""
ESDiscovery           = true

Thanks

**Comment by lmangani** [comment]
Hi @bmgante 
All you need is `HEPLIFYSERVER_ESADDR=http://elasticsearch:9200` for data, while if you want timeseries you should reconfigure Telegraf to use the Elasticsearch output plugin. I hope this helps!

**Comment by bmgante** [comment]
Hello,

Ok, I´ll try. Just a question, what kind of data does it send to
elasticserach? Is it only the same metrics available for prometheus or does
it send the raw SIP messages?

Thanks

Lorenzo Mangani <notifications@github.com> escreveu no dia segunda,
30/03/2020 à(s) 18:14:

**Comment by lmangani** [comment]
Heplify-Server will dump all packets to `ESADDR`, Telegraf will write the Timeseries.

**Comment by bmgante** [comment]
Got it, it´s working. Is there some more info regarding the usage of the
following parameters, what are they used for and what are the valid
arguments?

AlegIDs               = []
CustomHeader          = []
SIPHeader             = []

From the example:
# AlegIDs         =
["X-CID","P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)","X-BroadWorks-Correlation-Info"]
# CustomHeader    = ["X-CustomerIP","X-Billing"]
# SIPHeader       =
["callid","method","ruri_user","ruri_domain","from_user","from_domain","from_tag","to_user","to_domain","to_tag","via","contact_user"]

Thanks

Lorenzo Mangani <notifications@github.com> escreveu no dia terça,
31/03/2020 à(s) 10:50:

**Comment by lmangani** [comment]
Please read the examples, those are unrelated to elasticsearch and related to correlation - open a different issue if you need help with those.

**Comment by bmgante** [comment]
Ok, I´ll open another issue.
Regarding data export to ES, there´s also the possibility to export all
that raw data to loki.
Is the following URL the right one to send all data or only prom metrics?
"http://localhost:3100/api/prom/push"

Should i use http://localhost:3100/loki/api/v1/push
<http://10.21.12.152:3100/loki/api/v1/push> to forward all data to loki as
i am doing to ES?

The goal is to compare ES vs LOKI to understand which fits better my use
case.

Thanks

Lorenzo Mangani <notifications@github.com> escreveu no dia terça,
31/03/2020 à(s) 14:32:

**Comment by lmangani** [comment]
@bmgante it depends on the Loki version you are using - the API recently changed.
Try both with CURL beforehand against your loki server, and either one will be rejected ;)
