### ISSUE TITLE
WARN overflowing loki channel

### ISSUE THREAD

**Issue by nakchak** [sipcapture/heplify-server#353]
Spotted a new (to me) message in the heplify-server logs following a pull of the latest docker image
Pretty much a continuous stream of this:

> `2020/04/21 08:22:36.561765 server.go:224: WARN overflowing loki channel`
`2020/04/21 08:22:46.281350 server.go:224: WARN overflowing loki channel`
`2020/04/21 08:22:47.637995 server.go:224: WARN overflowing loki channel`
`2020/04/21 08:22:48.746299 server.go:224: WARN overflowing loki channel`
`2020/04/21 08:22:57.639620 server.go:224: WARN overflowing loki channel`

Is this safe to ignore or a cause for concern?

**Comment by lmangani** [comment]
Since you're experiencing this, I would suggest adding some volume information (how much data are you even sending?) as well as asking in the Loki community about the message and its implications, could be relevant to getting help here.

**Comment by negbie** [comment]
Yes and no ;) This means that the Loki message channel reached it's buffer capacity and will start to drop messages. heplify-server is designed in a way that it's non blocking so the other channels like the one for the db or metrics won't be affected. It seems that your Loki server isn't fast enough.

**Comment by negbie** [comment]
I would recommend you to take a look into the Loki settings or even better the cortex settings because a lot of performance critical code comes from cortex. It's quite hard to tweak it right depending on your hardware but normally it should outperform for example elasticsearch by magnitudes!

**Comment by nakchak** [comment]
Cool wont loose any sleep over it

My UAT deployment is a bit of an underpowered VM, and very low traffic maybe 10 test endpoints and carriers connected at most, only really used for internal testing and support escalation.  

Will have a look at the settings you suggest and see if anything changes, although its probably the hardware as its hosted on, its the last of our spinning rust based storage vm hosts and not much ram allocated to the vm (< 10Gb)

**Comment by nakchak** [comment]
Ok, im a muppet, i should have checked loki's status first, its stuck restarting, with this in the logs

`failed parsing config: /etc/loki/local-config.yaml: not a valid duration string: "0"` 

Will dig in further, only change was pulling latest images via a `docker-compose pull`  and changes to the homer7-docker repo

**Comment by nakchak** [comment]
Weird, just restarted fine without any config errors this time....

Closing as seems to a transient issue my end.

**Comment by negbie** [comment]
Ah cool. Jeah the local-config.yaml in the homer7-docker repo is outdated and needs to be fixed some days.

**Comment by nakchak** [comment]
Not quite as closed as i hoped

turns out there has been a format change upstream in cortex of the format for valid durations
https://github.com/grafana/loki/issues/1839

do you have any PR guidelines, as i will submit and updated loki config yaml when i have it working here

**Comment by negbie** [comment]
You will need to sign a CLA but nothing more. Just create the PR and the rest should be quite obvious ;)

**Comment by negbie** [comment]
I would suggest to this issue here and move to the right repo.

**Comment by nakchak** [comment]
Moving to right place
