### ISSUE TITLE
Deduplication issues

### ISSUE THREAD

**Issue by kpribic** [sipcapture/heplify-server#363]
I have `Dedup:true` in toml config however deduplication is inconsistent.Within one call some messages are removed and some are not.
In this particular example proxy and confbridge both have heplify installed and are sending to same heplify-server. All messages are duplicated in INVITE transaction but BYE transaction is not duplicated:

![image](https://user-images.githubusercontent.com/50572561/81396548-e335e900-9125-11ea-8c2a-7cd270ec3ec9.png)

![image](https://user-images.githubusercontent.com/50572561/81396823-6eaf7a00-9126-11ea-8a64-6e53e2eeb4f4.png)

However if I look at the trace on the heplify-server machine BYE transaction message came in twice, just like the INVITE transaction.

I'll take a leap of faith that @negbie will take a look at this so I'll provide traces via email :-)

**Comment by negbie** [comment]
Right I will only (even consider) looking into those issue with a pcap ;)

**Comment by negbie** [comment]
Replayed both pcaps with
./heplify -rf asterisk_sip.pcap -e -rs
./heplify -rf kamailio_sip.pcap -e -rs
to keep the original timestamp and I see the duplicated messages too. It's good that I can replicate this so I will start looking into it.

**Comment by negbie** [comment]
@kpribic please test with commit https://github.com/sipcapture/heplify-server/commit/0af21d0deee6bdfff6982d886ec0c47b9b4011a9

**Comment by negbie** [comment]
Oh and btw. you should check your ntp setup on the servers. It seems you some timedrift between them.

**Comment by negbie** [comment]
If you still see duplicated messages it's because the time between to identical packets is >= 500ms. I cannot filter packtes > 500ms because it could be a retransmission. In your two pcaps there are two identical packets which are +0.538s apart. So it's either a retransmission or a ntp timedrift.

**Comment by kpribic** [comment]
@negbie it works!

I think that retransmission happened because that one INVITE actually got lost (you'll notice that there is only one incoming invite in confbridge trace). I checked the chrony on both machines and it looks ok.

**Comment by kpribic** [comment]
@negbie forgot to ask: are prometheus metrics for SIP messages calculated before or after deduplication?

**Comment by negbie** [comment]
Prometheus metrics will be calculated after deduplication. Duplicated messages will be dropped as soon as possible to reduce processing.
