### ISSUE TITLE
"unsupported field type for default option" error after upgrade to v1.30

### ISSUE THREAD

**Issue by gledim** [sipcapture/heplify-server#366]
Hi team,

We recently started upgrading our heplify-servers from v1.18 to v1.30, but we noticed this error appearing:

`Syntax error in toml config file, use flag defaults. unsupported field type for default option
`
and it looks like the server fails to load any configuration variables from the toml file. 

We have several variables set as env ones, that are loaded correctly, but anything from the file fails to load, presumably as expected by https://github.com/sipcapture/heplify-server/blob/cd08cf382f35eb548e92e71bd9c479d372aba4a3/cmd/heplify-server/heplify-server.go#L36

At first we tried removing HEPLIFYSERVER_HEPTLSADDR from the list of default values, than we verified all the variables that we define, along with all the rest from https://github.com/sipcapture/heplify-server/blob/master/config/config.go, but couldn't spot anything wrong with the field types.

Finally, we pulled the latest build of heplify-server from Docker Hub and managed to replicate the issue there, with a very basic toml file.

Can you please help with any suggestions about this?

**Comment by negbie** [comment]
@gledim could you show me exactly how you reproduced it. How does your config look like and what env var did you use?

**Comment by gledim** [comment]
Hi @negbie 

I noticed the issue with 2 different installation methods, first from upgrading and then from a fresh install.

1. We have a handful of heplify-servers distributed across different tankers, that were working well with version 1.18. They run on docker containers, however we build our own images, based on the source code from your main repository. 
In an env file for these containers, we specify the following variables:
```
SERVER_HOSTNAME
HEPLIFY_PORT
HEPLIFYSERVER_DBDATATABLE
SERVICE_9096_NAME
HEPLIFYSERVER_DBUSER
HEPLIFYSERVER_LOGSTD
HEPLIFYSERVER_HEPTLSADDR
HEPLIFYSERVER_DBSHEMA
SERVICE_9096_TAGS
SERVICE_9060_NAME
DEV_SERVICE_9060_NAME
HEPLIFYSERVER_DBDROPDAYS
HEPLIFYSERVER_DBCONFTABLE
HEPLIFYSERVER_DBPASS
HEPLIFYSERVER_LOGLVL
HEPLIFYSERVER_PROMADDR
DEV_SERVICE_9096_NAME
HEPLIFYSERVER_DBADDR
PRIVATE_IP
HEPLIFYSERVER_DEDUP
DEV_SERVICE_9096_TAGS
HEPLIFYSERVER_DBDRIVER
HEPLIFYSERVER_HEPADDR
```
Not all of them are HEP related, and I have removed their values, but I have checked that at least for the HEP related ones, datatypes match.
In that list used to be also HEPLIFYSERVER_HEPTLSADDR, but I tried removing it without effect.

Then the HEP server is initialized with "-config heplify-server.toml" parameters.

The most recent version of the toml file, after removing some variables from yesterday, contains the ones as follow, where some of the values are hard-coded in it, some are passed using variables.

`
HEPAddr        
HEPTCPAddr     
HEPTLSAddr     
ESAddr       
PromAddr      
PromTargetIP  
PromTargetName  
DBShema         
DBDriver        
DBAddr        
DBUser          
DBPass        
DBDataTable  
DBConfTable   
DBBulk      
DBTimer    
DBRotate    
DBPartLog   
DBPartSip   
DBPartQos  
DBDropDays   
DBDropOnStart 
Dedup        
DiscardMethod 
AlegIDs       
LogDbg       
LogLvl      
LogStd       
Config      
Version    
`

2. As a test, I pulled **sipcapture/heplify-server:latest** from Docker Hub, and initialized the container with: 
`docker run -d --network host --entrypoint /root/heplify-server sipcapture/heplify-server`

I didn't define any external env variables in this case.

Then inside the container I defined a very simple heplify-server.toml file containing only:
`HEPAddr         = "0.0.0.0:9060"
HEPTLSAddr      = "0.0.0.0:9060"
`
and I still see the error message in the logs, or running `./heplify-server -version`

**Comment by negbie** [comment]
@gledim thanks! I can reproduce it and found the issue. It's a regression of the toml lib. Here is the issue: https://github.com/pelletier/go-toml/issues/406

Let me fix that.

**Comment by negbie** [comment]
@gledim fixed with this commit https://github.com/sipcapture/heplify-server/pull/367 new docker images should be up in a minute I guess.

**Comment by gledim** [comment]
@negbie The new version looks good. Thank you very much for the quick fix

**Comment by negbie** [comment]
@gledim you're welcome!
