### ISSUE TITLE
Heplify Server or Homer webapp problem 

### ISSUE THREAD

**Issue by khorsmann** [sipcapture/heplify-server#368]
Hi folks,

I use latest docker images on Homer 7.7 branch and I feed them with Kamailio directly via mod sipcapture. 

That works with one issue I saw, if my Kamailio brings calls to from udp to tls don't see the tls part anymore. 

How can I fetch more info to pinpoint in the correct direction. 

Cheers 
Karsten

**Comment by lmangani** [comment]
Hi @khorsmann So, you mean you used to see them but now you don't after the upgrade? Could you produce a PCAP with the HEP traffic or a sample call?

**Comment by khorsmann** [comment]
I send you my pcaps and made a test call but I changed a lot. Then I take a look on production on Homer 5.5 (different installation) and yes there I got all tls and wss stuff.

**Comment by negbie** [comment]
@khorsmann  do you still need help or can I close this?

**Comment by khorsmann** [comment]
Good question. I will check it Monday. @negbie
