### ISSUE TITLE
Heplify-Server deduplication

### ISSUE THREAD

**Issue by stephanomarques** [sipcapture/heplify-server#371]
Hi!
I have two nodes where ports are being mirrored and sent to heplify-server. Duplication of packets is an issue which I was hoping to solve with the help of heplify-server (otherwise I would need to configure triggers in PostgreSQL and Prometheus on insert).
I have updated to most recent version of heplify-server (1.31.0 - pushed 4 days ago in packagecloud) and have noticed during the latest releases that heplify-server deduplication has been worked on.

My question is: **how does heplify-server really deduplicate the packets**, and is it going to help the situation? **Until now it hasn't solved my problem of deduplication, although in the heplify-server.toml configuration file, dedup is activated (true).**

Could I get some help, as this is a serious issue for us, we have a lot of packets coming in and a lot of space being wasted because of this issue.

Thanks in advance.

**Comment by negbie** [comment]
Hi @stephanomarques 
deduplication is quite simple. I use a global concurrent safe cache with hashed HEP payload as key and HEP timestamp as value.

1.) a hash only from HEP payload will be created.
2.) a lookup from a global cache with the above hash will be performed.
3.) if the hash is in the cache the HEP timestamp will be checked to make sure if it's a retransmission or a duplicate. If the current HEP timestamp is < 500ms apart from  the one found in the cache it's a duplicate and the packet will be dropped.
4.) if the hash isn't in the cache packet is unique. The hash and HEP timestamp of that packet will be stored inside the global cache.

**Comment by negbie** [comment]
Some things you can check:
1.) make sure that the HEP payload is identical.
2.) check the timestamps of the duplicated messages, are they < 500ms apart?

**Comment by stephanomarques** [comment]
So if the packets arrive at **the exact same time**, there will be no way to compare the hashed HEP Payload with an existing entry in the global cache? I've attached a screenshot from HOMER, where the capture ID's are different ports on different switches.
![SharedScreenshot](https://user-images.githubusercontent.com/59531590/82321075-32a0d280-99cc-11ea-9657-c09865fe7324.jpg)

**Comment by negbie** [comment]
Could you please check the message detail tab and paste the unix timestamp with microseconds?

**Comment by stephanomarques** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/59531590/82322143-f0789080-99cd-11ea-8fb2-f73c0b0f884c.jpg)

**Comment by negbie** [comment]
Please click on them and go under the details tab. Isn't there a unix timestamp?

**Comment by stephanomarques** [comment]
Apologies.. 

Node 2001-
timeSeconds 	1589842817
timeUseconds 	973726 

Node 2002-
timeSeconds 	1589842817
timeUseconds 	973724

**Comment by negbie** [comment]
No problem ;) So they aren't the same and are < 500ms apart. Could you please check in the DB if the payload is really identical?

**Comment by negbie** [comment]
If thats the case I would need a pcap to see what's going and check in detail.

**Comment by stephanomarques** [comment]
When you mention the payload are you referring to the "raw" entry? (these are identical when observed).
As for the pcap, is it the exported pcap from homer you need?

**Comment by negbie** [comment]
With HEP payload I mean the payload which will be stored into DB without layer 3 and 4 information like IP and ports. So you say that in general deduplication is working but for some packets not? Does those packets have something in common?

**Comment by stephanomarques** [comment]
The only thing differenciating them is the frame time.. I've double and triple checked the payload and all other fields in the pcap aswell but I can still find a few duplicates here and there (random in the methods, can be a 200, 100, INFO, ACK, etc.) from different node ID's, although most of them have gone, which is a great upgrade compared to before. If the problem insists i'll take a deeper look into it and report what might be the cause. Thanks for your help.

**Comment by olofssonanton** [comment]
@stephanomarques I'm seeing the same issue with seemingly random packets. Did you figure anything out?

**Comment by lmangani** [comment]
@olofssonanton this issue has been closed for many years, I'd suggest opening a new one with as much detail as possible
