### ISSUE TITLE
Grafana RTCP QOS graph - Jitter units wrong?

### ISSUE THREAD

**Issue by AlexHeylin** [sipcapture/heplify-server#374]
Running latest Docker Prometheus build (pulled on Thursday). 

Please forgive me if I'm wrong, but our QOS RTCP graph in Grafana is showing values in "ms" which I find hard to believe ("75ms" jitter) based on reviewing calls in Homer (and real-world performance). 

As I understand it the IA Jitter values in Homer are in "timeunits" (which for 8000 Hz VoIP audio are 0.125 ms each).  The values in the Grafana graph are broadly the same numbers as Homer reports in the QoS tab for calls - but the units are stated as milliseconds, not "timeunits".

I've looked through the code in /metric and I don't see any unit conversion taking place (though I'm a newbie at Go).  Am I missing something, or are the graph units wrong?

Is heplify_rtcp_jitter supposed to be stored in ms or "timeunits"?

If the "75 ms" jitter is actually 75 * 0.125ms then that's 9.375 ms which is a value I'd believe and matches what I see in Homer and real-life performance. If units are being converted, I'd be grateful if someone could point me to where in the code this is done. 

Thanks!

**Comment by negbie** [comment]
heplify-server just decods the values from the heplify client and exposes them for prometheus.

**Comment by AlexHeylin** [comment]
Thanks for the reply, but I'm sorry I'm not clear on your meaning.  You're saying the units are not converted?
Which means the units in Prometheus are in "time units", and thus the Grafana graph is incorrectly labelled with ms when it should be "time units"?
If so, I'll have a go at a PR to address. 
Thanks

**Comment by negbie** [comment]
The units which comes in the RTCP packet.

**Comment by AlexHeylin** [comment]
OK, so Grafana is wrong to have these labelled as "ms" when they're variable length, and typically 0.125ms each.   I'll have a think about how to represent that in Grafana.

**Comment by negbie** [comment]
Grafana 7 comes with transformations and of course you can change units too.

**Comment by negbie** [comment]
Let's close this due to inactivity.
