### ISSUE TITLE
Invites too large and being discarded

### ISSUE THREAD

**Issue by rmmacala** [sipcapture/heplify-server#375]
I am using Kamailio to duplicate SIP messages and send them to a homer7 server. A tcpdump shows the INVITES are reaching the homer server but they are not being stored in the database and do not show on the GUI. The INVITES are longer than 1500 and Kamailio returns a:

`14(37) ERROR: <core> [core/udp_server.c:594]: udp_send(): sendto(sock, buf: 0x7f2e423d70f8, len: 1537, 0, dst: (10.0.1.59:9060), tolen: 16) - err: Message too long (90)
14(37) ERROR: siptrace [../../core/forward.h:228]: msg_send_buffer(): udp_send failed
14(37) ERROR: siptrace [siptrace_hep.c:215]: trace_send_hep3_duplicate(): cannot send hep duplicate message`

Can Homer be configured to accept these messages or is this a kamailio siptrace issue? 

I used the https://github.com/sipcapture/homer/wiki/Examples%3A-Kamailio configuration as an example. The siptrace module duplicate_uri is UDP only.

**Comment by negbie** [comment]
Hi @rmmacala did you try to use TCP?

**Comment by negbie** [comment]
Ah just saw that you mention it's UDP only. Mby you can run a heplify client as a sidecar?

**Comment by negbie** [comment]
And keep in mind that heplify-server will only accept HEP3. As far as I can tell you are using HEP2 (trace_send_hep2_duplicate)

**Comment by rmmacala** [comment]
I will double check my HEP version. I am not overly familiar with Kamailio configuration and integration with Homer, is there alternative way to send the SIP traffic to the homer server? otherwise, yes, a heplify sidecar might be my only option.

**Comment by rmmacala** [comment]
edited original post with a more recent log capture, before was a bad copy paste on my part. currently using HEP3 to send to homer from kamailio.

**Comment by negbie** [comment]
IMHO the fastest way to get you up and running is to download latest heplify version here https://github.com/sipcapture/heplify/releases and point it to heplify-server.

**Comment by rmmacala** [comment]
Alright, I can close this issue then. Seems like heplify might be the only way to send TCP. Thanks.

**Comment by negbie** [comment]
Your welcome. If you still have some troubles just post it here and I'm sure it's fixed in no time!
