### ISSUE TITLE
Diagram alias name problem when two sources have the same IP and port, but different Capture ID

### ISSUE THREAD

**Issue by ijozic** [sipcapture/heplify-server#378]
Hi.

I'm correlating calls from two sources which (due to the current configuration) both show the same localhost IP address (e.g. "0.0.0.0") as src_ip in their HEP events, but they use different capture ID values.

Since alias definitions in homer webapp also require capture ID to be defined, I expected that these two sources would be shown as two separate entities (as they are) on the call diagram according to the specified alias (i.e. though the IP and port are the same, different capture ID should help to distinguish between them and pull the correct alias name definition). 

In practice, only the second of the alias entries is used in both places in the diagram. IMHO, since different Capture ID is used in both sent HEP events and alias definitions, Homer UI should distinguish between them and show them as separate entities in the diagram.

**Comment by lmangani** [comment]
@ijozic we don't distinguish by session ID in the flow - its just a search filter/parameter with no UI relevance other than informational. If you want them to show as separate hosts, you'll have to use different IP:PORT pairs.

I hope this helps,
