### ISSUE TITLE
Prometheus update

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/heplify-server#379]
Trying to understand why the code contains target_name e.g. here:
https://github.com/sipcapture/heplify-server/blob/a4cfcacdf0aa63a3eaa537a43b0d660823698e88/metric/definition.go#L21

If I search the Prometheus client_golang code-base, I see no mention of 'target_name' anywhere. 
https://github.com/prometheus/client_golang/search?q=target_name&unscoped_q=target_name

Anyway - I'm trying to reconcile why `target_name` is even necessary in any of the dashboards. It never fills for me (but dash graphs display). The `target_name` values here are always evaluate to empty:

https://github.com/sipcapture/heplify-server/blob/a4cfcacdf0aa63a3eaa537a43b0d660823698e88/docker/hep-prom-loki-graf/grafana/provisioning/dashboards/SIP_Methods_Responses.json#L97

But if I change to `instance` - they fill and it works to choose the `heplify-server` endpoint. Or is this not what `target_name` was intended for?

Ref: https://github.com/sipcapture/homer7-docker/pull/78/files
ref: https://github.com/sipcapture/homer7-docker/issues/77

**Comment by negbie** [comment]
target_name will be filled when you configure PromTargetIP and PromTargetName, which you normally should do if you have more than one proxy or loadbalancer. Please search through some issues what these settings do.

**Comment by systemcrash** [comment]
My scrape endpoint shows e.g.:
```
# HELP heplify_method_response SIP method and response counter
# TYPE heplify_method_response counter
heplify_method_response{direction="",method="ACK",node_id="1",response="ACK",target_name=""} 31
...
```

So I see that `direction` and `target_name` exist, but are (always) empty for all entries.  Same for `direction`?

**Comment by negbie** [comment]
See my previous response. Without configuring PromTargetIP and PromTargetName you will never get into this code path which adds direction and target_name.

https://github.com/sipcapture/heplify-server/blob/master/metric/prometheus.go#L66

**Comment by systemcrash** [comment]
OK thanks. 
These ones seemed to help:

https://github.com/sipcapture/heplify-server/issues/231
https://github.com/sipcapture/heplify-server/issues/50

Lack of documentation and code comments... no wiki for heplify-server. So these flags are kind of mysterious.

Is wiki a bad idea for this project?

**Comment by lmangani** [comment]
We have a general Wiki for HOMER on the main repository feel free to add any page there.

**Comment by negbie** [comment]
"Is wiki a bad idea for this project?" I don't like the undertone of your question!

**Comment by systemcrash** [comment]
> "Is wiki a bad idea for this project?" I don't like the undertone of your question!

I meant for heplify-server (wiki tab redirects to main code - i.e. it's empty).

**Comment by lmangani** [comment]
Nope. One wiki for all things Homer since a long time. 
You can find it here: https://github.com/sipcapture/homer/wiki
