### ISSUE TITLE
Grafana SIP KPIs Dashboard Calculations

### ISSUE THREAD

**Issue by stephanomarques** [sipcapture/heplify-server#382]
While venturing through the Grafana dashboards kindly made available to us by the sipcapture team, I was taking a look at the SIP KPI's dashboard and noticed the formulas used to calculate SER, SEER, SCR, IRA & ISA. These are inspired by RFC 6076, but couldn't help to notice the **way the Total # of INVITE Requests is calculated**. If these INVITES are NOT taking into account the re-INVITES sent during keep-alives and other re-INVITES, the metrics results will not be accurate at all. Wouldn't it be more efficient to just associate the INVITE without a filled to-tag, meaning all other re-INVITES will be discarded in these calculations? I've included this "to_tag" on the SIP Header in the Heplify-Server but according to the function heplify_method_response(..) it can only have the following "variables": **[]string{"target_name", "direction", "node_id", "response", "method"})**

So my question is: How can I discard re-INVITES to get a very accurate metrics from our clients?

**Comment by negbie** [comment]
Hi @stephanomarques, if you don't configure heplify-server to use PromTargetIP and PromTargetName re-INVITES won't be considered and filtered out.
