### ISSUE TITLE
docker homer-heplify ERROR 1136 (21S01) at line 259: Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by games130** [sipcapture/heplify-server#40]
@negbie notice this error when running the docker
Is this cause by my sql version? I am using 5.7.21 MySQL Community Server (GPL)

> /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init_db.sql
> ERROR 1136 (21S01) at line 259: Column count doesn't match value count at row 1

Error when doing this script
> INSERT INTO `user` VALUES ('localhost','homer_user','*D0F60D1E3C6C124FEEB76527E00A9380C37643EE','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','','','','',0,0,0,0,'mysql_native_password','','N');

the mysql user table is formated as:
mysql> desc mysql.user;

> +------------------------+
> | Field                  |
> +------------------------+
> | Host                   |
> | User                   |
> | Select_priv            |
> | Insert_priv            |
> | Update_priv            |
> | Delete_priv            |
> | Create_priv            |
> | Drop_priv              |
> | Reload_priv            |
> | Shutdown_priv          |
> | Process_priv           |
> | File_priv              |
> | Grant_priv             |
> | References_priv        |
> | Index_priv             |
> | Alter_priv             |
> | Show_db_priv           |
> | Super_priv             |
> | Create_tmp_table_priv  |
> | Lock_tables_priv       |
> | Execute_priv           |
> | Repl_slave_priv        |
> | Repl_client_priv       |
> | Create_view_priv       |
> | Show_view_priv         |
> | Create_routine_priv    |
> | Alter_routine_priv     |
> | Create_user_priv       |
> | Event_priv             |
> | Trigger_priv           |
> | Create_tablespace_priv |
> | ssl_type               |
> | ssl_cipher             |
> | x509_issuer            |
> | x509_subject           |
> | max_questions          |
> | max_updates            |
> | max_connections        |
> | max_user_connections   |
> | plugin                 |
> | authentication_string  |
> | password_expired       |
> | password_last_changed  |
> | password_lifetime      |
> | account_locked         |
> +------------------------+
>

**Comment by negbie** [comment]
Version should be fine. Hmm strange. I tested the docker container yesterday and I got only some telestat errors but after the second docker-compose up everything was ok.

**Comment by negbie** [comment]
Let me build a new compose-file

**Comment by negbie** [comment]
Is this issue still relevant?

**Comment by games130** [comment]
i havent have the time to run this yet, but from the look of it since the doc/docker/graf-homer-hep-promker does not use the script init_db.sql i would say this error wont happen.
