### ISSUE TITLE
Not be able to capture log

### ISSUE THREAD

**Issue by bibace** [sipcapture/heplify-server#400]
heplify server Version: 1.30
Running environment: docker-compose

opensips version: 3.0.0

`loadmodule "proto_udp.so"
loadmodule "proto_hep.so"
modparam("proto_hep", "hep_id", "[hep_dst] heplify.server:9060; transport=udp; version=3")

loadmodule "tracer.so"
modparam("tracer", "trace_id", "[tid]uri=hep:hep_dst")

if (is_method("CANCEL")) {
            trace("tid", "t","sip|xlog" ,"");
            xlog("L_INFO", "Call: CANCEL message received - M=$rm RURI=$ru F=$fu T=$tu IP=$si ID=$ci \n");
	}`

ngrep on heplify server 9060, I can see the log packets

checked mysql homer_data, all hep_proto_100_default_* tables are empty

From homer webapp, search loki logs, I can not see any logs too

**Comment by negbie** [comment]
Please paste your heplify-server.toml, heplify-server.log

**Comment by bibace** [comment]
version: "3"

services:
  heplify-server:
    image: sipcapture/heplify-server:1.30
    ports:
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - "./heplify-server"
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_HEPTCPADDR="
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBADDR=postgres:5432"
      - "HEPLIFYSERVER_DBUSER=sipcapture_homer7"
      - "HEPLIFYSERVER_DBPASS=password"
      - "HEPLIFYSERVER_DBDATATABLE=homer7_data"
      - "HEPLIFYSERVER_DBCONFTABLE=homer7_config"
      - "HEPLIFYSERVER_DBROTATE=true"
      - "HEPLIFYSERVER_DBDROPDAYS=2"
      - "HEPLIFYSERVER_LOGDBG=hep,sql,loki"
      - "HEPLIFYSERVER_LOGLVL=warning"
      - "HEPLIFYSERVER_LOGSTD=true"
      #      - "HEPLIFYSERVER_PROMTARGETIP=127.0.0.1"
      #      - "HEPLIFYSERVER_PROMTARGETNAME=local"
      - "HEPLIFYSERVER_DEDUP=false"
      - "HEPLIFYSERVER_LOKIURL=http://loki:3100/loki/api/v1/push"
      - "HEPLIFYSERVER_LOKITIMER=2"
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

**Comment by bibace** [comment]
I did some research, I found that logs actually were stored in hep_proto_35_default_*.

and on homer-webapp, they were in response of qos request.

**Comment by negbie** [comment]
Normal logs should have HEP type 100 and should go into hep_proto_100_default.

**Comment by bibace** [comment]
> Normal logs should have HEP type 100 and should go into hep_proto_100_default.

You are right, I checked hep_proto_100 tables, they are all empty. 
logs were sent to heplify server via opensips tracer module.

Trying to find the issue and fix it

**Comment by negbie** [comment]
Just make sure that they will be send out with HEP ProtoType 100.

**Comment by lmangani** [comment]
This was an issue with OpenSIPS. It should be fixed in master OpenSIPS HEP.

**Comment by lmangani** [comment]
@bibace please upgrade your setup to master or manually force the HEP logs type to 100 (0x64)

**Comment by bibace** [comment]
> This was an issue with OpenSIPS. It should be fixed in master OpenSIPS HEP.

Thanks Lorenzo

Did you mean Opensip 3.0.* master or heplify-server master?

**Comment by lmangani** [comment]
No idea, but the OpenSIPS team notified and fixed this internally yesterday.

**Comment by bibace** [comment]
Thanks Eugen, Thanks Lorenzo

**Comment by negbie** [comment]
Your welcome!
