### ISSUE TITLE
PromTargetIP (Specific + Overall Targets)

### ISSUE THREAD

**Issue by stephanomarques** [sipcapture/heplify-server#407]
Hi! When inserting PromTargetIP and PromTargetName, for example:

PromTargetIP = "1.1.1.1, 2.2.2.2"
PromTargetName = "Asterisk1, Asterisk2"

My understanding is that heplify-server checks src/dst IP of packet and if matching PromTargetIP it labels with the PromTargetName (target_name="...").
The thing is, I don't want to scrape specifically for every target, so imagine I have 3.3.3.3 and 4.4.4.4 traversing heplify-server but I'm not interested in seeing specific metrics for them but rather overall metrics of both. Is there a way or special char that represents all other IP's so I can get overall and specific metrics, for example:

PromTargetIP = "...,1.1.1.1, 2.2.2.2"
PromTargetName = "...,Asterisk1, Asterisk2"

Where ... represents every other IP and is assigned the same target_name so that metrics are being scraped from them and I can still have an overall view of them and specific view for 1.1.1.1 2.2.2.2.

**Comment by negbie** [comment]
You should be able to do this with prometheus query language. Take a look at sum by or without.

**Comment by stephanomarques** [comment]
I was aware of that method in PromQL but the problem is there are no metrics apart from the ones scraped from PromTargetIP

PromIP 1
![target1](https://user-images.githubusercontent.com/59531590/84779474-590e5980-afdc-11ea-9cd3-83bdaa68ead9.jpg)
PromIP 2
![target2](https://user-images.githubusercontent.com/59531590/84779483-5ca1e080-afdc-11ea-9495-d0ae64dbdb49.jpg)
No target specifically
![targetnull](https://user-images.githubusercontent.com/59531590/84779490-5f043a80-afdc-11ea-97da-90c55626b1bf.jpg)

**Comment by negbie** [comment]
Ah ok now I understand.

**Comment by negbie** [comment]
Thinking about which label I should use for those metrics. I think it's better to not leave it empty.

**Comment by negbie** [comment]
Mby unknown?

**Comment by stephanomarques** [comment]
Unknown sounds good or Other

**Comment by negbie** [comment]
Ok merged https://github.com/sipcapture/heplify-server/pull/409

**Comment by negbie** [comment]
Currently unknown metrics are all which does not match targetip do you think we should just make a metric for any or keep it this way?

**Comment by negbie** [comment]
Basicly every message will increase the any label and additionally target_name if targetip machtes.

**Comment by stephanomarques** [comment]
Sorry was taking a look at the code and building, looks great to me.
Looking at people who will install and use this in the future, I think the approach where there's a metric for Any would be ideal.

**Comment by stephanomarques** [comment]
Although the benefit of the current manner is it's efficient to select All, Any other than specific or specific metrics.

**Comment by negbie** [comment]
Ok will think about it. The "problem" with the any metric is performance impact. Currently unknown label will only be set if there is no match src or dst ip. This should be rare cases. But by using any it will hit everytime.

**Comment by negbie** [comment]
Normally you configure all your edge devices like lb's or gateways as promtarget. So src or dst ip will hit almost everytime.

**Comment by negbie** [comment]
Mby I should add a new config option like PromMetricFilter. With that stuff like that could be controlled.

**Comment by stephanomarques** [comment]
True.. from a performance perspective the "unknown" seems most adequate and for the time being it works. Yes, my issue started from particular cases although almost most are being tagged with Prom.
 
PromMetricFilter does sound interesting and allows for more flexible configurations. The community can brainstorm some ideas, i'll surely be interested when time is more kind to me.

**Comment by negbie** [comment]
Sure, feel free to open a new issue if you have some ideas around this!
