### ISSUE TITLE
exports in latest version seem to produce empty files

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [sipcapture/heplify-server#419]
I recently installed the latest version, using the install script - on a CentOS 7 machine.
When exporting pcaps or txt files - the output file is empty - although the UI displays packets correctly.

No other error can be oserved.

Suggestions?

**Comment by negbie** [comment]
Hi @greenfieldtech-nirs If I remember it right there is still an issue in the UI master branch but it was fixed in devel. Mby its worth to give UI devel branch a try by rebuilding docker image with devel branch.

**Comment by negbie** [comment]
Otherwise you can mby wait for a few days till they merge devel into master. They want to do it asap.
