### ISSUE TITLE
Searching messages using domain name

### ISSUE THREAD

**Issue by sve71** [sipcapture/heplify-server#420]
Hello there,

There is a thread [here](https://mail.google.com/mail/u/0/#inbox/FMfcgxwHNqKNQwlHlHJNSsvfJkMgRcJH).
As Aleksandr said, I need to activate data_header.from_domain extraction in the heplify-server. Could you help me to configure it, please?

**Comment by adubovikov** [comment]
the param is in config:
SIPHeader          []string `default:"ruri_user,ruri_domain,from_user,from_tag,to_user,callid,cseq,method,user_agent"`

just add from_domain to the list

**Comment by sve71** [comment]
Hi,

Thanks, Aleksandr! Everything works fine.
