### ISSUE TITLE
the db record has unkown character

### ISSUE THREAD

**Issue by harold-yh** [sipcapture/heplify-server#421]
at some end of the sip message ,i can see some unkown character

![image](https://user-images.githubusercontent.com/28439656/86463540-46c44780-bd60-11ea-82af-31ff10cbce39.png)

**Comment by lmangani** [comment]
Hi @harold-yh please illustrate your full setup, its all about where the HEP packet came from.

**Comment by harold-yh** [comment]
> Hi @harold-yh please illustrate your full setup, its all about where the HEP packet came from.

cat /etc/heplify-server.toml
HEPAddr               = "0.0.0.0:9060"
HEPTCPAddr            = ""
HEPTLSAddr            = "0.0.0.0:9060"
ESAddr                = ""
ESDiscovery           = true
LokiURL               = ""
LokiBulk              = 200
LokiTimer             = 4
LokiBuffer            = 100000
LokiHEPFilter         = [1,5,100]
ForceHEPPayload	      = []
PromAddr        = "0.0.0.0:9096"
PromTargetIP          = ""
PromTargetName        = ""
DBShema               = "homer7"
DBDriver              = "postgres"
DBAddr                = "localhost:5432"
DBUser          = "homer_user"
DBPass          = "9DKJEIddeEWnjjToUQTAxyvo"
DBDataTable           = "homer_data"
DBConfTable           = "homer_config"
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 8
DBRotate              = true
DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 7
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
DBDropOnStart         = false
Dedup                 = false
DiscardMethod         = ["OPTIONS","NOTIFY"]
AlegIDs               = []
CustomHeader          = []
SIPHeader             = []
LogDbg                = ""
LogLvl                = "info"
LogStd                = false
LogSys                = false
Config                = "./heplify-server.toml"
ConfigHTTPAddr        = ""

**Comment by harold-yh** [comment]
> Hi @harold-yh please illustrate your full setup, its all about where the HEP packet came from.

sorry,it'ok.
I use the captagent for sip capture,the problem is caesed by  captagent client.

**Comment by harold-yh** [comment]
thanks
