### ISSUE TITLE
use specific network intarface to capture

### ISSUE THREAD

**Issue by DavidsonJR90** [sipcapture/heplify-server#427]
Hello,
My server has 4 network interface, is there any way to force the homer to capture network interface # 4?
I belive need to configure heplify's service with an interface parameter.
Where i configure ?

**Comment by aqsyonas** [comment]
This needs to be configured from agent side.

If you use heplify(hep agent) it has the feature to capture hep from a
specific interface only.

Br, Aqs

**Comment by DavidsonJR90** [comment]
Yes, I would like to know in which file, I can configure this specific interface.

**Comment by aqsyonas** [comment]
In heplify service check param -i.

https://github.com/sipcapture/heplify

Br, Aqs

**Comment by adubovikov** [comment]
i am clossing the ticket. If you need, ask directly in heplify-agent
