### ISSUE TITLE
Messages are sorted out of order

### ISSUE THREAD

**Issue by cicahrad** [sipcapture/heplify-server#433]
Messages in Homer GUI (also DB) are sorted out of order. "100 Trying" is before INVITE. When i check data in DB then Trying has has soner us timestamp then INVITE. I also check incoming HEP3 packet and in this us timestamp is correct.

using heplify-server verion 1.32

I feed HEP3 from OpenSIPs 3.1 or Heplify agent and on both i have same issue. In messages from  OpenSIPs, LOG and SIP are not sorted as they generated in OpenSIPs.

If you need some packets dump or data from DB i can provide it.

Thank you
Stepan

**Comment by mkezys** [comment]
I have the same problem with some of the calls. The majority of calls are ok, but sometimes '100 Trying' is before the INVITE.

**Comment by lmangani** [comment]
Please provide actual examples

**Comment by mkezys** [comment]
Flow: https://i.imgur.com/GLGrWud.png

Pcap: https://file.io/n0N5WZk2GRDd

**Comment by mkezys** [comment]
This is fixed?

**Comment by lmangani** [comment]
It should be - Up to you to retest it and confirm using the latest packages
