### ISSUE TITLE
heplify-server .deb installs to /usr/local instead of /usr

### ISSUE THREAD

**Issue by rlaager** [sipcapture/heplify-server#434]
The .deb package on packagecloud.io, which I believe is official, installs heplify-server to /usr/local/bin. On Debian systems, the convention is that packages should install to /usr, not /usr/local. This leaves /usr/local for use for source installs, etc.

I could submit a patch, but I don't know where the source is for the .deb packages.

```
$ dpkg --status heplify-server
Package: heplify-server
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 19458
Maintainer: QXIP SIPCapture <support@sipcapture.org>
Architecture: amd64
Version: 1.32.0
Replaces: heplify-server
Provides: heplify-server
Conffiles:
 /lib/systemd/system/heplify-server.service 0c108f67be3a97eebff7d6d2e5b32741
 /etc/heplify-server.toml 7fe2a53bc872b8f81bd4747e9cf457d8
Description: HEP Capture Server for HOMER/SIPCAPTURE
Vendor: QXIP
Homepage: http://qxip.net

$ dpkg -L heplify-server
/usr
/usr/local
/usr/local/bin
/usr/local/bin/heplify-server
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/heplify-server.service
/etc
/etc/heplify-server.toml
```

**Comment by negbie** [comment]
I think they are from qxip mby built by this script https://github.com/sipcapture/heplify-server/blob/master/scripts/build_package.sh

**Comment by negbie** [comment]
Mby $PACKAGE.yaml should be in this repo aswell but in general I alwayst suggest to build the binary yourself because it's the most secure way.
