### ISSUE TITLE
heplify-server generates a Certificate Authority

### ISSUE THREAD

**Issue by rlaager** [sipcapture/heplify-server#436]
Why is heplify-server generating a certificate authority and dynamically generating certificates based on the specified SNI?

I expected it to load a _certificate_. That is, I have a real certificate (from Let's Encrypt) that I want to use with heplify-server. This does not seem to be a configuration that is supported.

**Comment by negbie** [comment]
No good reason. Mostly because of laziness and I totally agree that it would be better to introduce two new flags for cert and key.

**Comment by negbie** [comment]
Btw. did you try to name your cert and key like the generated ones? As far I remember I only generate new one if I can't find a cert and key in that folder.

**Comment by negbie** [comment]
Mby instead of introducing two new flags it would be enough to mention it in the readme that the user could just put his cert+key with the right name into the heplify-server folder. What do you think?

**Comment by rlaager** [comment]
Yeah, I named the files heplify-server-key.pem and heplify-server-cert.pem. But the code expects to use those as a CA rather than as a server certificate/key. Unless there is a strong need for the CA approach, I think that is fundamentally wrong and should just be _replaced_ by the server certificate approach. The CA approach seems to be attempting to solve some problem around SNI (automatically issuing server certificates for SNI). The typical way this is handled is to take multiple cert/key pairs for the various SNI names. That would require either more complicated configuration grammar or a directory where the certificate/key files are named with the SNI.

**Comment by negbie** [comment]
Ah yes, forgot that already. No there is no strong need for the CA approach. I did it mostly because I wanted something you describe in your last sentence with the directory approach but did not finished it.

**Comment by bashtheshell** [comment]
Can we please reopen this issue or do I need to create a separate issue? 

I tried to look into this to see if I can create a PR, but I'm not familiar with Golang, let alone haven't done SSL/TLS programming, to be able to contribute with the limited amount of time I have. I've been at this for weeks, and I struggled to understand why the executable went through [this particular function](https://github.com/negbie/cert/blob/d1018a8fb00fe8b2ae03cf004a225c54699a2eb1/cert.go#L161) when the non-CA certificates are already provided in the appropriate directory.

**Comment by lmangani** [comment]
@bashtheshell please open a new issue, you can reference to this one in case of need

**Comment by womblep** [comment]
Can you please open this ticket again?
I have the scenario where I need to supply the certificate and key not the CA/key.
I am running heplify in AWS with a private CA and you cant get the key from them for your CA (security) so I am unable to put anything other than a leaf certificate.

**Comment by womblep** [comment]
Can we please reopen this issue?
I have a scenario where I cannot use a CA and need to use a certificate.
The scenario is running Heplify on AWS with a AWS Private CA. I cant get the key for the CA, that is controlled by AWS so I can only put a generated cert onto the server.

**Comment by lmangani** [comment]
@womblep you can use the following settings to use other certs:

```
	TLSCertFolder       string   `default:"."`
	TLSMinVersion       string   `default:"1.2"`
```

**Comment by womblep** [comment]
@lmangani as described above the TLSCertFolder only sets where to load the CA from not a cert. 
It will always generate a cert, not use one already there, either from an automatically generated CA or from the CA loaded from that path.

The code in tls.go loads the CA here:

	// get path for certificate/key storage
	cPath := config.Setting.TLSCertFolder
	minTLSVersion := parseTLSVersion(config.Setting.TLSMinVersion)
	// load any existing certs, otherwise generate a new one
	ca, err := cert.NewCertificateAuthority(filepath.Join(cPath, "heplify-server"))

and then gets a certificate (automatically generating it) here:

		go func() {
			h.handleTLS(tls.Server(conn, &tls.Config{GetCertificate: ca.GetCertificate, MinVersion: minTLSVersion}))
			wg.Done()
		}()

**Comment by lmangani** [comment]
@womblep if you know already, then feel free to submit a PR or open a new issue, not sure what your usecase even is

**Comment by rlaager** [comment]
@lmangani Using a certificate is completely standard for every daemon. For some examples: web servers (Apache, nginx), FTP (ProFTPd), email (Dovecot, Courier, Postfix, Exim) works, IM (ejabberd, prosody), syslog (rsyslog), NTP's NTS (ntpsec). This is how TLS is done everywhere.

Having a CA that generates certificates is extremely unusual. The only place I've ever heard of that would be a proxy doing corporate MITM SSL interception (where the CA is something the corporate computers are configured to trust).

**Comment by lmangani** [comment]
@rlaager we easily understand your point and we've been alive long enough to get it, no need for examples, but as you know we're not a webserver and HEP is not a generic protocol. Furthermore the vast majority of the HEP integrations (clients) do not support TLS at all. Feel free to open a new issue if you want to promote this potential improvement.

**Comment by lmangani** [comment]
> Feel free to submit a PR or open a new issue
