### ISSUE TITLE
Heplify server keeps crashing

### ISSUE THREAD

**Issue by Osmosis311** [sipcapture/heplify-server#443]
Hi.  I am using Homer+Heplify using the Docker instructions found here: 
https://github.com/sipcapture/homer/wiki/Quick-Install#-docker-install

It was working great for me for several months, however, all of a sudden there's no data coming into Homer, and when I check on Heplify I see the following alert whenever the container is started:

![image](https://user-images.githubusercontent.com/360240/98265068-a15ff100-1f56-11eb-808c-9fc277157b40.png)

I have no idea how to check heplify logs inside the container.  I tried to sh into it, but could not find any log files.

Any ideas what could be wrong or how I can diagnose it?

Thanks!

**Comment by lmangani** [comment]
Could be just about anything and the alert doesnt say much. You can try a `docker-compose pull` to get the latest containers, and then `docker-compose restart` see if it restores your functionality. `docker logs --follow {container_name}` will show what is going on inside each instance.

**Comment by Osmosis311** [comment]
Thank you for the fast response!

I did the commands you suggested, and below are the logs.  It looks like it keeps giving warnings, then stopping, then starting again, over and over again.....

Could not find toml config file, use flag defaults. <nil>
2020/11/05 14:28:46.018261 server.go:93: INFO start heplify-server 1.36 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", HEPWSAddr:"", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"http://loki:3100/api/prom/push", LokiBulk:400, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"db:5432", DBUser:"root", DBPass:"homerSeven", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:5, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_tag", "to_user", "callid", "cseq", "method", "user_agent"}, LogDbg:"", LogLvl:"info", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false, ScriptEnable:false, ScriptFolder:"lua/"}
2020/11/05 14:28:46.023323 prometheus.go:38: INFO expose metrics without or unbalanced targets
2020/11/05 14:28:48.334583 rotator.go:406: WARN pq: role "postgres" does not exist

2020/11/05 14:28:48.336837 rotator.go:344: INFO start creating tables (2020-11-05 14:28:48.336818336 +0000 UTC m=+2.347087506)
2020/11/05 14:29:13.157018 rotator.go:357: INFO end creating tables (2020-11-05 14:29:13.156996264 +0000 UTC m=+27.167265230)
2020/11/05 14:29:13.161830 postgres.go:61: INFO postgres connection established
2020/11/05 14:31:41.746834 heplify-server.go:102: INFO stopping heplify-server...
2020/11/05 14:31:41.793756 udp.go:27: INFO stopping UDP listener on [::]:9060
2020/11/05 14:31:42.086230 tls.go:39: INFO stopping TLS listener on [::]:9060
2020/11/05 14:31:42.086701 database.go:75: INFO close postgres channel
2020/11/05 14:31:42.086910 remotelog.go:44: INFO close remotelog channel
2020/11/05 14:31:42.087126 metric.go:69: INFO close metric channel
2020/11/05 14:31:42.087332 heplify-server.go:111: INFO heplify-server has been stopped
Could not find toml config file, use flag defaults. <nil>
2020/11/05 14:32:18.460151 server.go:93: INFO start heplify-server 1.36 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", HEPWSAddr:"", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"http://loki:3100/api/prom/push", LokiBulk:400, LokiTimer:2, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int(nil), PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"db:5432", DBUser:"root", DBPass:"homerSeven", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:400, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"2h", DBPartQos:"6h", DBDropDays:5, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), CustomHeader:[]string(nil), SIPHeader:[]string{"ruri_user", "ruri_domain", "from_user", "from_tag", "to_user", "callid", "cseq", "method", "user_agent"}, LogDbg:"", LogLvl:"info", LogStd:true, LogSys:false, Config:"./heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false, ScriptEnable:false, ScriptFolder:"lua/"}
2020/11/05 14:32:18.460583 prometheus.go:38: INFO expose metrics without or unbalanced targets
2020/11/05 14:32:20.484698 rotator.go:406: WARN pq: database "homer_data" already exists

2020/11/05 14:32:20.485235 rotator.go:406: WARN pq: role "homer_user" already exists

2020/11/05 14:32:20.485687 rotator.go:406: WARN pq: role "postgres" does not exist
