### ISSUE TITLE
Meaningful Documentation

### ISSUE THREAD

**Issue by DGEllis** [sipcapture/heplify-server#448]
Hello,

I found this page:
https://github.com/sipcapture/homer/wiki/HEPLIFY-SERVER-Settings

Please, folks, expand on this. Could you:

1. List all configuration switches
2. Provide what inputs each switch accepts, including ranges to remain within where appropriate
3. What the switch does, what it's intent is, how it is used, and how it relates to other switches

In other words, help up help ourselves.

Thank you,

Darren

PS: It would be a good idea to do this for Homer also.

**Comment by lmangani** [comment]
Hello @DGEllis 
Most critical items are documented in the configuration files, ie: https://github.com/sipcapture/heplify-server/blob/master/example/homer7_config/heplify-server.toml

There are many options for many use cases, you can discover going through the examples of interest. Any contributions are welcome, particularly on the documentation/wiki front. If everyone using it documented one feature they use, a full manual could be done in a few days ;)
