### ISSUE TITLE
Invalid character in db causing blank QoS page

### ISSUE THREAD

**Issue by sunilmmore** [sipcapture/heplify-server#450]
Hello I am using RTPENGINE Version: 9.1.1.2+0~mr9.1.1.2 and trying to connect with homer 7 . The QOS page in homer could not load up. Upon inspection I could observe that the statistics are sent to homer. However the sdes_information type 8 has a text value `{"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}` when sent to homer. What goes into the db is 
`{"sdes_chunk_ssrc":3191907923,"type":8,"text":"x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5`
which later makes the json invalid. After manually editing the value and removing the invalid character from db, I could get the QOS page. 
below are a few more details

data sent to homer by rtpengine.
`
{ "sender_information":{"ntp_timestamp_sec":3818986922,"ntp_timestamp_usec":1687922147,"octets":29584,"rtp_timestamp":2840360, "packets":172},"ssrc":3191907923,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":47986343,"highest_seq_no":39887,"fraction_lost":0,"ia_jitter":114,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":3191907923,"type":1,"text":"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org"},{"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}] }
`
value in db
`
{ "sender_information":{"ntp_timestamp_sec":3818986922,"ntp_timestamp_usec":1687922147,"octets":29584,"rtp_timestamp":2840360, "packets":172},"ssrc":3191907923,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":47986343,"highest_seq_no":39887,"fraction_lost":0,"ia_jitter":114,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":3191907923,"type":1,"text":"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org"},{"sdes_chunk_ssrc":3191907923,"type":8,"text":"x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}] }
`

**Comment by adubovikov** [comment]
@sunilmmore this should be also  an addtional ticket for Homer-UI. Can you please add it ?

**Comment by sunilmmore** [comment]
ok i will add it

**Comment by lmangani** [comment]
is this still an issue with the latest releases?

**Comment by sunilmmore** [comment]
i will check and get back

**Comment by lmangani** [comment]
Thanks! please reopen if needed
