### ISSUE TITLE
Jitter Buffer Misunderstand

### ISSUE THREAD

**Issue by waleedmagdy** [sipcapture/heplify-server#453]
A friend of mine is using Homer to analyze the Asterisk servers and we are getting peaks in Jitter buffer reaching 40s 
however I don't understand how Homer Calculate the Jitter Buffer he is using this query from Promql 

avg_over_time(heplify_rtcp_jitter{node_id="10020"}[30m]) > 10 and changes(heplify_rtcp_jitter{node_id="10020"}[1m]) > 0

if you could please help me how Homer calculate the Jitter and what does it mean and if this query right and will give the right values or not

Thanks

**Comment by waleedmagdy** [comment]
This is how the Voice Traffic going 

![Untitled Diagram](https://user-images.githubusercontent.com/1898623/108061838-8d518280-7061-11eb-8374-a6b9e5c03cd1.png)

**Comment by lmangani** [comment]
Hello @waleedmagdy 
RTCP Jitter is measured in time units not seconds, and the data as-is it extracted from the RTCP reports the user-agents generate, if any. Nothing is calculated by HOMER so you should refer to the RTCP RFC in terms of how the metric parameters and format. Spikes and mistakes in RTCP are quite normal so it's hard to tell with so little information about the actual metrics.

**Comment by waleedmagdy** [comment]
Thanks @lmangani I will take a look at RTCP RFC
