### ISSUE TITLE
Multi Heplify Servers sending logs to Loki Issue

### ISSUE THREAD

**Issue by bibace** [sipcapture/heplify-server#454]
Description:

multiple heplify servers behind an aws network load balance, 

sip server sending hep messages to that nlb.

multiple heplify-servers sending logs to the loki server.

Issue:

heplify servers keep poping sames errors:

 loki.go:155: ERR send time batch: server returned HTTP status 400 Bad Request (400): entry with timestamp 2021-02-18 04:08:38.535985 +0000 UTC ignored, reason: 'entry out of order' for stream: {job="heplify-server", node="1", protocol="sip", type="log"},

checked loki.go, I believe the errors from heplify-servers because all heplify servers sending same labels, loki can not distinguish where messages from and ignored some out of order messages.

If possible, would you mind to add a hostname label to loki.go to solve this issue.

https://github.com/sipcapture/heplify-server/blob/a683cb969af2eeae93abc3f112c4dc25b2168dfc/remotelog/loki.go#L127

Best Regards,

**Comment by lmangani** [comment]
Sounds like a fair approach to me - @adubovikov @negbie what do you guys think?

**Comment by negbie** [comment]
Sounds legit and a hostname label with value of call os.Hostname() could be added.

**Comment by bibace** [comment]
I can submit a PR if you dont mind.

**Comment by negbie** [comment]
@bibace that would be great!
