### ISSUE TITLE
git version tags stop at 1.30 but latest is 1.53

### ISSUE THREAD

**Issue by zombiedk** [sipcapture/heplify-server#457]
when i look at witch tags there is available, the latest is 1.30
but when i look in the src I can find several release, with the latest being 1.53 (12 Jul 2020)
are they just missing or have you stoped setting them ?

https://github.com/sipcapture/heplify-server/tags

**Comment by adubovikov** [comment]
@lmangani can we have a new one ? ;-)

**Comment by zombiedk** [comment]
@lmangani if possible can you also update the rpm / dep files to latest release

**Comment by lmangani** [comment]
fixed the auto builders, new versions pushed to all platforms
