### ISSUE TITLE
heplify-server-1.53.0.rpm missing dependency

### ISSUE THREAD

**Issue by zombiedk** [sipcapture/heplify-server#460]
with the latest rpm, there is a missing dependency for libluajit
if you upgrade from the last version and try to start the service you get this error

```
Mar 05 10:42:35 homer.uni-tel.dk systemd[1]: heplify-server.service: main process exited, code=exited, status=127/n/a
Mar 05 10:42:35 homer.uni-tel.dk heplify-server[11319]: /usr/local/bin/heplify-server: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

```
to fix this you need to install this
yum install luajit-devel

**Comment by lmangani** [comment]
It actually just requires `luajit` what operating system are you using? Please use release package 1.54

**Comment by adubovikov** [comment]
@zombiedk the new package has correct dependecies

for old one, just do yum install luajit

Thank you!

**Comment by zombiedk** [comment]
thanks it is now updated to the latest version
