### ISSUE TITLE
Possibility for call duration metric

### ISSUE THREAD

**Issue by ivlovric** [sipcapture/heplify-server#467]
Hi,

Is there a way to have call duration metric also exposed like "heplify_kpi_srd"  which is already there?

Thanks a lot,
I

**Comment by lmangani** [comment]
HOMER is stateless and does not track "call" duration in the DB, only calculates it in the UI based on session init/teardown. 
Also `srd != call duration` so I'm not understanding the reference.

**Comment by ivlovric** [comment]
Thanks Lorenzo! I understand that srd is not related to call duration, it is reference that I see where heplify-server is calculating something per SIP transactions (time difference from SIP 18x and initial INVITE request). 
If it can not be done, it is good answer for us, thanks :)

**Comment by lmangani** [comment]
Thank you @ivlovric  - note this feature is only available in HEPIC at this time, which is how we sponsor the HOMER development. 
If its vital to your business logic, perhaps you might want to consider that route or consider sponsoring the feature.
