### ISSUE TITLE
WARN could not find a valid CSeq in packet

### ISSUE THREAD

**Issue by alby-235** [sipcapture/heplify-server#470]
I get this error for all captures, the packets do have an appropiate callID so im unsure why its happening

2021-05-12T17:30:08-04:00 WARN could not find a valid CSeq in packet
"SIP/2.0 200 OK\r\nVia: SIP/2.0/UDP ***.***.***.***:5060;branch=z9hG4bKkju2cl009gd2dgq58rn0;received=***.***.***.***\r\nCall-ID: 97311fc32e40429e3b0361c1957d5fbc0200o0g6p3200@***.***.***.***\r\nTo: sip:ping@***.***.***.***\r\nFrom: <sip:ping@***.***.***.***>;tag=30528f7f58da7664c49cb2144eaa67760o0g6p3\r\nCSeq: 223474 "
nodeID: 2017, protoType: 1, version: 2, protocol: 17, length: 289, flow: ***.***.***.***:5060->***.***.***.***:5160

**Comment by lmangani** [comment]
The CSeq line does not appear to be terminated. Whatever generates this is at fault.

**Comment by alby-235** [comment]
Im using hepfix.js the traffic is originated on an oracle sbc

**Comment by lmangani** [comment]
@alby-235 hepfix doesn't generate any message, it just forwards them. So the culprit is the original emitter of sip:ping@
