### ISSUE TITLE
Docker and release tags don't match

### ISSUE THREAD

**Issue by Anthony-Bible** [sipcapture/heplify-server#471]
I've noticed that the docker image does get updated frequently but only the latest image. But the last tag for heplify-server on docker-hub is 1.30 where as the latest release is 1.55.

**Comment by lmangani** [comment]
@Anthony-Bible you're indeed correct, we're pushing to the latest tag on each build. Are you suggesting we remove the old leftover tagged versions to avoid confusion?

**Comment by Anthony-Bible** [comment]
@lmangani  Thanks for the quick response. Probably not as that would hurt deployments that are using any of those tagged versions (we are). I was hoping we might be able to see a tagged docker version get created as a release is created. A latest tag is not beneficial for dynamic environments where the docker may be started on a different server as it may result in a different version that was previously running or a mismatch between environments.

**Comment by lmangani** [comment]
Thanks for the feedback - we'll discuss and see what we can do to try to make this happen.

**Comment by lmangani** [comment]
Images are now on ghcr: https://github.com/sipcapture/heplify-server/pkgs/container/heplify-server
