### ISSUE TITLE
heplify-server rotation

### ISSUE THREAD

**Issue by VladimirMokhov** [sipcapture/heplify-server#477]
Hello, I have a question about heplify-server rotation. How It works? For example: when I set DB Drop Days = 1, data was saved from 2:00 of the current day, but when I set DB Drop Days = 2, data was saved from 22:00 previous day... What means DBMaxSize and DBPercentageUsage parameters in this context? I need to make dump for a day accurately 00:00-23:59 and which values I should choose for this?

**Comment by lmangani** [comment]
Please attach some evidence of your findings including the queries you are using to determine this status. 
If you want to dump data "your way" the best approach is to directly interface with the data Postgres and write your own rotation logic to run externally. There are no side effects as our applications only write forward and query the dataset - once data is gone, they simply won't find it.
