### ISSUE TITLE
Session Correlation

### ISSUE THREAD

**Issue by portsip** [sipcapture/heplify-server#478]
Hi, thanks for a great product.

My question: with the B2BUA PBX, if I use X-CID for the Session Correlation, must I put this X-CID in every SIP message of this call? i.e.: reINVITE message of session timer, BYE?

Thanks

**Comment by lmangani** [comment]
Hi @portsip  No, you do not need to do so. A correlation header can appear in a single message to trigger the correct behaviour. if you dont need to search by your X-header specifically, you might get away by just configuring your X-CID in heplify-server's AlegIDs to extract is as correlation and it all should work automatically as long as mapping is bidirectional. Hope this helps!
