### ISSUE TITLE
hep capture pass

### ISSUE THREAD

**Issue by bit4bit** [sipcapture/heplify-server#483]
thanks for your time
how can i active hep capture pass?

**Comment by adubovikov** [comment]
sorry, can you please concrete your question ?

**Comment by bit4bit** [comment]
thanks, how can i enable hep capture password?

**Comment by adubovikov** [comment]
do you use heplify-server ?

**Comment by bit4bit** [comment]
yes,
 VERSION: heplify-server 1.56

**Comment by kYroL01** [comment]
duplicate issue - already resolved here https://github.com/sipcapture/heplify-server/issues/495
