### ISSUE TITLE
Details on settings in heplify-server.toml

### ISSUE THREAD

**Issue by CoderJoeW** [sipcapture/heplify-server#484]
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000

I do not see where this settings are detailed about what they do specifically for instance if I increased DBBulk to 5000000000 what does this do try to insert 5000000000 rows at a time?

What does DBTimer do specify how often it trys to insert every 4 mins? seconds?
What is DBBuffer? 

Can I get some clarity on the settings please

**Comment by adubovikov** [comment]
it will insert 5000000000 if you will receive these rows in during 4 seconds (DBTimer)

**Comment by adubovikov** [comment]
DBBuffer = how many data you can keep inside (memory buffer) - by overflow the buffer data will dumped into DB
