### ISSUE TITLE
Calculate RTT with the data loaded by Heplify-Server

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/heplify-server#486]
Hello,

I am trying to use the data that heplfy-server stores to perform QoS calculations for each client IP.

Could you describe how the lsr, dlsr, ntp_timestamp_sec and ntp_timestam_usec fields are populated?

I try to replicate the RFC calculations for RTT with those values ​​(assuming they are integer representations of the RTCP field bits) and it gives me crazy results.

Tanks.

**Comment by lmangani** [comment]
The actual RTCP values are extracted and populated by heplify, not heplify-server so that's probably the best place to start from:
Here are the structs: https://github.com/sipcapture/heplify/blob/master/protos/rtcp.go

**Comment by lmangani** [comment]
Here you have a practical reference on how the statistics are rendered in a Grafana set of widgets: https://github.com/sipcapture/homer7-docker/blob/master/heplify-server/hom7-prom-all/grafana/provisioning/dashboards/QOS_RTCP.json

**Comment by mcebey1891** [comment]
Hello,
To close the query, I think the inconsistency occurs because the timestamp data is stored in Little Endian while the rest of the data (LSR and DLSR) is stored in Big Endian.
I corrected the data in my script and now it is at least consistent.
Thanks

**Comment by lmangani** [comment]
Please feel free to share back your scripts with the community as this might help others, too

**Comment by mcebey1891** [comment]
Of course. But it has not yet produced results.

As soon as I have something useful I share it.
