### ISSUE TITLE
feature transaction

### ISSUE THREAD

**Issue by silver0511** [sipcapture/heplify-server#488]
![img_3](https://user-images.githubusercontent.com/3271554/148872334-5eea4563-4809-4af4-ad1f-9bca848fcce9.png)
![img_4](https://user-images.githubusercontent.com/3271554/148872357-68281848-b5ab-4f75-bc4f-3e713bc02643.png)
hi, i have a version, in this we can merge and expand the transaction, please review the picture i uploaded, can i push the code? thanks

**Comment by lmangani** [comment]
Hi @silver0511 thanks for your proposal! 
I'm not sure I understand what the feature does yet, but absolutely any PR and description is welcome for review!

**Comment by silver0511** [comment]
<img width="1435" alt="截屏2022-01-12 10 42 45" src="https://user-images.githubusercontent.com/3271554/149057572-20677c85-ce83-4e5b-b0ed-712eee21d033.png">
@lmangani  hi, my idea came from https://thanhloi2603.wordpress.com/2017/04/22/understanding-sip-transaction-and-dialog/ ,  in my project, one call can have a lot of sips(just like invite,100,200,update....), please see my uploaded picture, i merged sip transaction to make it easier to see and find the problem. can i checkout one branch(feature_transaction) for homer-app、heplify-server、homer-ui？

**Comment by adubovikov** [comment]
@silver0511 sure, all contributions are welcome, please do fork and after PR, but before please describe your roadmap, because there are a lot of elements that have to be changed

**Comment by silver0511** [comment]
@adubovikov thanks, before fork and pr, i will put together a changelog first

**Comment by adubovikov** [comment]
@silver0511 thank you, but you have to prepare the roadmap, the changelog should be done after :-)

**Comment by silver0511** [comment]
@adubovikov sure, i had not prepared the roadmap before, i wonder if you could teach me how to prepare or give me a example url to learn, thanks :-)

**Comment by adubovikov** [comment]
@silver0511 sure - here you are https://www.aha.io/roadmapping/guide/product-roadmap

I am close the ticket for now and waiting for your PR
