### ISSUE TITLE
Incorrect Alpine version when pulling heplify-server:latest

### ISSUE THREAD

**Issue by Ay1000** [sipcapture/heplify-server#498]
Hi There,

When i do a docker pull heplify-server:latest from docker-hub, and we shell into this container running this image, we are getting alpine 3.12.0 as alpine version. 

When we look at the docker file in 'https://github.com/sipcapture/heplify-server/blob/master/docker/Dockerfile', we see that alpine:latest should be used which is 3.16 at the moment: 
copy/paste from dockerfile:
`FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/sipcapture/heplify-server/cmd/heplify-server/heplify-server .
COPY --from=builder /go/src/github.com/sipcapture/heplify-server/scripts ./scripts_
`
As a result our container image scanner detects lots of issues/CVE's.

Are we doing something wrong? Please help.

Thanks

**Comment by adubovikov** [comment]
if you can paste  the errors log here, it can help better ;-)

**Comment by lmangani** [comment]
rather than incorrect, its outdated since there were no commits in between to trigger the build CI - but that's why we point to latest and expect users to build their own version if they desire so. We'll merge a couple fixes a new version will appear.

**Comment by Ay1000** [comment]
@lmangani, Thanks, fair enough, however the image on docker-hub is dated 4 days ago. Do you mean that this heplify-server:latest is not necessarily a CI build which used the alpine:latest? And also alpine 3.12.0 is very old, like a couple of years old, was there no CI build in meantime?

So just to make my question/issue clear, if we pull the heplify-server:latest from docker-hub, which is updated 4 days ago, and we shell into the container running this heplify-server:latest image, 
and run a  cat /etc/os-release
we get 

`NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"`

**Comment by lmangani** [comment]
good point, i've forced the CI to force pull the latest alpine on each build and here's the result:
https://hub.docker.com/layers/heplify-server/sipcapture/heplify-server/latest/images/sha256-89132b2bc05c09d700c4ea9f491ad018dcdd8225c870e0d115316d5abe01937c?context=explore

**Comment by adubovikov** [comment]
@Ay1000 can you please recheck ? It should be fine now

**Comment by Ay1000** [comment]
Thanks guys, checking. . . CI/CD is running.

**Comment by Ay1000** [comment]
It is working, thanks again both @adubovikov & @lmangani :)

**Comment by lmangani** [comment]
Thank you @Ay1000 for catching this!
