### ISSUE TITLE
image store

### ISSUE THREAD

**Issue by lmangani** [sipcapture/heplify-server#5]
please ignore :)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/37555893-00e3f172-29ef-11e8-9112-503f0d0f37a1.png)

![image](https://user-images.githubusercontent.com/1423657/37555890-f9038d1e-29ee-11e8-9dc8-ab661681a8e3.png)

**Comment by negbie** [comment]
![sip_metrics](https://user-images.githubusercontent.com/20154956/39591222-708ee5ac-4f03-11e8-8016-19a564b12bac.jpeg)

**Comment by negbie** [comment]
![xrtp](https://user-images.githubusercontent.com/20154956/39675132-165c5f5a-5157-11e8-9d13-90bccf007638.jpeg)

**Comment by negbie** [comment]
![horaclifix_qos](https://user-images.githubusercontent.com/20154956/39879892-5e7feab8-547c-11e8-8046-a0c73fcef38a.jpeg)

**Comment by negbie** [comment]
![sip_metrics](https://user-images.githubusercontent.com/20154956/39880425-0b940148-547e-11e8-8a95-d0939a2042e6.jpeg)

**Comment by negbie** [comment]
![sip_metrics](https://user-images.githubusercontent.com/20154956/39880524-57838c04-547e-11e8-8dec-262184192742.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/40862016-705d998a-65eb-11e8-8b03-e711b7b4498d.png)

**Comment by negbie** [comment]
![screenshot_2018-12-17 grafana - home](https://user-images.githubusercontent.com/20154956/50091227-0b5c3980-020b-11e9-988a-f49719ede10f.png)

**Comment by negbie** [comment]
![Screenshot-2019-3-17 heplify-server web config](https://user-images.githubusercontent.com/20154956/54483281-ef3f5700-4850-11e9-8da1-9b8bed6186e3.png)

**Comment by negbie** [comment]
![cdr_errors](https://user-images.githubusercontent.com/20154956/70985139-ee777200-20bb-11ea-867b-200cd7e1b6b8.png)
