### ISSUE TITLE
Fresh Docker build, server restarting in constant loop

### ISSUE THREAD

**Issue by lukeescude** [sipcapture/heplify-server#507]
Docker logs shows the following errors:

Error loading shared library libluajit-5.1.so.2: No such file or directory (needed by ./heplify-server)
Error relocating ./heplify-server: lua_resume: symbol not found
Error relocating ./heplify-server: lua_insert: symbol not found
Error relocating ./heplify-server: lua_touserdata: symbol not found
Error relocating ./heplify-server: lua_pushlightuserdata: symbol not found
.... a lot more

This is only an issue with the most recent image.

**Comment by lmangani** [comment]
Thanks for the report @lukeescude are you building your own image or using the public one?

**Comment by adubovikov** [comment]
looks like the app has been compiled in dynamic and not static. Let me recheck it asap

**Comment by adubovikov** [comment]
fixed, let me push the patch. Sorry about that
```
bash-5.1# ls -l
total 18316
-rwxr-xr-x    1 root     root      18751376 Oct 20 10:47 heplify-server
drwxr-xr-x    2 root     root          4096 Oct 20 10:47 scripts
bash-5.1# ldd heplify-server 
/lib/ld-musl-x86_64.so.1: heplify-server: Not a valid dynamic program
```

**Comment by lukeescude** [comment]
Oh, I am using the Public image from docker hub.

Thanks for looking into it!

**Comment by adubovikov** [comment]
@lukeescude can you please re-check ? Should be ok now

**Comment by lukeescude** [comment]
Yes it’s working now!! Thank you!!

**Comment by adubovikov** [comment]
Super! Thank you for report!
