### ISSUE TITLE
Docker latest tag

### ISSUE THREAD

**Issue by karstenjakobsen** [sipcapture/heplify-server#514]
Hi guys

I see you pushed a new Docker image to dockerhub with tag `latest` - can we get a version tag on that?

**Comment by kYroL01** [comment]
Hi @karstenjakobsen 
The `latest` is referring to this version https://github.com/sipcapture/heplify-server/releases/tag/v1.59.3
Thank you

**Comment by xuanzhong** [comment]
> Hi @karstenjakobsen The `latest` is referring to this version https://github.com/sipcapture/heplify-server/releases/tag/v1.59.3 Thank you

@kYroL01 
We are having the same issue. Can we get an explicit tag for the release? 
docker pull sipcapture/heplify-server:v1.59.3, instead of docker pull sipcapture/heplify-server:latest

**Comment by lmangani** [comment]
@xuanzhong and everyone on the thread: Good news! Containers are now [distributed and tagged on ghcr](https://github.com/sipcapture/heplify-server/pkgs/container/heplify-server) please use those instead. If there's any issue with those, please open a new thread.
