### ISSUE TITLE
Remove sip header via lua or other means?

### ISSUE THREAD

**Issue by flantel** [sipcapture/heplify-server#523]
Hi,
We add a header X-L1CID for correlation. Unfortunately some of these headers end up blank (due to limitation of a PBX). If the X-L1CID is blank, homer-app seems to correlate with any other messages with a blank header. 

I would like to either restrict the correlation search to when the X-L1CID is non-blank, or a lua script to remove the header if it is blank.

Is this possible?
Thanks

**Comment by lmangani** [comment]
I doubt this is a heplify-server question and since we're passively monitoring, removing things is not in scope.
You can achieve this in the HOMER mapping themselves with a function on the field.
