### ISSUE TITLE
DB Error - could not map dynamic shared memory segment

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/heplify-server#525]
hey, i run the homer stack of postgres 13, heplify-server and homer-app provided by the homer installer script.

I have an issue when i search in the UI by the parameter captureId, it doesnt show anything. When i does it here's the following error from the postgres log. Weird thing it worked before and it somehow broke in the last few days.

```
STATEMENT:  SELECT * FROM "hep_proto_1_call"  WHERE (create_date between $1 AND $2 AND ( (protocol_header->>'captureId')::int = $3 )) LIMIT 2000
 ERROR:  could not map dynamic shared memory segment
 ERROR:  could not map dynamic shared memory segment
LOG:  background worker "parallel worker" (PID 262853) exited with exit code 1
LOG:  background worker "parallel worker" (PID 262854) exited with exit code 1
```

Here are the DB settings in the `heplify-server.toml` file. From my google searches its seems to indicate a performance issue so what should i tweak in the DB settings?

```
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 10
DBRotate              = true
```

Another Error when searching by source ip and destination ip

```
 ERROR:  syntax error at or near "AND" at character 79
STATEMENT:  SELECT * FROM "hep_proto_1_call"  WHERE (create_date between $1 AND $2 AND (  AND protocol_header->>'dstIp'= $3 )) LIMIT 2000
ERROR:  syntax error at or near "AND" at character 79
 STATEMENT:  SELECT * FROM "hep_proto_1_call"  WHERE (create_date between $1 AND $2 AND (  AND protocol_header->>'srcIp'= $3 )) LIMIT 2000
```

Thank you

**Comment by lmangani** [comment]
>  ERROR:  could not map dynamic shared memory segment

looks like you're possibly running out of memory or have too many packets per second for the allocated resources

**Comment by idanam-del** [comment]
@lmangani the memory use of the machine is 6% of 64gib

What too many packets per second for the allocated resources could mean exactly?

This only happens when i search this particular parameter. every other parameter or when i search no parameters to see all calls i don't have any issue. i also limit the query to 2000 using the ui parameter.

**Comment by lmangani** [comment]
No idea. You would have to provide some context - we don't even know the OS/version you're using. Everything matters.

**Comment by idanam-del** [comment]
@lmangani its deb 11 and i installed using your script "homer_installer.sh" to install postgres, homer app and heplify server

Homer is version 7.10.24

**Comment by lmangani** [comment]
> Weird thing it worked before and it somehow broke in the last few days.

I think this is extremely important. Nothing had changed in the project over the last weeks, so you should first review local changes impacting the setup somehow. Since it was all working, we can assume this is not a general issue, unless other users can report/replicate this same condition.

**Comment by idanam-del** [comment]
@lmangani hmm i did installed Prometheus docker on the machine before this happened and connected the heplify-server to it and im very happy with it i must say.

Could it be possible it affected somehow?

**Comment by kYroL01** [comment]
Hi @idanam-del it could be, but as Lorenzo said, if it worked before and suddenly not, I suggest you review your steps from A to Z, maybe you can spot some inconsistencies.
I'm closing this issue. Reopen if you find something useful for the community.
Thank you
