### ISSUE TITLE
Duplication with 'Dedup'  set to 'true'

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/heplify-server#526]
![image](https://github.com/sipcapture/heplify-server/assets/130898221/0cad15bb-f5cf-4542-ab80-cffa51b95eb8)

Hey, as you can see in the image a duplication of INVITE messages, they have the same content.

But they are from different sources. My setup is as follows:

The call flow in the image is from Freeswitch to Freeswitch gateway.

In the Freeswitches - i use the native agent that sends to localhost+ Heplify as Hep collector that listens to localhost. I use this To be able to send HEP in TLS to the homer server.

Could it be that when a hep collector sends HEP packets - The heplify-server cannot deduplicate them even with the feature to so is enabled?

**Comment by lmangani** [comment]
HOMER is designed to capture everything. None of our elements "drop" duplicates, quite the opposite. Deduplication is done by the API upon reading, and usually when it doesn't work for a specific pattern, the messages are either not hashing the same or too far apart in time.

**Comment by idanam-del** [comment]
@lmangani I see thank you. I'm pretty sure they are the same. how far apart in time do they need to be in order for it to not to work?

**Comment by lmangani** [comment]
You can try hash the raw messages and see if they match.

**Comment by idanam-del** [comment]
@lmangani thank you, ill check it out
