### ISSUE TITLE
Prometheus metrics 

### ISSUE THREAD

**Issue by nickakt** [sipcapture/heplify-server#528]
Hello, 

Is it possible to add custom headers to heplify_method_response

https://github.com/sipcapture/heplify-server/blob/master/metric/prometheus.go

something like that 

type Prometheus struct {
	TargetEmpty bool
	TargetIP    []string
	TargetName  []string
	TargetMap   map[string]string
	TargetConf  *sync.RWMutex
         **CustomHeaders []string**
	cache       *fastcache.Cache
}

**p.TargetName = strings.Split(cutSpace(config.Setting.PromCustomHeaders), ",")**

**methodResponses.WithLabelValues("unknown", "", pkt.NodeName,  pkt.SIP.FirstMethod, pkt.SIP.CseqMethod,pkt.**SIP.CustomHeader.X-MY-header**)).Inc()**

**Comment by lmangani** [comment]
Hello @nickakt 

I'm not sure this is possible. What would the goal be? Could you provide some practical examples or an analogy in any other project using this?

**Comment by nickakt** [comment]
hello, 
For example, I have multiple trunks and multiple users. I would like to count ASR per user/trunk using Prometheus 

could you clarify 

_You can already add headers and labels using a scraper if you want to._

**Comment by lmangani** [comment]
User level tags are not supported. You can do this with IP tags/trunks using the PromTargetIP/Name parameters:

```
# PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
# PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
```

**Comment by nickakt** [comment]
Iam using Kamailio, how to insert PromTargetName? Or maybe I don't understand how it works. Tnx

**Comment by lmangani** [comment]
Nothing to do on the HEP sender. Those are `heplify-server` settings to map IP/CIDR to a name in the statistics.
