### ISSUE TITLE
Prometheus was not accessed on installation and access is denied http and telnet on port 9090

### ISSUE THREAD

**Issue by izaacmenezes** [sipcapture/heplify-server#534]
Good afternoon, I have a problem with prometheus and possibly with alertmanager as well, when uploading the prometheus version it does not return a possible error, at least in a clearer way, the container uploads smoothly, below are some examples of how the scope is structured

Docker ps: 

![image](https://github.com/sipcapture/heplify-server/assets/72463556/53090d16-5f65-4905-9a09-5fc25f49f81a)

Log Prometheus:

[log prometheus.txt](https://github.com/sipcapture/heplify-server/files/12501037/log.prometheus.txt)

IPTABLES:

![image](https://github.com/sipcapture/heplify-server/assets/72463556/2d4a1427-d3a9-49a1-97b8-915c625c609b)

netstat -tpln:

![image](https://github.com/sipcapture/heplify-server/assets/72463556/d009141a-eb15-4630-b05c-4823f9cd1bd8)

I also tried to integrate directly through grafana, both through the grafana that was generated automatically, and the grafana that I have separated, I tried to integrate with the password admin, default admin of prometheus, however without success, I received it in grafana badgateway, if you can help with the theme, thank you too much

Grafana:

![image](https://github.com/sipcapture/heplify-server/assets/72463556/70f7204b-31f0-41d4-ba3c-1c0e011e0a00)

**Comment by lmangani** [comment]
I'm very sorry we cannot support you with the prometheus setup and troubleshooting.

What's important to know is heplify-server (homer) exposes a /metrics endpoint you can scrape into prometheus or qryn but from there on, its not our stack so you have to refer to the documentation and/or project examples for Grafana/Prometheus/etc.
