### ISSUE TITLE
heplify-server resets TCP connection

### ISSUE THREAD

**Issue by sergey-safarov** [sipcapture/heplify-server#536]
I have started `heplify-server` as docker container using command
```
/usr/bin/docker run -t --rm --name heplify-server --network=host \
         -e "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060" \
         -e "HEPLIFYSERVER_HEPTCPADDR=" \
         -e "HEPLIFYSERVER_DBSHEMA=homer7" \
         -e "HEPLIFYSERVER_DBDRIVER=postgres" \
         -e "HEPLIFYSERVER_DBADDR=127.0.0.1:5432" \
         -e "HEPLIFYSERVER_DBUSER=root" \
         -e "HEPLIFYSERVER_DBPASS=homerSeven" \
         -e "HEPLIFYSERVER_DBDATATABLE=homer_data" \
         -e "HEPLIFYSERVER_DBCONFTABLE=homer_config" \
         -e "HEPLIFYSERVER_DBDROPDAYS=31" \
         -e "HEPLIFYSERVER_LOGLVL=info" \
         -e "HEPLIFYSERVER_LOGSTD=true" \
         -e "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096" \
         -e "HEPLIFYSERVER_DEDUP=false" \
         -e "HEPLIFYSERVER_LOKIURL=http://[2600:1f18:578:5700::12]:3100/api/prom/push" \
         -e "HEPLIFYSERVER_LOKITIMER=2" \
         sipcapture/heplify-server:latest ./heplify-server -heptcpaddr 0.0.0.0:9060
```
heplify-server listening TCP/9060.
Kamailio send HEP3 message but server resets connection.
PCAP attached.
[hep.pcap.gz](https://github.com/sipcapture/heplify-server/files/12570541/hep.pcap.gz)

**Comment by lmangani** [comment]
>         -e "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060" \
>         -e "HEPLIFYSERVER_HEPTCPADDR=" \

mmmmm... with this config and HEPTCPADDR empty your service would be listening for UDP only. Configure HEP TCP on a different port if that's what you'd like to use from kamailio.

**Comment by sergey-safarov** [comment]
I see my typo and will retest.

**Comment by sergey-safarov** [comment]
I have retested and looks like TCP connection is stable.
No issue there.

**Comment by lmangani** [comment]
Thanks for confirming back!
