### ISSUE TITLE
correlation id lost when pushing to loki

### ISSUE THREAD

**Issue by tsearle** [sipcapture/heplify-server#541]
currently heplify-server doesn't preserve the hep3 filed for correlation id when sending to loki.

This makes it impossible to correlate RTCP metrics with a call (as the json of the rtcp report doesn't have even a sip call-id in it)

one possible option would be to add the correlation id into the json of message?

**Comment by lmangani** [comment]
Adding additional headers into the JSON payload seems a sensible option and since it can be used selectively it should not impact cardinality 👍 although we MIGHT need some type of label to declare the object contains correlation info to skim faster
