### ISSUE TITLE
Provide an entrypoint for docker image

### ISSUE THREAD

**Issue by crazybolillo** [sipcapture/heplify-server#553]
I am wondering why the docker image has no entrypoint, it was unexpected having to supply a command entry in the docker compose file.

**Comment by lmangani** [comment]
@crazybolillo you don't have to supply any command. the heplify-server container runs a single static binary and can be fully configured using ENV variables. You can of course build your own container with an entrypoint if you need more complexity.

**Comment by lmangani** [comment]
I see what you mean - but the CMD is all that's needed. We might add it back although most recipes provide it ad-hoc to allow specifying configuration, etc.
