### ISSUE TITLE
Search by reason_phrase / method text.

### ISSUE THREAD

**Issue by W1ck3dZA** [sipcapture/heplify-server#559]
Is it possible to enable the option to search by reason_phrase or method text and not just the method codes like 403 or 404.

This use to be possible in Homer 5 UI but cant seem to get it working in Homer 7.

I would ideally like the option to search for different strings and also display them in results table.

**Comment by adubovikov** [comment]
This is possible by using the "message" field in H7

**Comment by W1ck3dZA** [comment]
> This is possible by using the "message" field in H7

@adubovikov Thanks so much for the response.. Can you guide me in the right direction to add this, should I add this to the header config in heplify-server.toml as sipheader = ["message"] or is it only required in the mapping on the ui somehow ?

**Comment by W1ck3dZA** [comment]
Hi 

We can close this as I have moved this request to homer-app as that seems a better location for this.

[[https://github.com/sipcapture/homer-app/issues/573](url)](https://github.com/sipcapture/homer-app/issues/573)
