### ISSUE TITLE
Multiple Postgresql Servers

### ISSUE THREAD

**Issue by abitrusty55** [sipcapture/heplify-server#560]
Is it possible to send data to multiple database servers? I'm trying the below but there doesn't appear to be any connection attempt to either of them

DBAddr                = "10.10.20.10:5432,172.27.27.10:5432"

I have the same postgres username/password setup on both Homer servers and both postgres can receive data from external sources. Works to them individually

Have also tried "10.10.20.10:5432","172.27.27.10:5432" - but that gives a syntax error

**Comment by lmangani** [comment]
That's currently not supported. You should rather explore database replication or clustering.
