### ISSUE TITLE
Discard option

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#78]
Hi again,

Is there a way to discard cseq method (like heplify's -dim) for packets collected by captagent or any others hep tool ?

thx

**Comment by negbie** [comment]
Hi, for now heplify-server has no option to discard SIP methods. I did not include this because this is possible inside heplify and captagent. If you want to use captagent and drop some methods have a look at the bottom page:
https://github.com/sipcapture/captagent/wiki/Capture-Plans

**Comment by dvillaume** [comment]
Thanks for this answer, i tought about it but was lazy to process on all captagents

**Comment by khorsmann** [comment]
Should be easy with ansible or Puppet to do this for you.

**Comment by negbie** [comment]
It's easy to implement. I will do it this evening after the :soccer: matches ;)

**Comment by dvillaume** [comment]
I'll see to add some captagent playbook, it's just i used to do it on
server-side with kamaillio. As i planned to abandon captagent so if
undocumented option were there i would have save time.

Le lun. 18 juin 2018 à 18:38, Karsten Horsmann <notifications@github.com> a
écrit :

**Comment by dvillaume** [comment]
Lol, have a nice match.

Le lun. 18 juin 2018 à 18:44, Eugen Biegler <notifications@github.com> a
écrit :

**Comment by negbie** [comment]
Since version 0.93 you can use DiscardMethod to filter SIP methods. Keep in mind this is an array option so use it like that:

DiscardMethod   = ["OPTIONS","NOTIFY"]

**Comment by dvillaume** [comment]
You're a crazy worker, thanks for the tenth time.

I didn't hope you would implement it.

Hope you've enjoyed the match and not only worked tonight.

Le lun. 18 juin 2018 à 22:56, Eugen Biegler <notifications@github.com> a
écrit :

**Comment by negbie** [comment]
Hehe thanks. Yes I enjoyed the matches. This feature took me only 5 min.

**Comment by negbie** [comment]
Feature implemented. Will close here.
