### ISSUE TITLE
guide/how-to to send metrics data to elasticsearch

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/heplify-server#82]
could you refer any examples/guides that would help to understand how to configure heplify to send metrics to elasticsearch db?

**Comment by negbie** [comment]
I added elasticsearch 5+6 output today with this commit
https://github.com/sipcapture/heplify-server/commit/1956f9d6e02d025d8795a7a18617c24da1c1b952

I need to push the new heplify-server version to dockerhub and extend the docker compose file with the new esaddr option. I will do that tomorrow morning.

**Comment by JonConnor** [comment]
awesome thanks for the info will wait for that!

**Comment by negbie** [comment]
To clarify this. I don't send metrics to es. This makes no sense. I send every single SIP header and hep field to es. For metrics I use Prometheus.

**Comment by lmangani** [comment]
@negbie Telegraf can already do the job pretty well, there are literally zero changes needed for metrics, nor any way to use the SIP in ES so that also makes limited sense in my experience

**Comment by negbie** [comment]
@Imangani good reminder! @JonConnor so if you only want to send  metrics to es look into the telegraf es output plugin
https://github.com/influxdata/telegraf/blob/master/plugins/outputs/elasticsearch/README.md

**Comment by negbie** [comment]
I still highly recommended Prometheus or Influx for metrics only!

**Comment by JonConnor** [comment]
got it, thanks for the clarification.  Look forward to trying it out.

**Comment by negbie** [comment]
Hi, I pushed the latest image to dockerhub and now you will find inside the docker-compose file the option HEPLIFY_SERVER_ESADDR

fill this with something like http://yourhostip:9200 and pull the latest image with docker-compose pull && docker-compose up

**Comment by negbie** [comment]
If you want metrics inside es look into the hom5-hep-influx folder. There is a conf folder with a telegraf config file. In this you could add the es output from the link I already posted.

**Comment by negbie** [comment]
Oh btw the es index will be heplify-server

**Comment by JonConnor** [comment]
@negbie awesome work sir! came right up without any issues. 

i already had a homer5/kamailio/heplify-client setup working, but using the docker-compose was so much less fuss.  changed the heplify-clients to send to the new heplify-server docker instance and everything worked like a charm.

**Comment by games130** [comment]
@JonConnor Do you mind sharing what you plan to do with elastic search? Like what kind of data you are getting which prometheus is not already giving.

**Comment by lmangani** [comment]
@games130 I guess simply when someone is already using Elasticsearch its easier to keep one platform, I guess. Telegraf allows to convert all metrics to Elasticsearch format so there's really no difference other than the cost of operation and resources.

**Comment by JonConnor** [comment]
@games130 I have a lot of different data streams going into my ELK stack (various log files, snmp traps, etc) all from different VOIP servers and endpoints.  Wanted a way to incorporate some other data into the dashboard such as RPS/CPS, etc.   The Grafana dashboard that @negbie provides with the Docker setup is awesome, so right now using both Kibana and Grafana.  But eventually would like to have everything in one place.
