### ISSUE TITLE
Unhandled AlegID = "X-BroadWorks-Correlation-Info"

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/heplify-server#84]
Hello,

I use an unreferenced Header ""X-BroadWorks-Correlation-Info" and i would like to use as the AlegID.

I saw in https://github.com/sipcapture/heplify-server/issues/31 that you need to dclare the header in parser.

Would it be possible to add this one ? 

Thanks.

**Comment by lmangani** [comment]
Since I don't know many non-profits using Broadworks, how about a donation to sponsor such feature? :)

**Comment by negbie** [comment]
To do this right I will need to change the sipparser in a way that we can pass an string array from heplify-server to the parser. What I did in the issue you mentioned was ugly and I don't like it but forget about it. So thanks to bring this up again ;)

Because I don't want to break existing configs I will need to change the AlegID option to something else. I think I will go for AlegIDs.

**Comment by negbie** [comment]
@lmangani I guess I need to implement this anyway. Right now the AlegID option is broken so it was on my todo list but I forgot it. But of course are donations appreciated ;)

**Comment by negbie** [comment]
Done, I did it like @lmangani suggested in issue https://github.com/sipcapture/heplify-server/issues/31 with an array you can set inside the config file. I added a line to the example configs. You can configure it like this:

AlegIDs         = ["X-CID","P-Charging-Vector","X-BroadWorks-Correlation-Info"] 

So when you have different vendors which require a AlegID you can use multiple.

**Comment by dvillaume** [comment]
Thanks for the change.

For donation, i agree you all deserve it for the work provided and the quality of the tools, i don't have the decision on my own but i promise i will discuss it with my people.

**Comment by games130** [comment]
tested with the new changes, "P-Charging-Vector" for the AlegIDs is working well.

**Comment by negbie** [comment]
Thank you for testing!! Closing.

**Comment by hiaz** [comment]
Hi @negbie,

first of all: thank you for your work!

Is it possible that you update the related docker container https://hub.docker.com/r/negbie/heplify-server/ so that we have this fix also there in place?

Thank you.

**Comment by negbie** [comment]
Hi @hiaz 
sure I will do it after the the :soccer:  match ;)

**Comment by lmangani** [comment]
@hiaz @negbie the official containers are automatically built at each push already on the sipcapture repo

**Comment by negbie** [comment]
@lmangani yeah I guess I changed it sometime ago because the sipcapture repo at that time did not use multistage builds so the image was to large for my taste ;)

**Comment by negbie** [comment]
@lmangani maybe we can use multistage builds in the sipcapture repo too so I can use that?

**Comment by lmangani** [comment]
@negbie of course its possible it just need a pinch of will to coordinate right?

**Comment by negbie** [comment]
@hiaz pushed the latest build to dockerhub.

**Comment by hiaz** [comment]
Cool, thank you. Call correlation works perfectly now.

**Comment by dvillaume** [comment]
@negbie 

I tried to get the correlation ID working for "X-BroadWorks-Correlation-Info" , but i don't see any populated callid_aleg 

Definition on heplify-server environment variables: 
  -alegids
        Change value of AlegIDs. (default ["X-BroadWorks-Correlation-Info"])

Request :
select distinct callid,callid_aleg,correlation_id from sip_capture_call_20180703 where msg like '%X-BroadWorks-Correlation-Info: 0ff7277e-251e-482a-85fc-8ae2ff03f629%';

+----------------------------------+-------------+----------------------------------+
| callid                           | callid_aleg | correlation_id                   |
+----------------------------------+-------------+----------------------------------+
| b5eaa72fb158a41b29de44eb7460ae81 |             | b5eaa72fb158a41b29de44eb7460ae81 |
+----------------------------------+-------------+----------------------------------+

Do i miss anything ?

**Comment by negbie** [comment]
Yes it's because you use an outdated version of heplify-server. When you use docker just pull the new version. If you use a the binary from releases wait some hours as I will release 0.94 today.

**Comment by dvillaume** [comment]
I 've already done a docker pull recently i'm on a 0.93 and i well see alegids and no more former alegid.

**Comment by negbie** [comment]
Ah ok. Hmm mby a typo anywhere?

**Comment by negbie** [comment]
Could you please pull the latest image from sipcapture/heplify-server:latest
I created autobuild on that repo so this should be version 0.94 already. In this version I print out all the config settings at start. Could you please paste them here (strip your sensitive data first please)

**Comment by dvillaume** [comment]
Thanks to the trick, it permited me to figure out how to pass array in the environment variables 

In heplify-server.toml 
AlegIDs         = ["X-CID","X-BroadWorks-Correlation-Info"]

while in docker-compose.yml
      - "HEPLIFYSERVER_ALEGIDS=X-CID,X-BroadWorks-Correlation-Info"

i've tried this syntax before but i guess that was before pulling the latest docker.

Thanks again.

**Comment by negbie** [comment]
Exactly. To pass an string array as env var or flag simply use a comma separated string without whitespaces inbetween. Only inside the config file you should use
AlegIDs = ["X-CID","X-BroadWorks-Correlation-Info"]

**Comment by dvillaume** [comment]
Sorry to have annoyed you for such details.
Have a good day

Le mar. 3 juil. 2018 à 14:07, Eugen Biegler <notifications@github.com> a
écrit :

**Comment by negbie** [comment]
No problem. Always happy to help. Same to you!
