### ISSUE TITLE
Could not find a valid Call-ID in packet

### ISSUE THREAD

**Issue by hiaz** [sipcapture/heplify-server#87]
We are testing heplify-server as a replacement for the kamailio solution. The first impression is very good. 

With some packets I run into the following problem:

```
2018/06/27 11:54:15.076996 decoder.go:101: WARN Could not find a valid Call-ID in packet
"REGISTER sip:172.16.214.177 SIP/2.0\r\n
Via: SIP/2.0/UDP 10.0.3.1:5063;branch=z9hG4bK8c39.0c1a4d08fd1ea16d4d3214184ed4fa19.0;i=2\r\n
Via: SIP/2.0/TLS 172.16.214.1:62306;received=172.16.214.1;rport=62306;branch=z9hG4bKPjKui9oP4ADG7HLaCQttEpK7AOVbAeaEPL;alias\r\n
Max-Forwards: 69\r\n
From: <sip:on570MfDxSGbUF5@server>;tag=q3vJVOgNCd60bu2kyfs61rbA76qyYk.L\r\n
To: <sip:on570MfDxSGbUF5@server>\r\n
P-cs-if: ifens33.cloudstack\n
Call-ID: VgCxwcYMBL2BJ45VZdAgs-ufeElh-C1z\r\n
CSeq: 9956 REGISTER\r\n
...
```

As you can see the Call-ID is in the packet. But somehow the parser fails...

**Comment by negbie** [comment]
Yip, its the line above the Call-ID

P-cs-if: ifens33.cloudstack\n

My sipparser splits by \r\n

**Comment by negbie** [comment]
I guess I need to handle those cases better.

**Comment by hiaz** [comment]
@negbie Thank you for your fast reply. Yes, sure, would help if your parser would be more liberal ;). But the truth is that this is a bug on our side. Thank you for pointing out the issue.

**Comment by negbie** [comment]
@hiaz fixed with latest sipparser commits. Latest docker build has this fix too.

**Comment by hiaz** [comment]
works, thank you! But I also fixed our sip router to add the \r like the rfc says.
